# Dankwoord/Voorwoord {.unnumbered}

Het INBO monitoringsprogramma wordt uitgevoerd met de financiële steun van de Vlaamse Waterweg nv, Maritieme Toegang (MT) en het Agentschap voor Natuur en Bos (ANB).
Waarvoor dank.
De monitoring zou niet mogelijk geweest zijn zonder de bemanning van de schepen SCALDIS I, Scheldewacht II, Veremans, Henry de Vos en de Parel.
Dank aan Erwin De Backer (Waterbouwkundig laboratorium) voor de uitstekende planning van de bootcampagnes.

De zoogdierengegevens werden met toestemming ontleend uit de databank van Waarnemingen.be (Natuurpunt VZW).

De superdeluxe dataverzameling en het laboratoriumwerk voor watervogels, hyperbenthos, macrozoöbenthos en de hoogteraaien werden uitgevoerd door Dimitri Buerms, Ada Coudenys, Nico De Regge, Kenny Hessel, Charles Lefranc, Vincent Smeekens, Jan Soors en Frederic Van Lierop.
Topteam Estuaria!

De vismonitoring en data aanlevering werden voor ons verzorgd door INBO team MHAF (Monitoring Herstel Aquatische Fauna).
Medewerkers van team MHAF leverden opnieuw prachtig werk: Olja Bezdenjesnji, Franky Dens, Marc Dewit, Linde Galle, Isabel Lambeens, Yves Maes, Thomas Terrie, Grim Boddez en Laura Van de Meersche.
Voor de ankerkuilvisserij konden we rekenen op Sjaak, Job en Davy.
Dankzij hun professionele vaardigheid zijn de campagnes in 2022 vlot verlopen en kon ons onderzoek in de beste omstandigheden worden uitgevoerd, dank u wel.
Mevrouw Cabradilla (de Vlaamse Waterweg nv) verleent ons altijd vlot de nodige aanmeertoelatingen, hartelijk dank.

We zijn ook de mensen van BMK en in het bijzonder Els Lommelen erkentelijk voor de technische ondersteuning en begeleiding bij het uitwerken van de rapportering via rmarkdown, bookdown en github.

# Samenvatting {.unnumbered}

Deze rapportage geeft toelichting bij de datarapportage van de geïntegreerde systeemmonitoring van het Schelde-estuarium, kortweg MONEOS (= MONitoring Effecten OntwikkelingsSchets), uitgevoerd door het INBO.
De nadruk ligt op de resultaten van het monitoringsjaren 2022-2023 voor de aspecten leefomgeving voor flora en fauna en ecologie.

We lichten de langjarige trends toe en we voeren de Evaluatiemethodiek Schelde-estuarium (EMSE) uit voor verschillende hoofdstukken.

We bespreken de ecotopenkaart van 2022 van de Beneden-Zeeschelde.
Het globale plaatje over de lange termijn is een uitruiming van de vaargeul met steiler wordende oevers als gevolg. De schoroppervlakte neemt ook verder toe, vooral in nieuwe Sigmagebieden. 
In het tot nu toe toegepaste Zeeschelde ecotopenstelsel 1.0 werden subtidale (water) en litorale (slik) ecotopen vooralsnog uitsluitend op basis van diepte en overspoelingsregime onderscheiden, zonder ecologische validatie.
Op basis van recent onderzoek werd het ecotopenstelsel Zeeschelde 2.0 voorgesteld.
In deze rapportage wordt de ecotopenkaart voor de Beneden‐Zeeschelde 2021 volgens beide ecotopenstelsels voorgesteld en vergeleken.
Zo kunnen we nu in het sublitoraal de ecologisch meest waardevolle zones identificeren.
8.5% van het sublitoraal blijkt laagdynamisch waardevol habitat en situeert zich grotendeels in het ondiep subtidaal.
De klassificatie resulteert verder vooral in een verschuiving van middelhoog naar hoog slik zacht substraat of hard antropogeen (op hoog slik). De steile slikken zijn in hoofdzaak antropogeen verstevigde breuksteenzones.

Op basis van een statistische verkenning tonen de sedimentdata verzameld bij de macrozoöbenthosstalen significant slibrijker wordende bodems. Dit is opvallend voor de intertidale habitats van de zijrivieren en de Zeeschelde. Opvallend is dat ook de geul van de zone met sterke saliniteitsgradiënt (Beneden-Zeeschelde) significant slibrijker wordt. Nochtans is de variatie in sedimentsamenstelling hier net groot. De geul in zone met korte verblijftijd lijkt anderzijds minder slibrijk te worden (nog niet significant).

De soortenrijkdom van het macrozoöbenthos (exclusief Oligochaeta) lijkt de laatste jaren licht te stijgen in de meeste zones van de Zeeschelde. De shannondiversiteit in het intertidaal neemt toe in vrijwel alle zones sinds 2015.
In het subtidaal zijn er veel diversiteitsschommelingen.
In de zone met sterke saliniteitsgradiënt is er een sterke toename te noteren van schelpdieren. Vooral van de brakwaterkorfschelp (*Potamocorbula amurensis*) in het laag intertidaal en subtidaal en de platte slijkgapper (*Scrobicularia plana*) in het intertidaal.
Door de bemonstering op kleine oppervlakte is de kans op een toevalstreffer bij grotere organismen te groot (en de fout op de biomassaberekening te groot). Dit verklaart wellicht de lagere biomassaberekening voor de zone met sterke saliniteitsgradiënt in 2022. Om dit te verbeteren hebben we onze monitoringsmethodiek aangepast met een aanvullende staalname, gericht op bivalven, met grotere core en levend zeven. In de Boven-Zeeschelde werd een belangrijk deel van de systeembiomassa gerealiseerd in de zone zoet korte verblijftijd, meer  bepaald in de Scheldemeander tussen Melle en Gentbrugge. We zien dat de bodemdierbiomassa hier de laatste jaren daalt. Deze daling stuurt ook mee de algemene patronen van de bodemdierbiomassa in de Zeeschelde.


De soortenrijkdom van het hyperbenthos schommelt van jaar tot jaar.
Biomassa vertoont een patroon met in de zones stroomopwaarts van Antwerpen een gestage
toename na juni tot het einde van het jaar. Dit bevestigt de aanname dat dit voor veel hyperbenthische
soorten en vooral voor garnalen, aasgarnalen en vissen, een opgroeigebied is. De evolutie van densiteiten
en biomassa overheen de monitoringsjaren is onderhevig aan grote schommelingen die samen hangen
met goede en slechte jaren van specifieke soorten. Sinds 2022 zien we bijzonder lage hyperbenthosdensiteiten en dalende totale hyperbenthosbiomassa in het systeem. Vooral de grijze garnaal en de langneussteurgarnaal zijn, na elk
een eigen bloeiperiode, nu al enkele jaren in lagere aantallen aanwezig. Dit resulteert in een lagere predatiedruk door deze groep in het voedselweb. 

In deze rapportage wordt de vismonitoring in 2023 op de Zeeschelde met behulp van de ankerkuil en fuiken besproken. 2023 was net als 2022 een bodemjaar voor het aantal spieringen in de Zeeschelde. Dit geldt zowel voor de ankerkuil als voor de fuikvangsten, waardoor het beeld van de absolute dominantie van deze soort zelfs in het pelagiaal vervaagt. Grondels (brakwatergrondel en ook dikkop) zijn dominant in de aantallen in de oligohaliene en zoete zones. Sinds 2022 duikt de visindex voor de zoete zone, met een ontoereikende kwaliteitsbeoordeling, voor het eerst sinds 2009 onder die van de brakke en oligohaliene zones. Deze situatie moet nauw opgevolgd worden.
Naar estuarien habitatgebruik overheersen de trekvissen de visgemeenschappen van de Zeeschelde in aantal en biomassa.
Het estuarium heeft dus weer zijn functie opgenomen in de levenscyclus van deze soorten.
Om te evalueren of de populaties echt gevestigd en duurzaam zijn is echter een cohorte-analyse van de betrokken soorten in tijd en ruimte nodig. Naar dieet overheersen omnivore soorten, een normale opportunistische dieetkeuze in een estuarium met wisselende levensomstandigheden. Toch wordt het voedselweb stilaan complexer. Dit uit zich in een toename van benthivore en piscivore soorten. Om dit beter te evalueren moet voor de belangrijkste soorten rekening gehouden worden met de dieetshift die ze maken in de overgang van juveniel naar adult. In de rapportage wordt naast een evaluatie volgens de EMSE een alternatieve beoordelingsmethode voorgesteld bruikbaar als insteek voor een toekomstige herwerking van de methodiek.   

Opvallend is dat we veel schommelingen zien in het hyperbenthos en de vissen. De vraag kan gesteld worden in hoeverre
de sterk wisselende densiteiten een natuurlijk fenomeen zijn in het bovendeel van
een estuarium, en dus als negatief beoordeeld moet worden. Het is waarschijnlijk deels eigen aan een
opgroeigebied als de Zeeschelde dat er extreem succesvolle recruteringsjaren zijn waarin alle factoren
mee zitten, en waarin één of enkele soorten de gemeenschap domineren. Anderzijds is meer ecologische
kennis nodig over waarom soorten goede en slechte jaren afwisselen, en om natuurlijke en door de mens
beïnvloede oorzaken te kunnen onderscheiden. Concluderend is er een noodzaak om onderzoek op te starten om met innovatieve monitoring (bijvoorbeeld met echosounding) continue data te verzamelen en/of om ruimtelijk een beter beeld te krijgen van het habitatgebruik. Dit onderzoek moet helpen om de variaties in het waterleven in ruimte en tijd te verklaren.

Over de periode 2009-2023 bekeken is er op het niveau van de Zeeschelde een dalende trend te zien in het aantal overwinterende watervogels.
De trendindex toont wel een toename in de sterke saliniteitsgradiënt. Dit is vooral te wijten aan de toename van scholeksters, bergeenden en in 2023 ook tureluurs. De toename van de scholekster is vermoedelijk het gevolg van de toename aan schelpdieren (zie hoofdstuk Macrozoöbenthos). Bovendien trok de ontpoldering van Hedwige-Prosper sinds 2021 heel wat watervogels aan die ook gebruik maken van de slikken van de Zeeschelde.
Opvallend is de negatieve trend van de zone zoet lang, vooral veroorzaakt door een zeer sterke afname van de wilde eend. 
De diversiteit is het grootst in de zone met een sterke saliniteitsgradiënt en laag in de Durme en de zone zoet lang.
De afname van de vogelaantallen langsheen de Zeeschelde wordt gecompenseerd door de toename van de vogelaantallen in de estuariene natuurontwikkelingsgebieden. In de ontpoldering van het Groot Schoor te Hamme verbleven zeer hoge aantallen wintertalingen en bergeenden. 
Dit resulteert tot vandaag niet in een totale toename van de watervogelaantallen binnen het estuarium (de vallei buiten beschouwing gelaten).

De evoluties in de broedvogelaantallen voor een selectie van goed te inventariseren soorten binnen IHD-gebied (wetlands en estuariene gebieden) worden besproken in deze rapportage.
Verscheidene soorten met doelstellingen komen tot 2023 nog steeds zelden tot broeden in het IHD‐gebied Schelde‐estuarium (grote karekiet, kwak, kwartelkoning, roerdomp en paapje), of werden nog nooit vastgesteld als broedvogel (purperreiger).
Grote karekiet en lepelaar lijken zich wel te vestigen als regelmatige broedvogel.
De zomertaling, baardman, woudaap en snor vertonen de laatste jaren een stijgende trend in de vallei van de Zeeschelde en haar tijgebonden zijrivieren. Voor het eerst wordt het doel van de zomertaling bereikt. Het valt op te merken dat het gebied Wal-Zwijn met een tussentijdsbeheer als wetland bijzonder succesvol was in het aantrekken van doelsoorten zoals roerdomp, woudaap, zomertaling, snor, grote karekiet en dodaars.
De predatiewerende omheiningen in het noordelijk gebied hebben duidelijk een effect met hogere broedaantallen sinds 2021 van kluut, tureluur en een beperkte toename van grutto.
De bruine kiekendief blijft stabiel (maar laag).
Behalve voor zomertaling, blauwborst, rietzanger en dodaars worden de doelstellingen voor geen enkele soort gehaald.

De bever koloniseerde ondertussen bijna alle geschikte habitats in het Zeeschelde-estuarium en neemt nu opvallend toe langsheen de Grote Nete.
Het geschatte aantal beverterritoria in de vallei van de Zeeschelde en tijgebonden zijrivieren wordt geschat op ca.
73.
Dit stemt overeen met 44 families.
De IHD-doelstelling voor bever is daarmee gerealiseerd.
Het aantal waarnemeningen van otters is stabiel.
De instandhoudingsdoelstellingen zijn echter zeker nog niet vervuld.
Het aantal waargenomen gewone zeehonden was lager dan voorgaande jaren. Er waren slechts twee waarnemingen van bruinvis en grijze zeehond.


De detail-hoogtemetingen op raaien langsheen de Zeeschelde illustreren en onderbouwen de waargenomen ontwikkelingen in de ecotopenkaarten en zijn indicatief als early warning voor morfologische veranderingen in het systeem. Algemeen kunnen we stellen dat er in de Beneden-Zeeschelde relatief weinig gewijzigd is ten opzichte van de langjarige trend. De trends zijn eerder doorgaand. Ter hoogte van Lillo Haven (LH) is nu voor het eerste jaar sterke erosie met vorming van erosieklif op het slik vastgesteld. 
De zone rond Antwerpen en Hoboken (GW en HO) wordt gekenmerkt door sterke morfodynamiek (zandmobiliteit) toe tussen de jaren erosie of sedimentatie van zand ter hoogte van de Galgenweel‐raai (GW). Hier verliest het slik wel het grootste deel van het
slib waarbij meer harde substraat komt bloot te liggen. Dit illustreert de hoge dynamiek in deze zone.
Daarnaast zijn er opvallend veel aanwijzingen voor trendbreuken in 2022 en 2023 in hoog en middelhoog slik in de
Boven‐Zeeschelde met plotse erosie of stagnatie van de sedimentatie. In de zone tussen Rupel- en de Durmemonding wordt de stagnatie van sedimentatie en omslag naar erosie bevestigd. Hier is een trend tot verruiming van de vaargeul met gevolgen voor de slikken (minder sedimentatie tot trendbreuk naar erosie). 
Een verband met de bathymetrische veranderingen als gevolg van de verdieping afwaarts en/of de bagger- en zandwinningshoeveelheden in de Boven-Zeeschelde en Durme kan niet worden uitgesloten.
Het lijkt daarom raadzaam om deze evoluties nauw op te volgen om sterke irreversibele morfologische veranderingen zo ver stroomopwaarts te voorkomen.
Verder onderzoek naar de recente veranderingen in deze zone en mogelijke impact van huidige rivierbeheermaatregelen is zeer wenselijk.

Ook de oevererosie werd gemonitord op basis van de bathymetrische verschilkaart (2023 versus 2022, 2021 en 2020).
Deze kaarten dienen voornamelijk ter ondersteuning van de interpretatie van erosie van het hoger slik en schorrand als monitoring in functie van het oeverbeheer. Er wordt als signaalfunctie een erosie (en sedimentatie) van meer dan 50 cm gehanteerd. Zowel in de Boven‐ als Beneden‐Zeeschelde zijn grote dynamieken waargenomen in enkele zones. 
De waargenomen erosiezones vergen geen directe ingrepen, maar kunnen de voorbode zijn van toenemende erosieve druk op de hogere slikken en schorren zoals ook vastgesteld op de raaimetingen en zijn zones van aandacht. Vooral de erosie in de ondiepwaterzones van bochten in de Boven-Zeeschelde is opvallend.   
