# Vegetatiekaart

Fichenummer: S-DH-V-003 -- Vegetatiekartering

Bart Vandevoorde, Frederik Van Lierop, Vincent Smeekens & Koen Thibau

## Inleiding

Met behulp van schorvegetatiekaarten kan de evolutie van de habitatdiversiteit binnen het schorecotoop nader geëvalueerd worden. De basiseenheid van deze vegetatiekaart, is een homogene vegetatie-eenheid waaraan volgens een hiërarchisch systeem een habitat, formatie en vegetatietype zijn toegekend.

In Tabel \@ref(tab:Tabel1) is een overzicht gegeven van de vegetatiekaarten die van de schorren zijn gemaakt de voorbije decennia. De gebruikte methode, ruimtelijke afbakening en detailgraad zijn niet voor alle kaarten gelijk. Zo zijn de kaarten van 1992, 1996, 2003, 2013 en 2019 gemaakt aan de hand van de fotogeleide veldmethode. Remote sensing-technieken zijn gebruikt in 2007 om het hele Zeeschelde-estuarium te karteren (Bertels *et al*., 2008) en in 2011 voor de vegetatiekartering van de Beneden-Zeeschelde (Eurosense, 2012). Voor een overzicht van de historische kaarten en een toelichting bij de gebruikte codes verwijzen we naar Vandevoorde (2011).

Table: (#tab:Tabel1) Overzicht van de jaren waarvan vegetatiekaarten beschikbaar zijn. De verschillende deelgebieden zijn gekarteerd volgens de klassieke karteringsmethode (A) of door middel van remote sensing-technieken (B).

  -------------------------------------------------------------------------------------------------
  **Deelgebied**       **1992**   **1996**   **2003**   **2007**   **2011**   **2013**   **2019**
  -------------------- ---------- ---------- ---------- ---------- ---------- ---------- ----------
  Beneden-Zeeschelde   A          A          A          B          B          A          A

  Boven-Zeeschelde     A          A          A          B                     A          A

  Durme                           A          A          B                     A          A

  Rupel                                      A          B                     A          A

  Zenne                                                 A B                   A          

  Dijle                                                 A B                   A          

  Kleine Nete                                           A B                   A          

  Grote Nete                                            A B                   A          
  -------------------------------------------------------------------------------------------------

Momenteel is de vegetatiekaart van 2019 in opmaak. Deze kaart zal de schorren van de volledige Zeeschelde, Durme en Rupel omvatten, inclusief de getijdenafhankelijke delen van de Ringvaart en Tijarm in het meest stroomopwaartse deel van het estuarium (regio Gent). Ook de ontpolderingen gerealiseerd in 2019 of ervoor maken deel uit van deze kaart (bijv. Wijmeers, Fasseit, Burchtse Weel, Potpolder Lillo). Naast deze ontpolderingen zijn ook de verschillende functionele gecontroleerd gereduceerd getijdengebieden (GGG's) in deze vegetatiekaart opgenomen (Bergenmeersen, Lippenbroek, Polders van Kruibeke). Van de verschillende GGG's is de vegetatiekaart overgenomen uit de OMES-rapportage (Maris *et al*., 2020).

In de zomer van 2019 zijn falsecolour infrared-beelden (FCIR) gemaakt van het volledige projectgebied, inclusief de nieuw aangelegde gebieden (GGG's en ontpolderingen). Met behulp van deze beelden is in 2020, 2021, 2022 en 2023 veldwerk verricht om grondwaarheidsgegevens te verzamelen.

In Van Ryckegem *et al*. (2022) is een voorlopige versie van de vegetatiekaart van 2019 van de Zeeschelde, Durme en Rupel gepubliceerd. In deze rapportage wordt geen nieuwe versie van deze vegetatiekaart ter beschikking gesteld. De definitieve versie van de kaart zal gepubliceerd worden in het datarapport van 2025 of in een aparte rapportage.

## Referenties

Bertels L., Houthuys R., Deronde B., Knaeps E., Vandevoorde B. & Van den Bergh E. (2008). Automatische kartering voor opvolging areaal slikken en schorren. Rapport VITO 2008/TAP/R/076, 137 p.

Eurosense (2012). Hyperspectraalmetingen en kartering van slikken en schorren van de Zeeschelde afwaarts Wintam in het kader van de geïntegreerde monitoring van het Schelde-estuarium (MONEOS-programma). Eindrapport 01/10/2012. In opdracht van W&Z Afdeling Zeeschelde.

Maris T., Baeten S., Van den Neucker T., van den Broeck T. & Meire P. (2020). Onderzoek naar de gevolgen van het Sigmaplan, baggeractiviteiten en havenuitbreiding in de Zeeschelde op het milieu. Geïntegreerd eindverslag van het onderzoek verricht in 2019, deelrapport Intergetijdengebieden. ECOBE 020-R266 Universiteit Antwerpen, Antwerpen.

Vandevoorde B. (2011). Systeemmonitoring vegetatiekartering. In Van Ryckegem G., (red.) (2011). MONEOS --Geïntegreerd datarapport Toestand Zeeschelde tot 2009. Datarapportage ten behoeve van de VNSC voor het vastleggen van de uitgangssituatie anno 2009. Rapporten van het Instituut voor Natuur- en Bosonderzoek INBO.R.2011.8. Instituut voor Natuur‐ en Bosonderzoek, Brussel.

Van Ryckegem G., Vanoverbeke J., Van de Meutter F., Vandevoorde B., Mertens W., Mertens A., Van Braeckel A., Smeekens V., Thibau K., Bezdenjesnji O., Buerms D., De Regge N., Hessel K., Lefranc C., Soors J. & Van Lierop F. (2022). MONEOS ‐ Geïntegreerd datarapport INBO: Toestand Zeeschelde 2021. Monitoringsoverzicht en 1ste lijnsrapportage Geomorfologie, diversiteit Habitats en diversiteit Soorten. Rapporten van het Instituut voor Natuur‐ en Bosonderzoek 2022 (26). Instituut voor Natuur‐ en Bosonderzoek, Brussel.

