---
params:
  hoofdstuk: "090_vissen"
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile,
                          encoding=encoding,
                          output_dir = paste0(rmarkdown::yaml_front_matter(inputFile)$params$hoofdstuk, 
                          "/output")
                          )})

title: "visdata fuiken"
output:
  bookdown::word_document2: default
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, error=FALSE, warning=FALSE, message=FALSE, cache=FALSE)

```


```{r libraries}

library(tidyverse)
library(lubridate)
library(readxl)
library(writexl)
library(inbodb)

library(rprojroot) ## workaround pad

```


```{r, pad}

# inlezen van variabelen
# pad naar data : pad_data
# pad naar tabellen : pad_tabellen
# pad naar figuren : pad_figuren

run_pad <- function() {
  
  source(find_root_file("../pad.R", criterion = is_rstudio_project))
  
  pad_data <- maak_pad(params$hoofdstuk, "data")
  pad_figuren <- maak_pad(params$hoofdstuk, "figuren")
  pad_tabellen <- maak_pad(params$hoofdstuk, "tabellen")
  
  # print(ls())
  
  sapply(ls(), function(x) assign(x, get(x), .GlobalEnv))
  
}

run_pad()

```


```{r, variabelen}

run_variabelen <- 
  function () {

    jaren <- 2009:2020
    vangstmethode <- c('Schietfuik')
    
    # Zeeschelde vissen
    locaties_name <- "fuikvangsten_Zeeschelde_locaties"
    metadata_name <- "fuikvangsten_Zeeschelde_metadata"
    filename <- "fuikdata_Zeeschelde"
    
    # zijrivieren vissen
    # locaties_name <- "fuikvangsten_zijrivieren_locaties"
    # metadata_name <- "fuikvangsten_zijrivieren_metadata"
    # filename <- "fuikdata_zijrivieren"
    
    locaties <-
      read_xlsx(str_c(pad_data, "metadata VLIZ/", locaties_name, ".xlsx"))
    locatie_nrs <- locaties$locatiecode %>% as.character()
    locatie_namen <- locaties$locatie

    # print(ls())

    sapply(ls(), function(x) assign(x, get(x), .GlobalEnv))
    
  }

run_variabelen()

```


```{r connectie met databank}

VIS2 <- connect_inbo_dbase("D0147_00_Vis2")
VIS <- connect_inbo_dbase("W0001_00_Vis")

```


```{r bevragen databank}

FactMeting_Pivot <- 
    tbl(VIS, "FactMeting_Pivot")
DimWaarneming <- 
    tbl(VIS, "DimWaarneming")
DimGebied <- 
    tbl(VIS, "DimGebied")
DimGebiedInfo <- 
    tbl(VIS, "DimGebiedInfo")
DimTaxon <- 
    tbl(VIS, "DimTaxon")
DimVisindexTaxon <- 
    tbl(VIS, "DimVisindexTaxon")
DimMethode <- 
    tbl(VIS, "DimMethode")
DimDate <- 
    tbl(VIS, "DimDate")

Vispunten <- 
    tbl(VIS2, "Vispunten")
VHAVispunten <- 
    tbl(VIS2, "VHAVispunten")
AbiotischeMeting <- 
    tbl(VIS2, "AbiotischeMeting")
  

tbl_data <-
  FactMeting_Pivot %>% 
  inner_join(DimWaarneming %>% 
               inner_join(DimGebied, 
                          by = "GebiedKey") %>% 
               inner_join(DimDate, by = c("BeginDatumKey" = "DateKey")),
             by = "WaarnemingKey") %>% 
  inner_join(DimTaxon %>% 
               left_join(DimVisindexTaxon %>% select(TaxonKey, Exoot)), 
             by = "TaxonKey") %>% 
  inner_join(DimMethode, by = "MethodeKey") %>% 
  select(MetingPivotKey, WaarnemingKey, WaarnemingID, GebiedKey, Gebiedcode, LambertX, LambertY, Lat, Long, Gebiednaam, Gemeentenaam, Begindatum, Month, Year, MethodeKey, Methodenaam, Methodegroepcode, AantalDagen, AantalFuiken, TaxonKey, Soort, Exoot, TAXONAANTAL, TAXONGEW, TAXONTOTGEW, TAXONLEN, TEMPERATUUR, ZUURSTOF, TURBIDITEIT, CONDUCTIVITEIT, PH) %>% 
  filter(Year %in% jaren,
         Gebiedcode %in% locatie_nrs,
         Methodenaam %in% vangstmethode)

gebied_codes <-
  tbl_data %>% 
  distinct(Gebiedcode) %>% 
  collect() %>% 
  pull()

waarneming_IDs <- 
  tbl_data %>% 
  distinct(WaarnemingID) %>% 
  collect() %>% 
  pull()

tbl_locatie_gegevens <- 
  Vispunten %>% 
  inner_join(VHAVispunten, by = c("VIP_ID" = "VHP_VIP_ID")) %>% 
  select(VIP_CDE, VIP_Omschrijving, VHP_LOTIC_NAAM, VHP_LOTIC_BekNaam, VHP_LOTIC_STROOMGEBIED, VHP_GEMEENTE) %>% 
  filter(VIP_CDE %in% gebied_codes)

tbl_abiotiek <- 
  AbiotischeMeting %>% 
  select(ABME_WRNG_ID, ABME_ZUURSTOF, ABME_ZUURSTOFPROCENT, ABME_TEMPERATUUR, ABME_PH, ABME_CONDUCTIVITEIT, ABME_TURBIDITEIT, ABME_SALINITEIT_PRM) %>% 
  filter(ABME_WRNG_ID %in% waarneming_IDs)

data <-
  tbl_data %>% 
  collect() %>% 
  left_join(tbl_locatie_gegevens %>% collect(), by = c("Gebiedcode" = "VIP_CDE")) %>% 
  left_join(tbl_abiotiek %>% collect(), by = c("WaarnemingID" = "ABME_WRNG_ID"))

```


```{r sluiten databank}

dbDisconnect(VIS)
dbDisconnect(VIS2)

```


```{r hervariabel, ref.label=c('pad', 'variabelen')}

rm(list = ls()[-which(ls() %in% c("data", "params", "run_pad", "run_variabelen"))])

run_pad()
run_variabelen()

```


```{r check dubbelgewicht}

```


```{r postprocessing data}

# data %>% 
#   distinct(Methodenaam)
# data %>% 
#   distinct(Gebiednaam)
# data %>% 
#   distinct(Year) %>% 
#   arrange(Year) %>% 
#   pull()
# 
# 
# gebieden <- 
#   data %>% 
#   distinct(Gebiedcode, LambertX, LambertY, Gebiednaam, Gemeentenaam)
# 

old_names <- 
  data %>% 
  distinct(Gebiedcode, Gebiednaam) %>% 
  arrange(Gebiedcode) %>% 
  pull(Gebiednaam)

(gebieden <- 
  data %>% 
  distinct(Gebiedcode, Gebiednaam, VHP_LOTIC_NAAM, round(LambertX), round(LambertY)) %>% 
  arrange(Gebiedcode) %>% 
  mutate(new_names = locatie_namen[order(locatie_nrs)]))

level_key <- locatie_namen[order(locatie_nrs)]
names(level_key) <- old_names


data_per_datum <- 
  data %>% 
  select(locatiecode = Gebiedcode, locatie = Gebiednaam, datum = Begindatum, 
         aantal_dagen = AantalDagen, aantal_fuiken = AantalFuiken, soort = Soort, 
         aantal = TAXONAANTAL, gewicht_ind = TAXONGEW, gewicht_tot = TAXONTOTGEW, 
         temperatuur = ABME_TEMPERATUUR, zuurstof = ABME_ZUURSTOF,	zuurstof_perc = ABME_ZUURSTOFPROCENT,	
         ph = ABME_PH,	turbiditeit = ABME_TURBIDITEIT,	conductiviteit = ABME_CONDUCTIVITEIT) %>% 
  mutate(locatie = recode(locatie, !!!level_key),
         fuikdagen = aantal_dagen * aantal_fuiken,
         datum = date(datum),
         jaar = year(datum),
         maand = month(datum)) %>% 
  group_by(locatiecode, locatie, datum, jaar, maand, aantal_dagen, aantal_fuiken, fuikdagen, soort) %>% 
  summarise(n = n(),
            aantal = sum(aantal, na.rm = FALSE),
            # gewicht = sum(if_else(is.na(gewicht_ind), 
            #                   if_else(is.na(gewicht_tot), NA_real_, gewicht_tot), 
            #                   if_else(is.na(gewicht_tot), gewicht_ind, gewicht_ind + gewicht_tot)),
            gewicht = sum(if_else(is.na(gewicht_ind), 
                                  gewicht_tot, gewicht_ind),
                          na.rm = FALSE),
            across(c(temperatuur, zuurstof,	zuurstof_perc, ph,	turbiditeit, conductiviteit), 
                   ~mean(., na.rm = TRUE)),
            .groups = "drop")

```


```{r controle gegevens}

# dubbel gewicht in ruwe data
dubbel_gewicht <-
  data %>% 
  filter(!is.na(TAXONGEW) & !is.na(TAXONTOTGEW))


# ontbrekende campagnes
campagnes <- 
  data_per_datum %>% 
  select(locatie, jaar, maand) %>% 
  distinct() %>% 
  mutate(seizoen = 
           case_when(
             maand %in% 3:5 ~ "voorjaar",
             maand %in% 6:8 ~ "zomer",
             maand %in% 9:11 ~ "najaar",
             maand %in% 12:1 ~ "winter"))

camp_tot <-
  campagnes %>% 
  expand(locatie, jaar, seizoen)
  
campagnes_ontbrekend <-
  camp_tot %>% 
  anti_join(campagnes)

write_xlsx(list(campagnes_ontbrekend = campagnes_ontbrekend),
           path = str_c(pad_data, "campagnes_ontbrekend.xlsx"))


campagnes_NA_or_0 <-
  data_per_datum %>% 
  group_by(locatiecode, locatie, datum, jaar, maand, aantal_dagen, aantal_fuiken) %>% 
  summarise(n = sum(n), aantal = sum(aantal, na.rm = TRUE), gewicht = sum(gewicht, na.rm = TRUE)) %>% 
  ungroup() %>% 
  arrange(datum, locatie) %>% 
  filter(if_any(.fns = ~is.na(.)) | 
           if_any(c(aantal_dagen, aantal_fuiken), ~near(., 0)))



# NA of 0 in aantal of gewicht

aantal_NA_of_0_ruw <-
  data %>% 
  filter(is.na(TAXONAANTAL) |
           near(TAXONAANTAL, 0)) %>% 
  select("MetingPivotKey", "WaarnemingKey", "WaarnemingID", "GebiedKey", "Gebiedcode", 
         "LambertX", "LambertY", "Gebiednaam", 
         "Begindatum", "Month", "Year", "MethodeKey", "Methodenaam", "Methodegroepcode", 
         "AantalDagen", "AantalFuiken", 
         "TaxonKey", "Soort", 
         "TAXONAANTAL", "TAXONGEW", "TAXONTOTGEW", "TAXONLEN")

gewicht_NA_of_0_ruw <-
  data %>% 
  filter(if_all(c(TAXONGEW, TAXONTOTGEW), ~is.na(.)) |
           if_all(c(TAXONGEW, TAXONTOTGEW), ~near(., 0))) %>% 
  select("MetingPivotKey", "WaarnemingKey", "WaarnemingID", "GebiedKey", "Gebiedcode", 
         "LambertX", "LambertY", "Gebiednaam", 
         "Begindatum", "Month", "Year", "MethodeKey", "Methodenaam", "Methodegroepcode", 
         "AantalDagen", "AantalFuiken", 
         "TaxonKey", "Soort", 
         "TAXONAANTAL", "TAXONGEW", "TAXONTOTGEW", "TAXONLEN")


uniek_aantal_of_gewicht <-
  data_per_datum %>% 
  select(locatiecode, locatie, datum, jaar, maand, aantal_dagen, aantal_fuiken, fuikdagen, soort, n, aantal, gewicht) %>% 
  arrange(datum, locatie) %>% 
  filter(if_any(c(aantal, gewicht), ~is.na(.)) |
           (if_any(c(aantal, gewicht), ~near(., 0)) & !if_all(c(aantal, gewicht), ~near(., 0))))


uniek_aantal_of_gewicht_vis <-
  uniek_aantal_of_gewicht %>% 
  filter(!str_detect(str_to_lower(soort), "garnaal|garnalen|gammarus|krab|kreeft|inktvis|octopus|zeekat"))

uniek_aantal_of_gewicht_inv <-
  uniek_aantal_of_gewicht %>% 
  filter(str_detect(str_to_lower(soort), "garnaal|garnalen|gammarus|krab|kreeft|inktvis|octopus|zeekat"))

# data_check <-
#   data %>%
#   filter(
#     Soort == "bot",
#     Gebiedcode == "85000225",
#     year(Begindatum) == 2016,
#     month(Begindatum) == 8)

write_xlsx(list(NA_aantal_of_gewicht = uniek_aantal_of_gewicht,
                NA_aantal = aantal_NA_of_0_ruw,
                NA_gewicht = gewicht_NA_of_0_ruw),
           path = str_c(pad_data, "NA_aantal_of_gewicht.xlsx"))



```


```{r sheets finale data}

campagnes <-
  data_per_datum %>% 
  select(locatie, datum, jaar, maand, aantal_dagen, aantal_fuiken, fuikdagen, 
         temperatuur, zuurstof,	zuurstof_perc, ph,	turbiditeit, conductiviteit) %>% 
  distinct() %>% 
  arrange(datum, locatie) %>% 
  mutate(ID_afvissing = 1:n()) %>% 
  select(ID_afvissing, everything()) %>% 
  arrange(ID_afvissing)

aantallen <-
  data_per_datum %>% 
  select(locatie, datum, soort, aantal) %>% 
  pivot_wider(names_from = soort,
              values_from = aantal,
              names_sort = TRUE,
              values_fill = 0) %>% 
  arrange(datum, locatie) %>% 
  mutate(ID_afvissing = 1:n()) %>% 
  select(ID_afvissing, everything(), -locatie, -datum) %>% 
  arrange(ID_afvissing)

gewicht <-
  data_per_datum %>% 
  select(locatie, datum, soort, gewicht) %>% 
  pivot_wider(names_from = soort,
              values_from = gewicht,
              names_sort = TRUE,
              values_fill = 0) %>% 
  arrange(datum, locatie) %>% 
  mutate(ID_afvissing = 1:n()) %>% 
  select(ID_afvissing, everything(), -locatie, -datum) %>% 
  arrange(ID_afvissing)

```


```{r wegschrijven finale data}

metadata <- 
  read_xlsx(str_c(pad_data, "metadata VLIZ/", metadata_name, ".xlsx"))

write_xlsx(list(locaties = locaties,
                campagnes = campagnes,
                aantallen = aantallen,
                gewicht = gewicht,
                metadata = metadata),
           path = str_c(pad_data, filename, "_", str_c(range(jaren), collapse = "_"), ".xlsx"))

```

