# Broedvogels 

Fichenummer: Fiche S-DS-V-006 -- Broedvogels (aangepaste versie 11/04/2013)

Fichenummer: Fiche S-DS-V-006 -- Broedvogels (aangepaste versie 11/04/2013)

**Wim Mertens**

## Inleiding

De eerstelijnsrapportage beschrijft de trends van de broedvogelsoorten waarvoor Instandhoudingsdoelstellingen gelden.

## Materiaal en methode

### Studiegebied

Het IHD-gebied (zoals beschreven in Adriaensen et al. (2005)) omvat

-   het Noordelijk gebied (Doelpolder Noord, Doelpolder Midden, Prosperpolder en Schor Ouden Doel, Paardenschor),

-   het Galgenschoor,

-   Ketenisse

-   Blokkersdijk en

-   Het Rest IHD-gebied.

Rest IHD-gebied is de NOP-zoneplus, het studiegebied van de Instandhoudingsdoelstellingen Schelde-estuarium (Adriaensen et al. 2005). Dit gebied omvat de vallei van de Zeeschelde en haar getijgebonden zijrivieren, inclusief de vallei van de Grote Nete tot in Zammel en van de Kleine Nete tot in Grobbendonk en alle buitendijkse gebieden.

Het Galgenschoor, Ketenisse en het Noordelijk gebied worden apart behandeld omdat hiervoor aparte doelstellingen zijn gedefinieerd (Adriaensen et al., 2005).

Het Groot Buitenschoor, het overstromingsgebied Kruibeke -- Bazel -- Rupelmonde, de Potpolder Lillo, het Molsbroek, de overige gebieden vzw Durme (reservaten Durmemeersen, Scheldebroeken (excl. Paardeweide en reservaatzone Donkmeer), de Kalkense Meersen en Wijmeers (KM en WM), de Paardeweide, de Bergenmeersen, het Aubroek en de Sint Onolfspolder, Schellebelle (omgeving station) en Zennegat zitten vervat in het 'Rest IHD-gebied'. Toch worden de gegevens van deze gebieden ook apart weergegeven omdat van deze gebieden (voor één of meerdere soorten) goede tijdsreeksen beschikbaar zijn.

In het werkblad "IHD-gebied_Totaal" worden de totalen berekend voor het IHD-gebied. Deze totalen zijn gebaseerd op de aantallen van bovenstaande deelgebieden (zie andere werkbladen), waarbij in geval van een vork steeds de hoogste waarden werd genomen. Aanwezigheid van NA's (soort niet geteld in dat gebied tijdens dat jaar) in één gebied leidt tot een NA in het totaal.

Rest AN-LO is het Vogelrichtlijngebied op de linkeroever van de Schelde, inclusief de compensatiegebieden (Achtergrondnota Natuur) en exclusief het Noordelijk gebied en Ketenisse. Deze data zijn in principe niet nodig voor de evaluatie of de beschrijving van de T0 aangezien de IHD-Z geen betrekking hebben op dit gebied (er worden aparte doelstellingen voor dit gebied geformuleerd in de Achtergrondnota Natuur). Ze kunnen wel bijkomende informatie geven over de feitelijke populatiegrootte van sommige soorten.

Het Fort St- Marie en het gebied tussen de Vlakte van Zwijndrecht en Blokkersdijk is mee opgenomen in 'Rest IHD-gebied'.

AN_RO_Inclusief Kuifeend omvat het Vogelrichtlijngebied de Kuifeend en de omliggende gebieden (Plas voormalige Hoge Maey, de Verlegde Schijns, het Oud Schijn, de Grote Kreek en Stadsgracht), de Meeuwenbroedplaats en het Opstalvalleigebied. Ook deze aantallen zijn niet strikt noodzakelijk voor de evaluatie omdat de Achtergrondnota Natuur voor dit gebied aparta instandhoudingsdoelstellingen vastlegt.

De overige gebieden in de haven op de rechteroever van de Schelde zijn opgenomen in Rest IHD-gebied (Fort St-Filip, Potpolder Lillo ...).

### Dataverzameling

De aantallen zijn gecompileerd uit de volgende bronnen:

Anselin et al. (1998); Vermeersch et al. (2004); Vermeersch et al. (2006); Vermeersch & Anselin (2009); Anselin (2010);Spanoghe et al. (2003); Gyselings et al. (2004); Spanoghe et al. (2006); Gyselings et al. (2007); Spanoghe et al. (2008); Gyselings et al. (2009); Spanoghe et al. (2010); (Gyselings et al., 2010); Gyselings et al. (2013); Weyn et al. (2013); Daniëls et al. (2013).

Daarnaast werd gebruik gemaakt van de Broedvogeldatabank van het INBO (http://broedvogels.inbo.be) en de Broedvogelatlasdatabank en --kaartlagen van het INBO. Voor de periode 2010-2017 werden deze gegevens aangevuld met gegevens uit Waarnemingen.be, de website voor natuurinformatie van Natuurpunt en Stichting Natuurinformatie, ter beschikking gesteld door Natuurpunt Studie vzw.

De data vóór 2000 zijn afkomstig uit BBV-verslagen 1995-1996 en 1994-2005 (Anselin et al. 1998) en (Vermeersch et al. 2006) en de Broedvogeldatabank.

De gegevens van de periode 2000-2002 zijn afkomstig van de Broedvoegelatlas (Vermeersch et al. 2004) en de digitale voorbereidende bestanden. Voor enkele zeldzame soorten zijn per jaar de aantallen gekend. Voor algemenere soorten slaan de aantallen op de hele periode 2000-2002. In de tabel werden ze ingevuld bij 2001.

De gegevens van de periode 2003-2005 zijn afkomstig uit het BBV-verslag 1994-2005 (Vermeersch et al. 2006) en de Broedvogeldatabank.

De gegevens van de periode 2006-2007 zijn afkomstig uit het BBV-verslag 2006-2007 (Vermeersch and Anselin 2009) en de Broedvogeldatabank.

De gegevens voor de periode 2008-2009 zijn afkomstig uit (Anselin 2010) en de Broedvogeldatabank.

Voor de deelgebieden Noordelijk gebied, Ketenisse, Rest AN-LO zijn de aantallen vanaf 2003 afgeleid uit de monitoringsrapporten van het Linkerscheldeoevergebied (Spanoghe et al., 2003, 2006, 2008, 2010 en Gyselings et al. 2004, 2007, 2009) en recentere monitoringsgegevens van het INBO-project "Monitoring en evaluatie van het Linkerscheldeoevergebied (LO)".

De aantallen voor Blokkersdijk zijn afkomstig van de [[website van Natuurpunt-Waasland]{.ul}](http://www.natuurpuntwaasland.be/index.php/fauna-blokkersdijk) en het [[tweede monitoringsrapport]{.ul}](http://www.natuurpuntwaasland.be/images/PDF/BD-171111-Tweede_-Monitoringrapport.pdf) (De Jonghe & Verschueren, 2017) en data aangeleverd door Willy Verschueren (2018, 2019).

Voor Kuifeend en omgeving zijn de gegevens vanaf 2009 en voor sommige soorten vanaf 2004 afkomstig uit het monitoringsrapport RO (Gyselings et al. 2014) en recentere monitoringsgegevens van het EVINBO-project "Monitoring en evaluatie van het Rechterscheldeoevergebied (RO)". De aantallen voor de jaren 2009 tot en met 2017 zijn voor enkele soorten aangepast op basis van de meest recente rapportage.

Voor het overstromingsgebied Kruibeke -- Bazel -- Rupelmonde zijn de gegevens afkomstig van de jaarverslagen van de Beheercommissie Kruibeke-Bazel-Rupelmonde (Anoniem, 2014) en recentere monitoringsgegevens van het INBO-project ""Opvolgen en adviseren beheercommissie Kruibeke-Bazel-Rupelmonder (KBR)".

Gegevens van Molsbroek en de overige gebieden van de vzw Durme zijn afkomstig van de Vogelwerkgroep Durmevallei.

Gegevens van Kalkense Meersen, Wijmeers, Paardeweide, Bergenmeersen en Zennegat na 2008 werden verzameld in het kader van het INBO/ANB-project "Wetenschappelijke opvolging van de natuurontwikkeling in de gebieden van het geactualiseerde Sigmaplan".

Gegevens over het aantal gruttoterritoria Kalkense Meersen en omgeving in de periode 2001-2009 zijn afkomstig uit Schepers (2010). Gegevens over het aantal gruttoterritoria in Aubroek, Sint Onolfspolder en Schellebelle (omgeving station) na 2010 zijn afkomstig van de projectverslagen Weidevogelbescherming in het Regionaal Landschap Schelde-Durme (2013 en 2014) en van data aangeleverd door Robbert Schepers.

De gegevens van het Groot Buitenschoor (2012) zijn ongepubliceerde gegevens verzameld in het kader van een INBO-ANB monitoringproject Antwerpen RO.

Voor de soorten baardman, bruine kiekendief, grote karekiet, kluut, snor, tureluur, woudaap en zomertaling werden de aantallen uit bovenstaande bronnen aangevuld op basis van waarnemingen uit waarnemingen.be geïnterpreteerd volgens de criteria uit Van Dijk en Boele (2011).

Nullen werden enkel ingevuld als:

-   er een intensieve monitoring werd uitgevoerd en geen territoria of broedgevallen zijn vastgesteld in een bepaald gebied

-   er voor een bepaald jaar voor een gebied aantallen in de databank zaten voor andere soorten

-   het op basis van de gekende Vlaamse populaties uiterst onwaarschijnlijk is dat een bepaalde soort zou hebben gebroed.

In andere gevallen, waar geen zekerheid bestaat over aan- of afwezigheid, werd niets ingevuld.

De aantallen voor de gebieden Groot Buitenschoor, overstromingsgebied Kruibeke -- Bazel -- Rupelmonde, Potpolder Lillo, Molsbroek, Overige gebieden vzw Durme (reservaten Durmemeersen, Scheldebroeken (excl. Paardeweide en reservaatzone Donkmeer), Kalkense Meersen en Wijmeers (KM en WM), Paardeweide, Bergenmeersen, Aubroek en Sint Onolfspolder en Schellebelle (omgeving station) worden in aparte werkbladen gegeven maar zitten vervat in de totalen van de categorie Rest_IHD-gebied (indien aanwezig).

In het werkblad Rest_IHD-gebied worden enkel aantallen gegeven indien verwacht mag worden dat ze een redelijke schatting zijn van het totaal aantal territoria in het gebied.

## Exploratieve data-analyse broedvogels

Voor sommige soorten werden redelijk volledige tijdsreeksen verkregen voor alle deelgebieden. Dit zijn voornamelijk de zeldzame, goed te inventariseren soorten van het Bijzondere Broedvogelproject (baardman, bruine kiekendief, grote karekiet, lepelaar, porseleinhoen, roerdomp, snor) of soorten die niet of amper broeden in Vlaanderen (purperreiger, kwak, kwartelkoning, paapje).

Voor een aantal soorten is de tijdsreeks voor Rest IHD-gebied en Galgeschoor beperkt tot de atlasperiode 2000-2002. Het gaat over minder zeldzame soorten die niet opgenomen zijn in het Bijzondere Broedvogelproject (blauwborst, dodaars, rietzanger, scholekster, slobeend). De beschikbare data is aangeleverd maar wordt in deze rapportage niet verder besproken.

Voor zomertaling werden de gegevens na 2007 aangevuld op basis van waarnemingen.be. De gegeven aantallen kunnen als minima geïnterpreteerd worden maar geven na 2007 waarschijnlijk toch een redelijk accuraat beeld van de reële aantallen.

Voor kluut en tureluur kan aangenomen worden dat de gegeven aantallen voor Rest IHD-gebied na de atlasperiode tamelijk nauwkeurig zijn omdat deze soorten amper of slechts in (zeer) lage aantallen broeden buiten de recent aangelegd en frequent gemonitorde natuurgebieden van het Sigmaplan. Ook de aantallen grutto in het 'Rest IHD-gebied' zijn betrouwbaar omdat telkens de volledige populatie in en rond de Kalkense Meersen geteld werd. Elders in het 'Rest_IHD-gebied' komt/kwam de soort niet of slechts in zeer lage aantallen tot broeden.

Verscheidene soorten komen tot 2017 nog maar zelden tot broeden binnen IHD gebied Schelde-estuarium (grote karekiet, kwak, kwartelkoning, lepelaar, roerdomp en paapje) of werden nog nooit vastgesteld als broedvogel (purperreiger). Van deze soorten zijn geen trends bespreekbaar.

Figuur \@ref(fig:Figuur11-1) toont de data met uitzondering van de vijf algemenere soorten (blauwborst, dodaars, rietzanger, scholekster, slobeend) en één tot nog toe afwezige soort (puperreiger). Deze figuur toont de trends van de soorten binnen de gebieden met Instandhoudingsdoelstellingen in het Schelde-estuarium. Hoewel geen gebiedsdekkende kartering mogelijk is wordt aangenomen dat het aantal broedkoppels per soort een redelijk accuraat beeld van de reële aantallen weergeeft.

![(#fig:Figuur11-1) Evoluties in de broedvogelaantallen voor een selectie van soorten waarvoor de data-inzameling representatief is binnen IHD-gebied met tot doel gestelde aantallen in Adriaensen et al. (2005) (rode lijn) (data van Noordelijke gebied, Ketenisse, Galgeschoor, Blokkersdijk, Rest-IHD-gebied, voor bruine kiekendief werd het aantal territoria in Rest-IHD-gebied en Galgeschoor in jaren zonder data gelijkgesteld aan 1, wat overeenkomt met het minimum voor en na). Loess-smoother weergegeven](090_vissen\templates\figuren_geintegreerd-rapport\media\image1.png){width="5.905511811023622in" height="7.3818908573928255in"}

Van de jaarlijks broedende soorten komt een aanzienlijk deel van de populatie van grutto, snor, woudaap en zomertaling voor buiten de haven. Voor de andere jaarlijks broedende soorten is het Noordelijk gebied van het Antwerpse havengebied op linkeroever veruit het belangrijkst. Baardman, grutto, kluut en snor vertonen de laatste decennia een stijgende trend in de vallei van de Zeeschelde en haar getijgebonden zijrivieren (NOP-zone). Het aantal territoria baardman schommelt tien jaar sterk (tussen 15 in 2013 en 37 in 2016), maar vertoont wel een stijgende trend. De laatste tien jaar zijn de aantallen grutto eerder stabiel (60 territoria), alhoewel de aantallen in 2018 en 2019 wat gedaald zijn. De hoogste aantallen kluut in de periode tussen 2015 en 2017 (bijna 200 territoria), sindsdien zijn de aantallen is het Noordelijk gebied van het Antwerpse havengebied op linkeroever sterk gedaald. Snor komt in kleine (4-8), maar duidelijk stijgende, aantallen voor met een maximum van 8 territoria in 2016 en 2019. De aantallen zomertalingen stijgen na 2007 wat te verklaren is door de stapsgewijze inrichting van (estuariene) gebieden van het Sigmaplan. In de eerste jaren na inrichting van overstromingsgebieden met gecontroleerd gereduceerd getij en ontpolderingen verschijnen zomertalingen. Waarschijnlijk zullen de aantallen hier terug afnemen tengevolge van de te verwachten vegetatiesuccessie. Om de doelstellingen voor deze soort duurzaam te realiseren zal moeten gerekend worden op niet-estuariene wetlands van het Sigmaplan, zoals de niet tidale aantakking in Paardeweide, waar de soort ook reeds het eerste jaar na inrichting verscheen. De tureluurpopulatie kende tussen 2005 en 2010-2012 een toename, maar gaat de laatste vijf jaar achteruit tot een 30-tal territoria de laatste jaren. De achteruitgang van bruine kiekendief in het havengebied is vooralsnog niet gestopt. Voor woudaap was 2017 een slecht jaar met slechts twee territoria (tegen 8 in 2016), maar in 2018 waren er terug 4 en in 2019 5 territoria. Het aantal territoria van porseleinhoen kent een erratisch verloop dat sterk afhangt van de weersomstandigheden in het voorjaar. De overige soorten (grote karekiet, kwak, kwartelkoning, lepelaar, paapje en roerdomp) zijn niet elk jaar aanwezig en er worden jaarlijks maximaal 1 of 2 territoria vastgesteld.

Op Figuur \@ref(fig:Figuur11-1) valt op dat de aantallen voor de meeste soorten ver verwijderd zijn van de instandhoudingsdoelstelling (Adriaensen et al. 2005). Enkel zomertaling en grutto en in mindere mate baardman en kluut benaderen de tot doel gestelde aantallen.

Figuur \@ref(fig:Figuur11-2) toont de evolutie van zes algemene soorten weergegeven in gebieden die frequent worden geteld. Het Noordelijk gebied in de haven van Antwerpen (Sigma_LO op Figuur \@ref(fig:Figuur11-2)), Blokkersdijk en Ketenisse worden jaarlijks integraal onderzocht op broedvogels. In de Sigmagebieden werd één telling uitgevoerd voorafgaand aan de inrichting (T0) en één tot drie na de inrichting. Het betreft volgende gebieden:

-   Kalkense Meersen: geleidelijke verwerving van gronden sinds 2008 waarna omzetting tot grasland en/of een verschralingsbeheer wordt opgestart.

-   Bergenmeersen: GGG sinds april 2013

-   Wijmeers: deels ontpolderd en deels ingericht als niet-estuarien wetland sinds november 2015

-   Paardeweide: oostzijde ingericht als rietatol sinds 2014

-   Weijmeerbroek: verschralingsbeheer sinds 2010, beperkte vernatting sinds 2016

-   Polders van Kruibeke: geleidelijke inrichting sinds 2008, GGG Bazel-noord sinds 2015

-   Zennegat: inrichting afgerond in 2017

Om volledige tijdsreeksen te bekomen voor de Sigmagebieden werd een extrapolatie van de data doorgevoerd. De jaren voorafgaand aan de inrichting kregen de aantallen van de nulmeting (T0) toegekend, na de inrichting werden gaten opgevuld d.m.v. een lineair verband (afronding naar boven).

Voor vijf van de zes soorten (blauwborst, dodaars, rietzanger, slobeend en zomertaling) neemt het belang van de regelmatig getelde Sigmagebieden toe naarmate meer gebieden ingericht worden. Voor vier van de zes soorten vullen deze gebieden sinds 2017 reeds een groot deel van de instandhoudingsdoelstelling van het gehele Schelde-estuarium in: meer dan 50% voor blauwborst (IHD = 550 territoria), meer dan 75% voor dodaars (IHD = 50), meer dan 100% voor rietzanger (IHD = 170) en 50% voor zomertaling (IHD = 20). Voor slobeend (IHD = 150) en scholekster (IHD = 190) ligt dit aandeel lager, respectievelijk 27,3% en 7%.

![(#fig:Figuur11-2) Evoluties in de broedvogelaantallen (territoria) voor een selectie van algemenere soorten voor een beperkt aantal gebieden die frequent worden geteld (BD (Blokkersdijk), ,K (Ketenisse), Sigma (Kalkense Meersen, Wijmeers, Bergenmeersen, Paardeweide, Weijmeerbroek en Polder van Kruibeke) , Sigma_LO (= Noordelijke gebied = Doelpolder + Prosperpolder + Paardenschor + Schor Ouden Doel)).](090_vissen\templates\figuren_geintegreerd-rapport\media\image2.png){width="5.906110017497813in" height="7.3826367016622925in"}

## Referenties

Adriaensen F., Van Damme S., Van den Bergh E., Van Hove D., Brys R., Cox T., Jacobs S., Konings P., Maes J., Maris T. et al. (2005). Instandhoudingsdoelstellingen Schelde-estuarium. Antwerpen: Antwerpen U. 05-R82. 249 p.

Anoniem (2014). Jaarverslag 2013. Beheercommissie Natuur Kruibeke -- Bazel -- Rupelmonde, Gent.

Anselin A. (2010). Enkele resultaten van het project Bijzondere Broedvogels voor 2008 en 2009. Vogelnieuws : ornithologische nieuwsbrief van het Instituut voor Natuur- en Bosonderzoek 14(Brussel).

Anselin A., Devos K., Kuijken E. (1998). Kolonievogels en zeldzame broedvogels in Vlaanderen in 1995 en 1996 = colonial and rare breeding birds in flanders (belgium) in 1995 and 1996.

Daniëls F., Deduytsche B., Dillen A., Maes T., Maris T., Nachtergale L., Nollet S., Spanoghe G., Vanden Abeele L., Van den Bergh E. et al. (2013). Jaarverslag 2012 Beheercommissie Kruibeke-Bazel-Rupelmonde. Gent: Beheercommissie Kruibeke-Bazel-Rupelmonde.

De Jonghe G., Verschueren W. (2017). Blokkersdijk E-131 (Antwerpen Linkeroever). Tweede monitoringrapport. Antwerpen: Natuurpunt Waasland vzw Kern Antwerpen Linkeroever.

Gyselings R., Spanoghe G., Hessel K., Mertens W., Vandevoorde B., Van den Bergh E. (2009). Monitoring van het Linkerscheldeoevergebied in uitvoering van de resolutie van het Vlaams Parlement van 20 februari 2002: resultaten van het zesde jaar : bijlage 9.8 bij het zesde jaarverslag van de Beheercommissie Natuur Linkerscheldeoever. Brussel. 2009.3.

Gyselings R., Spanoghe G., Van den Bergh E. (2004). Monitoring van het linkerscheldeoevergebied in uitvoering van de resolutie van het Vlaams Parlement van 20 februari 2002: resultaten van het tweede jaar. Brussel. 2004.19.

Gyselings R., Spanoghe G., Van den Bergh E. (2007). Monitoring van het Linkerscheldeoevergebied in uitvoering van de resolutie van het Vlaams Parlement van 20 februari 2002: resultaten van het vierde jaar : bijlage 9.10 van het vierde jaarverslag van de Beheercommissie natuurcompensaties Linkerscheldeoevergebied. Brussel. 2007.2.

Gyselings R., Spanoghe G., Van den Bergh E., Verbelen D., Benoy B., Vogels B., Willems W. (2011). Monitoring natuur havengebied en omgeving Antwerpen Rechteroever. Brussel. 2010.15.

Gyselings R., Spanoghe G., Van den Bergh E., Verbelen D., Benoy L., Vogels B., Lefevre A. (2013). Monitoring natuur havengebied en omgeving Antwerpen Rechteroever, resultaten van het monitoringsjaar 2012. Brussel: Instituut voor Natuur- en Bosonderzoek.

Mertens W., Hessel K., Spanoghe G., Van Lierop F. (in prep.). T0-rapportage van de monitoring van de 2010-gebieden van het geactualiseerde Sigmaplan. Broedvogels. Brussel: Instituut voor Natuur- en Bosonderzoek.

Gyselings R., Spanoghe G., Van den Bergh E., Verbelen D., Benoy L., Lefevre, A., Willems W. (2014). Monitoring natuur havengebied en omgeving Antwerpen Rechteroever -- Resultaten 2013. Brussel. 2014.6392398.

Schepers R. (2010). De Grutto (*Limosa limosa*) in de Kalkense Meersen. Historiek, broedsucces en toekomstperspectieven. Gent: Universiteit Gent. 63 p.

Spanoghe G., Gyselings R., Van den Bergh E. (2003). Monitoring van het Linkerscheldeoevergebied in uitvoering van de resolutie van het Vlaams Parlement van 20 februari 2002: resultaten van het eerste jaar. Brussel. 2003.15.

Spanoghe G., Gyselings R., Van den Bergh E. (2006). Monitoring van het Linkerscheldeoevergebied in uitvoering van de resolutie van het Vlaams Parlement van 20 februari 2002: resultaten van het derde jaar. Brussel. 2006.1.

Spanoghe G., Gyselings R., Van den Bergh E. (2008). Monitoring van het Linkerscheldeoevergebied in uitvoering van de resolutie van het Vlaams Parlement van 20 februari 2002: resultaten van het vijfde jaar : bijlage 9.10 bij het vijfde jaarverslag van de Beheercommissie Natuurcompensatie Linkerscheldeoevergebied. Brussel. 2008.14.

Spanoghe G., Gyselings R., Vandevoorde B., Van den Bergh E., Hessel K., Mertens W. (2010). Monitoring van het Linkerscheldeoevergebied in uitvoering van de resolutie van het Vlaams Parlement van 20 februari 2002: resultaten van het zevende jaar : bijlage 9.8 bij het zevende jaarverslag van de Beheercommissie Natuur Linkerscheldeoever. Brussel. 2010.8.

Van Dijk A.J., Boele A. (2011). Handleiding SOVON Broedvogelonderzoek. Nijmegen, Nederland: SOVON Vogelonderzoek.

Vermeersch G., Anselin A. (2009). Broedvogels in Vlaanderen in 2006-2007. Recente status en trends van Bijzondere Broedvogels en soorten van de Vlaamse Rode Lijst en/of Bijlage I van de Europese Vogelrichtlijn. Brussels, Belgium. 2009(3).

Vermeersch G., Anselin A., Devos K. (2006). Bijzondere broedvogels in Vlaanderen in de periode 1994-2005 : populatietrends en recente status van zeldzame, kolonievormende en exotische broedvogels in Vlaanderen. Brussels, Belgium. 2006(2). 1-64 p.

Vermeersch G., Anselin A., Devos K., Herremans M., Stevens J., Gabriëls J., Van Der Krieken B. (2004). Atlas van de Vlaamse broedvogels : 2000-2002.

Weyn K., Gyselings R., Spanoghe G. (2013). Jaarverslag 2012 Beheercommissie Natuur Linkerscheldeoever. Kallo: Beheercommissie Natuur Linkerscheldeoever.

