# Hogere planten 

Fichenummers: S-DS-V-001 -- Hogere planten; P-DS-V-001a - Hogere planten)

**Bart Vandevoorde & Frederik Van Lierop**

## Inleiding

Op de schorren van het Zeeschelde-estuarium wordt de diversiteit aan hogere planten opgevolgd door middel van vegetatieopnames. Deze worden gemaakt van de bestaande permanente kwadraten (PQ) en aangevuld met losse vegetatieopnames welke stratified random worden gelokaliseerd in functie van de huidige vegetatietypes of doelvegetatietypes (Leyssen *et al*., 2006; Meire & Maris, 2008).

## Materiaal en methode

Vegetatieopnames worden gemaakt volgens de principes van de Frans-Zwitserse school (Schaminée *et al*., 1995). Dit houdt in dat de vegetatie in een proefvlak homogeen moet zijn en dat ze een representatieve weergave moet zijn van de aanwezige vegetatie. Het proefvlak moet met andere woorden groot genoeg zijn om de floristische samenstelling van de vegetatie weer te geven (i.e. minimumareaal).

Bij het installeren van de permanente kwadraten is rekening gehouden met de twee voorwaarden (homogeniteit, minimumareaal) in functie van het toen aanwezige vegetatietype. Maar na verloop van tijd kan het evenwel gebeuren dat de vegetatie in het permanent kwadraat niet langer homogeen is. Een PQ, oorspronkelijk gelegd in een homogene ruigte, kan bijvoorbeeld ingegroeid geraken door een struweel, waardoor het voor een deel uit ruigte bestaat en het andere deel uit struweel. Dit is eigen aan permanente kwadraten en hoeft geen probleem te zijn. De vegetatieopnames die gemaakt zijn van permanente kwadraten, kunnen dus uit heterogene vegetaties bestaan.

Bovendien wordt volgens de principes van de Frans-Zwitserse school de vegetatie in zijn geheel beschouwd. Dit wil zeggen dat bij het maken van een vegetatieopname alle plantensoorten, mossen, lichenen en (macro)algen verdeeld over de verschillende lagen (boomlaag, struiklaag, kruidlaag, moslaag, algenlaag) in rekening worden gebracht. De planten moeten wel rechtstreeks in contact staan met de bodem; epifyten worden bijvoorbeeld niet meegeteld.

In functie van het (initiële) vegetatietype varieert de oppervlakte van de permanente kwadraten. De grootte van een permanent kwadraat is zodanig gekozen dat het representatieve weergave is van de aanwezige vegetatie (i.e. minimumareaal). In bossen en struwelen zijn bijvoorbeeld grotere proefvlakken afgebakend in vergelijking met andere vegetatietypes als biezen- en pioniervegetaties. Bij het maken van een vegetatieopname van het permanent kwadraat wordt de initiële grootte van het proefvlak gerespecteerd, onafhankelijk van de vegetatie die er zich heeft ontwikkeld. Bij vergelijking van vegetatieopnames van PQ's met verschillende grootte wordt hier best rekening mee gehouden door te standaardiseren per oppervlakte-eenheid.

Kaderend binnen de systeemmonitoring werd tot 2013 3-jaarlijks een vegetatieopname gemaakt van de permanente kwadraten. Deze meetfrequentie is evenwel gewijzigd naar 6-jaarlijks. De laatste opnamesessie dateert van 2019. De vegetatieopnames die toen gemaakt zijn van de permanente kwadraten, zijn gepubliceerd in Van Ryckegem *et al*. (2020).

Tot 2013 werden de natuurontwikkelingsgebieden (Paardeschor, Ketenisseschor, Paddebeek en Heusden) jaarlijks bemeten maar vanaf 2013 is deze meetfrequentie aangepast naar 3-jaarlijks. De proefvlakken of permanente kwadraten, waarvan vegetatieopnames worden gemaakt, zijn gelegen langs transecten die loodrecht op de rivieras gesitueerd zijn. In 2019 zijn de laatste keer vegetatieopnames gemaakt van deze PQ's welke gepubliceerd zijn in Van Ryckegem *et al*. (2020).

De laatste jaren zijn nieuwe permanente kwadraten geïnstalleerd ter opvolging en evaluatie van recent aangelegde natuurontwikkelingsgebieden zoals de Potpolder Lillo en Fort Filips. De resultaten hiervan zullen gepubliceerd worden in volgende rapportages.

Een 30-tal PQ's van de systeemmonitoring worden ook aangewend ter evaluatie van het habitattype 91E0_sf Zachthoutooibos (wilgenvloedbos, *Salicetum albae*). Om dit habitattype betrouwbaar te evalueren zijn echter 77 PQ's nodig. Negen hiervan liggen langs de Maas, de resterende 38 PQ's zijn afgebakend langs het Schelde-estuarium (Westra *et al*., 2014). De plots worden bemonsterd met een retourperiode van 6 jaar. Jaarlijks wordt een vegetatieopname gemaakt van een zesde van de plots. De resultaten hiervan zullen ook gepubliceerd worden in volgende rapportages.

## Referenties

Meire P. & Maris T. (2008). MONEOS: Geïntegreerde monitoring van het Schelde‐estuarium.

Leyssen A., Denys L., Schneiders A., Van Looy K., Packet J. & Vanhecke L. (2006). Afstemmen van referentiecondities en evaluatiesystemen voor de biologische kwaliteitselementen macrofyten en fytobenthos en uitwerken van een meetstrategie in functie van de Kaderrichtlijn Water. Rapport van het Instituut voor Natuurbehoud IN.R.2006.09 in opdracht van VMM, Brussel.

Schaminée J.H.J., Stortelder A.H.F. & Westhoff V. (1995). De vegetatie van Nederland. Deel 1 Inleiding tot de plantensociologie: grondslagen, methoden en toepassingen. Opulus Press, Uppsala, Leiden, 296 p.

Van Ryckegem G., Van Braeckel A., Elsen R., Vanoverbeke J., Van de Meutter F., Vandevoorde B., Mertens W., Breine J., Speybroeck J., Bezdenjesnji O., Buerms D., De Beukelaer J., De Regge N., Hessel K., Soors J. & Van Lierop F. (2020). MONEOS -- Datarapport INBO: toestand Zeeschelde 2018-2019. Monitoringsoverzicht en 1ste lijnsrapport Geomorfologie, diversiteit Habitats en diversiteit Soorten. Rapporten van het Instituut voor Natuur- en Bosonderzoek 2020 (38). Instituut voor Natuur- en Bosonderzoek, Brussel.

Westra T., Oosterlynck P., Van Calster H., Paelinckx D., Denys L., Leyssen A., Packet J., Onkelinx T., Louette G., Waterinckx M. & Quataert P. (2014). Monitoring Natura 2000 - habitats: meetnet habitatkwaliteit. Rapporten van het Instituut voor Natuur- en Bosonderzoek 2014 (1414229). Instituut voor Natuur- en Bosonderzoek, Brussel.

