--- 
title: "MONEOS - Geïntegreerd datarapport INBO: Toestand Zeeschelde 2021"
subtitle: "Monitoringsoverzicht en 1ste lijnsrapportage Geomorfologie, diversiteit Habitats en diversiteit Soorten"
author: 
  - firstname: Gunther
    name: Van Ryckegem
    email: gunther.vanryckegem@inbo.be 
  - firstname: Joost
    name: Vanoverbeke
    email: joost.vanoverbeke@inbo.be
  - 
    name: Frank Van de Meutter
  - 
    name: Bart Vandevoorde
  - 
    name: Wim Mertens
  - 
    name: Amber Mertens
  - 
    name: Alexander Van Braeckel
  - 
    name: Vincent Smeekens
  - 
    name: Koen Thibau
  - 
    name: Olja Bezdenjesnji
  - 
    name: Dimitri Buerms
  - 
    name: Nico De Regge
  - 
    name: Kenny Hessel
  - 
    name: Charles Lefranc
  - 
    name: Jan Soors
  - 
    name: Frederik Van Lierop
shortauthor: 
  - Van Ryckegem, G., Vanoverbeke, J., Van de Meutter, F., Vandevoorde, B., Mertens, W., Mertens, A., Van Braeckel, A., Smeekens, V., Thibau, K., Bezdenjesnji, O., Buerms, D., De Regge, N., Hessel, K., Lefranc, C., Soors, J., Van Lierop, F.
corresponding: gunther.vanryckegem@inbo.be
reviewer: Erika Van den Bergh
year: "`r Sys.getenv('jaar_moneos')`"
cover_photo: "IMG-20220930-WA0010_snede.jpg"
cover_description: "Benthosstaalname op het Groot Schoor van Hamme (nieuwe ontpoldering) eind september 2022 (foto door Dimitri Buerms)."
# cover: cover.pdf # link naar pdf met cover
doi: "10.21436/inbor.85928183"
reportnr: "Rapporten van het Instituut voor Natuur- en Bosonderzoek 2022 (26)"
depotnr: "D/2022/3241/290"
embargo: ""

style: INBO
lang: nl
tocdepth: 2
lof: FALSE
lot: FALSE
floatbarrier: subsection

site: bookdown::bookdown_site

output:
  INBOmd::gitbook: default
  INBOmd::pdf_report: default
  INBOmd::ebook: default
  bookdown::dont_run: default
---


# Dankwoord/Voorwoord {-}

Het INBO monitoringsprogramma wordt uitgevoerd met de financiële steun van de Vlaamse Waterweg nv, Maritieme Toegang (MT) en het Agentschap voor Natuur en Bos (ANB).
Waarvoor dank.
De monitoring zou niet mogelijk geweest zijn zonder de bemanning van de schepen SCALDIS I, Scheldewacht II, Veremans, Henry de Vos en de Parel.
Dank aan Erwin De Backer (Waterbouwkundig laboratorium) voor de uitstekende planning van de bootcampagnes.
Dank aan iedereen die in het bijzondere corona-jaar meehielp blijvend te sleutelen aan afspraken zodat de monitoring praktisch uitvoerbaar bleef onder voordurend veranderende COVID regels.
Dank!
Door jullie inzet kon het monitoringsprogramma bijna volledig uitgevoerd worden.

De zoogdierengegevens werden met toestemming ontleend uit de databank van Waarnemingen.be (Natuurpunt VZW).

De superdeluxe dataverzameling en het laboratoriumwerk voor watervogels, hyperbenthos, macrozoöbenthos en de hoogteraaien werden uitgevoerd door Olja Bezdenjesnji, Dimitri Buerms, Joram De Beukelaer, Nico De Regge, Kenny Hessel, Charles Lefranc, Vincent Smeekens, Jan Soors en Frederic Van Lierop.
Topteam Estuaria!
De vismonitoring werd uitgevoerd door team MHAF-INBO (Monitoring Herstel Aquatische Fauna).
De onderzoekers en onderzoeksmedewerkers leverden opnieuw prachtig werk: Olja Bezdenjesnji, Jan Breine, Adinda De Bruyn, Linde Galle, Isabel Lambeens, Yves Maes, Thomas Terrie, Gerlinde Van Thuyne en Jeroen Van Wichelen, met de ondersteuning van technici en arbeiders hieronder vermeld.
Voor de ankerkuilvisserij konden we rekenen op Job Bout, Sjaak Bout en Davy Govers.
Dankzij hun professionele vaardigheid zijn de campagnes in 2021 vlot verlopen en kon ons onderzoek in de beste omstandigheden worden uitgevoerd, dank u wel.
Het INBO-team Linkebeek, dat alle gevangen vissen uitzoekt, meet en weegt, blijft enthousiast ondanks de lange dagen aan boord van 'De Harder'.
Dank voor jullie geestdrift en hun hulp aan boord.
Mevrouw Cabradilla (de Vlaamse Waterweg nv) verleent ons altijd vlot de nodige aanmeertoelatingen, hartelijk dank.
Fuikvisserij is een harde job, ploeteren en sleuren in het slik bij weer en wind.
Dank u wel collega's Franky Dens, Marc Dewit en Pieter Piron, jullie waren niet alleen een hulp op het terrein maar ook voor- en nadien zorgden jullie dat het nodige materiaal altijd klaar was om te gebruiken.
2021 was ook het laatste jaar dat we konden steunen op de medewerking van Jan Breine.
We missen je enorm op het INBO!
Geniet van je pensioen!

We zijn de mensen van 'Zates' in Branst dankbaar voor hun gastvrijheid en voor het doorgeven van bijzondere waarnemingen in het Zeeschelde-estuarium.

We zijn ook de mensen van BMK en in het bijzonder Els Lommelen zeer erkentelijk en dankbaar voor de technische ondersteuning en begeleiding bij het uitwerken van de rapportering via rmarkdown, bookdown en github.


```{r setup, include = FALSE}
library(knitr)
opts_knit$set(eval.after = "fig.cap")
opts_chunk$set(
  echo = TRUE, 
  eval = TRUE,
  cache = FALSE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  warning = TRUE,
  error = TRUE,
  message = TRUE
)
library(tidyverse)
library(INBOtheme) # remotes::install_github("inbo/INBOtheme")
if (interactive()) {
  theme_set(
    theme_inbo(
      base_family = "FlandersArtSans-Regular",
      base_size = 10
    )
  )
} else {
  switch(
    opts_knit$get("rmarkdown.pandoc.to"),
    html = {
      opts_chunk$set(dev = "png", dpi = 72)
      theme_set(
        theme_inbo(
          base_family = "FlandersArtSans-Regular", 
          base_size = 12
        )
      )
    },
    latex = {
      opts_chunk$set(dev = "cairo_pdf", dpi = 300)
      theme_set(
        theme_inbo(
          base_family = "FlandersArtSans-Regular", 
          base_size = 9
        )
      )
      update_geom_defaults("point", list(size = 1.5))
    },
    epub3 = {
      opts_chunk$set(dev = "png", dpi = 300)
      theme_set(
        theme_inbo(
          base_family = "FlandersArtSans-Regular", 
          base_size = 12
        )
      )
    }
  )
}
```

