# Dankwoord/Voorwoord {.unnumbered}

Het INBO monitoringsprogramma wordt uitgevoerd met de financiële steun van de Vlaamse Waterweg nv, Maritieme Toegang (MT) en het Agentschap voor Natuur en Bos (ANB).
Waarvoor dank.
De monitoring zou niet mogelijk geweest zijn zonder de bemanning van de schepen SCALDIS I, Scheldewacht II, Veremans, Henry de Vos en de Parel.
Dank aan Erwin De Backer (Waterbouwkundig laboratorium) voor de uitstekende planning van de bootcampagnes.

De zoogdierengegevens werden met toestemming ontleend uit de databank van Waarnemingen.be (Natuurpunt VZW).

De superdeluxe dataverzameling en het laboratoriumwerk voor watervogels, hyperbenthos, macrozoöbenthos en de hoogteraaien werden uitgevoerd door Olja Bezdenjesnji, Dimitri Buerms, Nico De Regge, Kenny Hessel, Charles Lefranc, Vincent Smeekens, Jan Soors en Frederic Van Lierop.
Topteam Estuaria!

De vismonitoring en data aanlevering werden voor ons verzorgd door INBO team MHAF (Monitoring Herstel Aquatische Fauna).
De onderzoekers en onderzoeksmedewerkers leverden opnieuw prachtig werk: Olja Bezdenjesnji, Adinda De Bruyn, Franky Dens, Marc Dewit, Linde Galle, Isabel Lambeens, Yves Maes, Thomas Terrie, Gerlinde Van Thuyne en Jeroen Van Wichelen.
Voor de ankerkuilvisserij konden we rekenen op Sjaak Bout en Davy Govers.
Dankzij hun professionele vaardigheid zijn de campagnes in 2022 vlot verlopen en kon ons onderzoek in de beste omstandigheden worden uitgevoerd, dank u wel.
Mevrouw Cabradilla (de Vlaamse Waterweg nv) verleent ons altijd vlot de nodige aanmeertoelatingen, hartelijk dank.

We zijn ook de mensen van BMK en in het bijzonder Els Lommelen zeer erkentelijk en dankbaar voor de technische ondersteuning en begeleiding bij het uitwerken van de rapportering via rmarkdown, bookdown en github.

# Samenvatting {.unnumbered}

Deze rapportage geeft toelichting bij de datarapportage van de geïntegreerde systeemmonitoring van het Schelde-estuarium, kortweg MONEOS (= MONitoring Effecten OntwikkelingsSchets), uitgevoerd door het INBO.
De nadruk ligt op de resultaten van het monitoringsjaar 2022 voor de aspecten leefomgeving voor flora en fauna en ecologie.

We lichten de langjarige trends toe en we voerden in de datarapportage de Evaluatiemethodiek Schelde-estuarium (EMSE) uit voor verschillende hoofdstukken.
De gepresenteerde eerstelijnsanalyses met de toepassing van de EMSE zijn een eerste stap en zullen komende jaren verder uitgewerkt worden.

De ecotopenkaart van 2021 van de Beneden-Zeeschelde wordt besproken.
Het globale plaatje is een uitruiming van de vaargeul met steiler wordende oevers als gevolg. De kaart toont de grootste oppervlakte sublitoraal (water) sinds de start van de meetreeks. De schoroppervlakte nam verder toe, vooral in nieuwe Sigmagebieden. Voor het eerst werd het Fort Filip als afgewerkt Sigmaproject opgenomen in de ecotopenkaart. Dit resulteerde in een netto uitbreiding van het estuarium met 5 ha. Ongeveer 4 ha daarvan is wel antropogeen hard substraat. De ecologische kwaliteitswinst zit voornamelijk in het omvormen van hoogdynamisch diep water naar laagdynamisch ondiep aansluitend op een bredere gradiënt aan slikken en de sanering van de site zelf.
In het tot nu toe toegepaste Zeeschelde ecotopenstelsel 1.0 werden subtidale (water) en litorale (slik) ecotopen vooralsnog uitsluitend op basis van diepte en overspoelingsregime onderscheiden, zonder ecologische validatie.
Op basis van recent onderzoek werd het ecotopenstelsel Zeeschelde 2.0 voorgesteld.
In deze rapportage wordt de ecotopenkaart voor de Beneden‐Zeeschelde 2021 volgens beide ecotopenstelsels voorgesteld en vergeleken.
Zo kunnen we nu in het sublitoraal de ecologisch meest waardevolle zones identificeren.
8.5% van het sublitoraal blijkt laagdynamisch waardevol habitat en situeert zich grotendeels in het ondiep subtidaal.
De klassificatie resulteert verder vooral in een verschuiving van middelhoog naar hoog slik zacht substraat of hard antropogeen (op hoog slik). De steile slikken zijn in hoofdzaak antropogeen verstevigde breuksteenzones.

Op basis van de eerste dataverkenning tonen de sedimentdata verzameld bij de macrozoöbenthosstalen doorgaans het slibrijker worden van het litoraal en het ondiep- en matig diep sublitoraal sinds 2011.
Dit is vooral opvallend in de zoete zones.
In de diepere geul van de zone met sterke saliniteitsgradiënt is de variatie in sedimentsamenstelling groot en zonder duidelijk patroon.
In de olighohaliene zone en zoet lange zone van de Zeeschelde wordt de diepe waterbodem zandiger.

De soortenrijkdom van het macrozoöbenthos (exclusief Oligochaeta) lijkt de laatste jaren licht te stijgen in de meeste zones van de Zeeschelde.
In het subtidaal zijn er veel diversiteitsschommelingen.
De shannon diversiteit in het intertidaal neemt toe in vrijwel alle zones sinds 2015.
Dit is vooral opvallend in de zone met sterke salinteitsgradiënt indien je de index baseert op aantallen, maar de index is negatief indien de diversiteitsmaat gebaseerd is op biomassa.
Dat laatste is wellicht te wijten aan de opkomst van de brakwaterkorfschelp (*Potamocorbula amurensis*) en de platte slijkgapper (*Scrobicularia plana*).
Deze soorten zijn meteen ook de oorzaak van de hoge systeembiomassa berekend voor de zone met sterke saliniteitsgradiënt, waardoor ook voor het tweede jaar op rij de intertidale systeembiomassa ruim de doelstelling van 30 ton droge stof overschrijdt.
Hoewel de systeembiomassa ruim de doelstelling haalt, worden niet in alle deelzones de lokale doelstellingen gehaald.
Vooral in de oligohaliene zone en de zoete zone met lange verblijftijd is de biomassa en soortenrijkdom macrozoöbenthos (te) laag. De zone Zoet kort verblijf bleef de hele monitoringsperiode wel afgetekend het soortenrijkste waterlichaam.

De soortenrijkdom van het hyperbenthos schommelt van jaar tot jaar.
In 2022 werd het hoogste aantal taxa, zowel totaal als enkel inheemse soorten, vastgesteld sinds de start van
de monitoring. Een hogere soortenrijkdom hangt mogelijk samen met droge jaren met lage bovenafvoer,
omdat soorten uit de Westerschelde dan vaker en verder doordringen in de Zeeschelde.
Biomassa vertoont een ander patroon met in de zones stroomopwaarts van Antwerpen een gestage
toename na juni tot het einde van het jaar. Dit bevestigt de aanname dat dit voor veel hyperbenthische
soorten en vooral voor garnalen, aasgarnalen en vissen, een opgroeigebied is. De evolutie van densiteiten
en biomassa overheen de monitoringsjaren is onderhevig aan grote schommelingen, die samen hangen
met goede en slechte jaren van specifieke soorten. Het optreden van goede of slechte jaren kan soms
gelinkt worden aan bovenafvoer en zoutgehalte, maar is ook vaak nog niet goed begrepen. Van de recente
jaren 2021‐2022, die hier gerapporteerd worden, is vooral 2021 opmerkelijk. De historisch natte zomer
en de daarmee gepaard gaande piekdebieten zorgden voor bijzonder lage hyperbenthosdensiteiten vanaf
juli tot oktober. Vanwege de grote jaarlijkse variatie introduceerden we ook een parameter die naar het
lopend gemiddeld over 3 jaar kijkt, wat een stabieler beeld van evoluties geeft. Deze parameter is meer
richtinggevend voor langetermijntrends en vertoonde in de meeste gevallen minder dan 25% variatie sinds
2015, wat recent vooropgesteld werd als nieuw kwaliteitscriterium. De laatste jaren lijkt de totale hyperbenthosbiomassa in het systeem te dalen. Vooral de grijze garnaal en de langneussteurgarnaal lijken na elk
een eigen bloeiperiode nu al enkele jaren in lagere aantallen aanwezig. 

In deze rapportage wordt de vismonitoring in 2022 op de Zeeschelde door ankerkuil en fuiken besproken. 2022 was een bodemjaar voor het aantal spieringen in de Zeeschelde. Dit geldt zowel voor de ankerkuil als voor de fuikvangsten, waardoor het beeld van de absolute dominantie van deze soort zelfs in het pelagiaal vervaagt.In 2022 werd met de ankerkuil uitzonderlijk veel sprot gevangen in Doel en Antwerpen en dit in voorjaar, zomer en najaar. In 2022 dook de visindex voor de zoete zone, met een ontoereikende kwaliteitsbeoordeling, voor het eerst sinds 2009 onder die van de brakke en oligohaliene zones. Deze situatie moet nauw opgevolgd worden.
In 2022 werd de vangstinspanning met de fuiken gehalveerd. Fuiken werden telkens 1 in plaats van 2 etmaal uitgezet.
Dit had een invloed op het aantal gevangen soorten.
Naar estuarien habitatgebruik overheersen de trekvissen de visgemeenschappen van de Zeeschelde in aantal en biomassa.
Het estuarium heeft dus weer zijn functie opgenomen in de levenscyclus van deze soorten.
Om te evalueren of de populaties echt gevestigd en duurzaam zijn is echter een cohorte analyse van de betrokken soorten in tijd en ruimte nodig.Naar dieet overheersen omnivore soorten, een normale opportunistische evolutie in een estuarium met wisselende levensomstandigheden. Toch wordt het voedselweb stilaan complexer. Dit uit zich in een toename van benthivore en piscivore soorten. Om dit beter te evalueren moet voor de belangrijkste soorten rekening gehouden worden met de dieet shift die ze maken in de overgang van juveniel naar adult. In de rapportage wordt naast een evaluatie volgens de EMSE een alternatieve beoordelingsmethode voorgesteld bruikbaar als insteek voor een toekomstige herwerking van de methodiek.   

Opvallend is dat we veel schommelingen zien in het hyperbenthos en de vissen. De vraag kan gesteld worden in hoeverre
de sterk wisselende densiteiten een natuurlijk fenomeen zijn in het bovendeel van
een estuarium en dus als negatief beoordeeld moet worden. Het is waarschijnlijk deels eigen aan een
opgroeigebied als de Zeeschelde dat er extreem succesvolle recruteringsjaren zijn waarin alle factoren
mee zitten, en waarin één of enkele soorten de gemeenschap domineren. Anderzijds is meer ecologische
kennis nodig over waarom soorten goede en slechte jaren afwisselen, en om natuurlijke en door de mens
beïnvloede oorzaken te kunnen onderscheiden. Concluderend is er een noodzaak om onderzoek op te starten om met innovatieve monitoring (bijvoorbeeld met echosounding) continue data te verzamelen. Dit onderzoek moet helpen om de variaties in het waterleven in ruimte en tijd te verklaren.

Over de periode 2009-2022 bekeken is er op het niveau van de Zeeschelde een dalende trend te zien in het aantal overwinterende watervogels.
De trendindex toont een toename in de sterke saliniteitsgradiënt. Dit is vooral te wijten aan de toename van scholeksters en bergeenden. De toename van de scholekster is vermoedelijk het gevolg van de toename aan schelpdieren (zie hoofdstuk Macrozoöbenthos). De ontpoldering van Hedwige-Prosper trok heel wat bergeenden aan die ook gebruik maakten van de slikken van de Zeeschelde.
Opvallend is de negatieve trend van de zone zoet lang, vooral veroorzaakt door een sterke afname van de wilde eend. Niettegenstaande deze trend blijft de dichtheid aan overwinterende watervogels nog steeds het hoogst in de zone zoet lang en het laagst in de zone met sterke saliniteitsgradiënt. Opvallend is een lage dichtheid aan vogels op de Durme gedurende het winterseizoen.
De diversiteit is het grootst in de zone met een sterke saliniteitsgradiënt en laag in de Durme en de zone zoet lang.
De afname van de vogelaantallen langsheen de Zeeschelde wordt gecompenseerd door de toename van de vogelaantallen in de estuariene natuurontwikkelingsgebieden.
Dit resulteert tot op heden niet in een totale toename van de watervogelaantallen binnen het estuarium (de vallei buiten beschouwing gelaten).

De evoluties in de broedvogelaantallen voor een selectie van goed te inventariseren soorten binnen IHD-gebied (wetlands en estuariene gebieden) worden besproken in deze rapportage.
Verscheidene soorten met doelstellingen komen tot 2022 nog steeds zelden tot broeden in het IHD‐gebied Schelde‐estuarium (grote karekiet, kwak, kwartelkoning, roerdomp en paapje), of werden nog nooit vastgesteld als broedvogel (purperreiger).
Grote karekiet lijkt zich wel te vestigen als regelmatige broedvogel.
Ook de lepelaar nam toe door een broedkolonie in de Durme (Meulendijkbroek).
De zomertaling, baardman, woudaap en snor vertonen de laatste jaren een stijgende trend in de vallei van de Zeeschelde en haar tijgebonden zijrivieren. Voor het eerst wordt het doel van de zomertaling bereikt.
De predatiewerende omheiningen in het noordelijk gebied hebben duidelijk een effect met hogere broedaantallen sinds 2021 van kluut, tureluur en een beperkte toename van grutto.
De bruine kiekendief blijft stabiel.
Behalve voor zomertaling, blauwborst, rietzanger en dodaars worden de doelstellingen voor geen enkele soort gehaald.

De bever koloniseerde ondertussen bijna alle geschikte habitats in het Zeeschelde-estuarium door en zit nu ook in de Grote Nete, maar beperkt zich tot nu toe tot de vallei van de Grote Laak.
Opmerkelijk zijn nieuwe waarnemingslocaties in de buurt van Antwerpen en de Antwerpse haven en de Grote Geul.
Het geschatte aantal beverterritoria in de vallei van de Zeeschelde en tijgebonden zijrivieren wordt geschat op ca.
63.
Dit stemt overeen met 38 families en 176 individuen.
De IHD-doelstelling voor bever is sinds 2021 gerealiseerd.
Het aantal waarnemeningen van otters nam niet verder toe.
De instandhoudingsdoelstellingen zijn echter zeker nog niet vervuld.
Het aantal waargenomen gewone en grijze zeehonden bleef laag en stabiel. Er waren wel waarnemingen tot ver stroomopwaarts de Zeeschelde en zijrivieren.
Er was slechts 1 waarneming van bruinvis.


De detail-hoogtemetingen op raaien langsheen de Zeeschelde illustreren en onderbouwen de waargenomen ontwikkelingen in de ecotopenkaarten.
Ter illustratie worden raaien getoond waar duidelijke veranderingen plaatsvonden in het voorjaar van 2022.
De hoogteveranderingen voor de raaien in de Beneden-Zeeschelde zijn geïllustreerd.

Ook de oevererosie werd gemonitord op basis van de bathymetrische verschilkaart (2021 versus 2020, 2019 en 2018).
Deze kaarten dienen voornamelijk ter ondersteuning van de interpretatie van erosie van het hoger slik en schorrand, die slechts 3‐jaarlijks gekarteerd worden.
Zowel in de Boven‐ als Beneden‐Zeeschelde zijn dynamieken waargenomen in enkele zones.
Meestal kon de dynamiek gelinkt worden aan menselijke activiteiten zoals bagger‐ en oeverwerken.
De waargenomen erosiezones vergen geen directe ingrepen, maar kunnen de voorbode zijn van toenemende erosieve druk en zijn zones van aandacht.
