---
params:
  hoofdstuk: "070_macrozoobenthos"
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile,
                          encoding=encoding,
                          output_dir = {
                            source("../pad.R");
                            maak_pad(rmarkdown::yaml_front_matter(inputFile)$params$hoofdstuk, "output")
                          }
                          )})
title: "Macrozoöbenthos data"
output:
  bookdown::word_document2
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, error=FALSE, warning=FALSE, message=FALSE, cache=FALSE)

```


```{r libraries}

library(tidyverse)
library(lubridate)
library(readxl)
library(writexl)
library(googlesheets4)

```


```{r pad}

# inlezen van variabelen
# pad naar data : pad_data
# pad naar tabellen : pad_tabellen
# pad naar figuren : pad_figuren

source("../pad.R")

pad_data <- maak_pad(params$hoofdstuk, "data")
pad_figuren <- maak_pad(params$hoofdstuk, "figuren")
pad_tabellen <- maak_pad(params$hoofdstuk, "tabellen")

```


```{r inlezen-uit-google-sheet}

macrobenthos_sheet <- 
  read_sheet("https://docs.google.com/spreadsheets/d/1vXtZAKBI4mN6gRGI02tZSuEt66kyARxk2DVxqEXeoT0/edit#gid=1482251030",
             sheet = "Spatial 18")

```


```{r code-waterlopen}

# # temp <-
# #   read_excel(paste0(pad_data, "S_DS_V_002_macrobenthos_data2008-2017_rapportage2019_3.xlsx"),
# #              sheet = "densiteit") %>% 
# 
# 
# temp <-
#   read_excel(paste0(pad_data, "SpatialBenthos2018.xlsx")) %>% 
#   rename(locatie = staal)
# 
# temp <-
#   temp %>%
#   mutate(code = str_sub(locatie, 1, 2))
# 
# waterloop <-
#   temp %>%
#   distinct(waterlichaam,
#            waterloop,
#            code) %>%
#   arrange(waterlichaam, waterloop)
# 
# write_xlsx(waterloop, path = paste0(pad_data, "code_waterlopen.xlsx"))


```


```{r ecotopen-en-waterlopen}

ecotopen <- read_excel(paste0(pad_data, "Ecotoop_check_SP18.xlsx"))
code_waterlopen <- read_excel(paste0(pad_data, "code_waterlopen.xlsx"))

# strata <- read_excel(paste0(pad_data, "VERDELING PER STRATUM 2019.xlsx"))

```


```{r selectie-spatial-datapunten}

macrobenthos_spatial <-
  macrobenthos_sheet %>% 
  filter(str_sub(staal, 1, 2) %in% code_waterlopen$code,
         str_sub(staal, 3, 4) == "18")

ecotopen <-
  ecotopen %>% 
  filter(str_sub(locatie, 1, 2) %in% code_waterlopen$code,
         str_sub(locatie, 3, 4) == "18")

zonder_ecotoop <-
  ecotopen %>% 
  filter(is.na(ecotoop_werkelijk))

```


```{r optellen-fracties}

macrobenthos_spatial <-
  macrobenthos_spatial %>% 
  group_by(campagne, staal, datum, soort) %>% 
  summarise(aantal = sum(aantal),
            AFDW = sum(AFDW)) %>% 
  mutate(aantalperm2 = aantal*628.8,
         AFDWperm2 = AFDW*628.8)

# testen op duplicaten
# macrobenthos_spatial %>% 
#   distinct(staal, datum) %>% 
#   count(staal) %>% 
#   filter(n > 1)

```


```{r toevoegen-waterlopen}

macrobenthos_spatial <-
  macrobenthos_spatial %>% 
  mutate(code = str_sub(staal, 1, 2)) %>% 
  left_join(code_waterlopen)
  

```


```{r toevoegen-ecotopen}

macrobenthos_spatial <-
  macrobenthos_spatial %>% 
  left_join(ecotopen %>% 
              select(staal = locatie,
                     real_X,
                     real_Y,
                     Z,
                     ecotoop_gepland,
                     ecotoop_werkelijk,
                     tidaal_gepland = tidaal)) %>% 
  mutate(tidaal_werkelijk = if_else(str_detect(ecotoop_werkelijk, "subtidaal"), "sub", "inter"))

test_ecotoop <- 
  macrobenthos_spatial %>% 
  filter(is.na(ecotoop_werkelijk) |
           ecotoop_gepland != ecotoop_werkelijk)

```


```{r wegschrijven-dataset}

write_xlsx(macrobenthos_spatial, path = paste0(pad_data, "macrobenthos_spatial_2018.xlsx"))

```

