---
editor_options: 
  markdown: 
    wrap: sentence
---

# Dankwoord/Voorwoord {.unnumbered}

Het INBO monitoringsprogramma wordt uitgevoerd met de financiële steun van de Vlaamse Waterweg nv, Maritieme Toegang (MT) en het Agentschap voor Natuur en Bos (ANB).
Waarvoor dank.
De monitoring zou niet mogelijk geweest zijn zonder de bemanning van de schepen SCALDIS I, Scheldewacht II, Veremans, Henry de Vos en de Parel.
Dank aan Erwin De Backer (Waterbouwkundig laboratorium) voor de uitstekende planning van de bootcampagnes.

De zoogdierengegevens werden met toestemming ontleend uit de databank van Waarnemingen.be (Natuurpunt VZW).

De superdeluxe dataverzameling en het laboratoriumwerk voor watervogels, hyperbenthos, macrozoöbenthos en de hoogteraaien werden uitgevoerd door Dimitri Buerms, Ada Coudenys, Nico De Regge, Kenny Hessel, Charles Lefranc, Bram Loos, Anouk Organe, Vincent Smeekens, Koen Thibau, Jan Soors en Frederic Van Lierop.
Topteam Estuaria!

De vismonitoring en data aanlevering werden voor ons verzorgd door INBO team MHAF (Monitoring Herstel Aquatische Fauna).

Medewerkers van team MHAF leverden opnieuw prachtig werk: Franky Dens, Linde Galle, Yves Maes, Isabel Lambeens, Thomas Terrie, Grim Boddez, Yente De Maesschalck en Laura Van de Meersche.\
Voor de ankerkuilvisserij konden we rekenen op Sjaak, Job en Davy.\
Dankzij hun professionele vaardigheid zijn de campagnes in 2024 vlot verlopen en kon ons onderzoek in de beste omstandigheden worden uitgevoerd, dank u wel.\
Mevrouw Cabradilla (de Vlaamse Waterweg nv) verleent ons altijd vlot de nodige aanmeertoelatingen, hartelijk dank.

# Samenvatting {.unnumbered}

Deze rapportage geeft toelichting bij de datarapportage van de geïntegreerde systeemmonitoring van het Schelde-estuarium, kortweg MONEOS (= MONitoring Effecten OntwikkelingsSchets), uitgevoerd door het INBO.
De nadruk ligt op de resultaten van de monitoringsjaren 2022 (ecotopen)-2023-2024 voor de aspecten leefomgeving voor flora en fauna en ecologie.

We lichten de langjarige trends toe en we voeren de Evaluatiemethodiek Schelde-estuarium (EMSE) uit voor verschillende hoofdstukken.

**Ecotopen**

De datarapportage bespreekt de ecotopenkaart van de Beneden-Zeeschelde in 2023, de Boven-Zeeschelde in 2022, de ecotopen van Rupel en Durme in 2022 en de ecotopen van de Ringvaart en Tijarm Zwijnaarde in 2022.
De voornaamste vaststellingen zijn:

-   De meeste ecotopen in de Beneden-Zeeschelde vertonen geen sterke evolutie en behouden hun oppervlakte in de enge planimetrie.

-   Boven-Zeeschelde: op lange termijn is er een toename van het schor en een afname van de potentiële pionierzone en hard antropogeen substraat in de enge planimetrie.

-   De **oppervlaktetoenames** in de ruime planimetrie zijn vooral het **gevolg van estuariene areaaluitbreidingen** (ontpolderingen/GGG’s in het kader van het Sigmaplan).

-   In de Durme is het sublitoraal toegenomen, afwaarts van de ontpoldering Klein Broek.

**Vegetatie** -data 2019

De vegetatiekaart van de Zeeschelde, Durme en Rupel (situatie 2019) is volledig afgewerkt en als datalaag beschikbaar gesteld.
De eerste interpretatie toont een aantal opmerkelijke tendenzen:

-   Brakwaterschorren verrieten en de zilte graslandvegetaties in de zone met sterke saliniteitsgradiënt nemen sterk af.

-   Verzilting van de zoetwaterschorren lijkt een duidelijke impact te hebben op de zoetwaterschorren nabij de zoet-zoutovergang (oligohaliene zone).
    Zo neemt de bosoppervlakte in deze zone af, neemt de brakke rietvegetatie toe en is er een duidelijke terugval van de zoetwaterminnende reuzenbalsemien (*Impatiens glandulifera*).

-   Gelinkt aan de areaaluitbreiding in het kader van het Sigmaplan is er een toename van enkele zeldzamere pionierssoorten zoals waterereprijs.
    Maar ook de driekantige bies langsheen de oevers van de Boven-Zeeschelde breidde zich uit.

**Macrozoöbenthos (Bodemdieren)** – data 2023

-   Abundantie en biomassa: het jaar 2023 was uitzonderlijk met een **hoge tot zeer hoge abundantie en** de hoogste gemiddelde **biomassa** sinds 2008 in het intertidaal (vooral in Oligohalien en Zoet lang verblijf).

-   Oorzaken: de toename is mogelijk het gevolg van verminderde top-down controle door een laag aantal hyperbenthos (garnalen/steurgarnalen) in 2023, en/of bottom-up ecologische factoren.

-   Systeembiomassa: de totale ecosysteembiomassa voor het intertidaal zacht substraat bereikte de hoogste waarde sinds 2008 (bijna het dubbele van de doelstelling).

**Hyperbenthos** – data 2024

Abundantie en biomassa: er is recent een **negatieve trend** waarneembaar, die sterker is voor biomassa en het meest uitgesproken is in de zone Oligohalien.
Dit hangt samen met de vrijwel volledige afwezigheid van grijze garnalen en langneussteurgarnalen in 2024.

Soortenrijkdom: de effectieve gemiddelde maandelijkse soortenrijkdom in 2024 was in alle zones lager dan de referentie.
De toestand voor de zone Oligohalien evolueert naar **ongunstig**.

**Vissen** – data 2024

-   Soortenrijkdom: in 2024 werd het laagste aantal vissoorten (34) gemeten sinds de start van de opvolging in 2009.

-   Visgemeenschappen: het uitzonderlijk natte voorjaar van 2024 suggereert een benedenstroomse verschuiving van de saliniteitszonaties.

-   Specifieke soorten:

    -   Spiering: voor het derde opeenvolgende jaar kende deze soort bodemaantallen in de Zeeschelde.

    -   Fint: opmerkelijk is een piek in 2024 na zeven jaar, maar verdere systematische opvolging van paaitrek en rekrutering is nodig om de duurzaamheid van de hervestiging te beoordelen.

    -   Grondels: de trend van uitzonderlijk veel gevangen grondels (vooral brakwatergrondel) zet zich door met recordaantallen.

    -   Nieuwe soort: de Shimofurigrondel (*Tridentiger bifasciatus*), een nieuwe niet-inheemse vissoort, werd voor het eerst gevangen.

-   Visindex: de visindex bereikte in 2024 een **slechte status in de zoetwater**zone (voor het eerst sinds 2003 opnieuw), een **matige toestand** in de **oligohalien**e zone en een **ontoereikend**e status in de **mesohalien**e zone.

**Overwinterende Watervogels** - data 2024

-   Recent herstel: hoewel de lange termijn negatief is, is de laatste 2-3 jaar een kentering zichtbaar met een significante toename van bodemdieretende soorten (steltlopers en eenden), wat correleert met de toename van schelpdieren en intertidale bodemdierbiomassa. De toename is ook te danken aan de recente inrichting van twee Sigmagebieden Hedwige Prosperpolder en Groot Schoor Hamme.

**Sedimentatie/Erosie** – data 2024

-   Er zijn **veel erosieve** tendenzen en de hydrodynamiek lijkt de afgelopen tien jaar toegenomen zowel in de Beneden-Zeeschelde als in Boven-Zeeschelde. In de Beneden-Zeeschelde spelen scheepsgolven waarschijnlijk een toenemende rol in de erosieprocessen.
-   Zoete Zone & Boven-Zeeschelde: in 2025 zijn de morfologische veranderingen geïntensiveerd met **erosieve trends of trendbreuken** op bijna 80% van de gemonitorde raaien in de zoete zone (tussen Durme en Melle).
    -   Oorzaak: deze snelle en sterke veranderingen op de oevers wijzen op een verandering in de hydro- en morfodynamiek in de Boven-Zeeschelde, gelinkt aan de bathymetrische veranderingen en toegenomen waterdynamiek.
    -   Aanbeveling: verder onderzoek is nodig om de oorzaken van deze erosie van habitats te bepalen zodat het beheer bijgestuurd kan worden zodat een meer veerkrachtig, klimaatadaptief ecosysteem in gunstige stand van instandhouding gebracht kan worden.
