---
editor_options: 
  markdown: 
    wrap: sentence
---

# Dankwoord/Voorwoord {.unnumbered}

Het INBO monitoringsprogramma wordt uitgevoerd met de financiële steun van De Vlaamse Waterweg nv (DVW), Maritieme Toegang (MT) en het Agentschap voor Natuur en Bos (ANB).
Waarvoor dank.
De monitoring zou niet mogelijk geweest zijn zonder de bemanning van de schepen SCALDIS I, Scheldewacht II, Veremans, Henry de Vos en de Parel.
Dank aan Erwin De Backer (Waterbouwkundig laboratorium) voor de uitstekende planning van de bootcampagnes.

De zoogdierengegevens werden met toestemming ontleend uit de databank van Waarnemingen.be (Natuurpunt VZW).

De superdeluxe dataverzameling en het laboratoriumwerk voor watervogels, hyperbenthos, macrozoöbenthos en de hoogteraaien werden uitgevoerd door Dimitri Buerms, Ewout Compernol, Ada Coudenys, Nico De Regge, Kenny Hessel, Charles Lefranc, Bram Loos, Vincent Smeekens, Koen Thibau, Jan Soors en Frederic Van Lierop.
Topteam Estuaria!

De vismonitoring en data aanlevering werden voor ons verzorgd door INBO team MHAF (Monitoring Herstel Aquatische Fauna).

Medewerkers van team MHAF leverden opnieuw prachtig werk: Franky Dens, Linde Galle, Yves Maes, Isabel Lambeens, Thomas Terrie, Grim Boddez, Yente De Maesschalck en Laura Van de Meersche.\
Voor de ankerkuilvisserij konden we rekenen op Sjaak, Job en Davy.\
Dankzij hun professionele vaardigheid zijn de campagnes in 2024 vlot verlopen en kon ons onderzoek in de beste omstandigheden worden uitgevoerd, dank u wel.\
Mevrouw Cabradilla (de Vlaamse Waterweg nv) verleent ons altijd vlot de nodige aanmeertoelatingen, hartelijk dank.

# Samenvatting {.unnumbered}

Deze rapportage geeft toelichting bij de datarapportage van de geïntegreerde systeemmonitoring van het Schelde-estuarium, kortweg MONEOS (= MONitoring Effecten OntwikkelingsSchets), uitgevoerd door het INBO.
De nadruk ligt op de resultaten van de monitoringsjaren 2024-2025 voor de aspecten leefomgeving voor flora en fauna en ecologie.

We lichten de langjarige trends toe en we voeren de Evaluatiemethodiek Schelde-estuarium (EMSE) uit voor verschillende hoofdstukken.

**Overzicht Estuariene natuurontwikkelingsprojecten**

Tot medio 2026 is ongeveer 800 hectare estuariene natuur (slik en schor) gerealiseerd van de vooropgestelde streefdoelstelling van 2000 hectare (500 hectare slik en 1500 hectare schor).
Extra natuurontwikkeling blijft dus noodzakelijk.
Recente uitbreidingen: Na de grote ontpolderingen van Prosper- en Hedwigepolder in 2022, werden in het najaar van 2025 GGG Wal-Zwijn, GGG Vlassenbroekse Polder (Noord) en GGG Bovenzanden geopend, goed voor bijna 230 ha bijkomende gereduceerde getijdennatuur.
Klein Broek (Durme) was in 2025/2026 tijdelijk niet-functioneel wegens werkzaamheden.

**Ecotopen**

De datarapportage bespreekt de ecotopenkaart van de Beneden-Zeeschelde in 2024.
De voornaamste vaststellingen zijn:

- De toename van het sublitoraal met 16,8 hectare vooral door een toename van het ondiep subtidaal. Dit vooral tenkoste van het laag slik.

**Sedimentkenmerken** - data 2025

Zowel in de Zeeschelde als haar zijrivieren worden de **intertidale habitats gestaag slibrijker** (fijner sediment).
Het diep subtidaal (geul) kent een hoge variatie in slibgehalte; dit hangt vermoedelijk samen met schommelingen in rivierdebieten en sedimenttransport tussen droge en natte periodes.

**Macrozoöbenthos (Bodemdieren)** – data 2024

Abundantie en biomassa: 2024 was een jaar met **hoge benthosbiomassa en -densiteiten** in zowel het intertidaal als subtidaal (vooral in de zones oligohalien en zoet lang verblijf).
  De stijgende trend houdt nu al meerder jaren aan.

Systeembiomassa: de totale ecosysteembiomassa voor het intertidaal zacht substraat bereikte de hoogste waarde sinds 2008 (bijna het dubbele van de doelstelling).
  De intertidale biomassa in 'zoet lange verblijftijd' zette de in 2023 ingezette hersteltrend voort.

**Hyperbenthos** – data 2025

Abundantie en biomassa: er is een doorgaande **negatieve trend** waarneembaar.
Een toename van de langneussteurgarnalen in 2025 in het oligohalien vormde een uitzondering.

Soortenrijkdom: de effectieve gemiddelde maandelijkse soortenrijkdom in 2025 was in alle zones lager dan de referentie.

**Vissen** – data 2025

Soortenrijkdom: de soortenrijkdom herstelde zich in 2025 naar de normale gemiddelden (42 waargenomen vissoorten), met de hoogste soortendiversiteit in de zone met sterke saliniteitsgradiënt.

- Specifieke soorten:

  - Spiering: voor het vierde opeenvolgende jaar kende deze soort bodemaantallen in de Zeeschelde.

  - Fint: Na de piek van fint in 2024 is de soort in 2025 opnieuw slechts beperkt aanwezig.

  - Grondels: de trend van uitzonderlijk veel gevangen grondels (vooral brakwatergrondel) zet zich niet door.

Visindex: de visindex bereikte in 2025 een **matige kwaliteit** in alle zones, wat een duidelijke verbetering inhoudt ten opzichte van voorgaande dipjaren.

**Overwinterende Watervogels** - data 2024

Hoewel de meeste overwinterende sleutelsoorten over de lange en middellange termijn een afnemende trend vertonen, is er de laatste zes telseizoenen een kentering merkbaar met een significante toename van bergeend, krakeend en wintertaling.
Beschouwen we de trends per trofische groep, dan valt vooral de sterke toename van benthivore soorten op (in de eerste plaats steltlopers en in het bijzonder de Scholekster).
Mogelijk houdt dit verband met een biomassatoename van schelpdieren, meer bepaald de brakwaterkorfschelp.

**Broedvogels** - data 2025

Moeras- en rietvogels kenden een positieve evolutie.
De Roerdomp bereikte een recordaantal territoria, mede dankzij een bemoedigende vestiging in Anderstand/Polder van Lier.
Ook de Bruine kiekendief breidde zich ruimtelijk uit maar de aantallen blijven wel nog ver onder de doelstelling van veel soorten.
Vooral de vogels van schrale graslandtypes blijven afwezig door gebrek aan verschraald leefgebied.

**Sedimentatie/Erosie** – data 2025

Er is sprake van **stabilisatie**.
Na enkele jaren van uitgesproken erosie lijkt er minder erosie of zelfs sedimentatie te zijn geweest in 2025-2026.
Een uitzondering is de raai BR (Branst) waar erosie optreedt door uitbochting van de geul.
Het systeem lijkt hier morfologisch uit evenwicht.
Mogelijk is het aangewezen het duurzame bathymetrie onderhoud te herijken en/of de zandwinning te evalueren.

**Monitoring slik en schorrand**

Uit de vergelijking van kaarten (2025 vs. 2024/2023/2022) werden lokale erosie- en sedimentatiezones in de onderste oeverzone geïdentificeerd.
De vastgestelde erosiezones vereisen momenteel **geen directe ingrepen**, maar blijven aandachtsgebieden.
