# Vegetatiekaart

Fichenummer: S-DH-V-003 -- Vegetatiekartering

Bart Vandevoorde, Frederik Van Lierop, Simon Desmet, Ewout Compernol & Koen Thibau

## Inleiding

Met behulp van schorvegetatiekaarten kan de evolutie van de habitatdiversiteit binnen het schorecotoop nader geëvalueerd worden. De basiseenheid van deze vegetatiekaart, is een homogene vegetatie-eenheid waaraan volgens een hiërarchisch systeem een habitat, formatie en vegetatietype zijn toegekend. Deze vegetatietypes kunnen gekoppeld worden aan een Europees Natura2000-habitattype.

In Tabel \@ref(tab:Tabel1) is een overzicht gegeven van de vegetatiekaarten die van de schorren zijn gemaakt de voorbije decennia of die in opmaak zijn (2025). De gebruikte methode, ruimtelijke afbakening en detailgraad zijn niet voor alle kaarten gelijk. Zo zijn de kaarten van 1992, 1996, 2003, 2013 en 2019 gemaakt aan de hand van de fotogeleide veldmethode. Dit geldt ook voor de kaart van 2025. Remote sensing-technieken zijn gebruikt in 2007 om het hele Zeeschelde-estuarium te karteren (Bertels *et al*., 2008) en in 2011 voor de vegetatiekartering van de Beneden-Zeeschelde (Eurosense, 2012). Voor een overzicht van de historische kaarten en een toelichting bij de gebruikte codes verwijzen we naar Vandevoorde (2011).

  --------------------------------------------------------------------------------------------------------------
  **Deelgebied**        **1992**   **1996**   **2003**   **2007**   **2011**   **2013**   **2019**   ***2025***
  -------------------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ------------
  Beneden-Zeeschelde       A          A          A          B          B          A          A          *A*

  Boven-Zeeschelde         A          A          A          B                     A          A          *A*

  Durme                               A          A          B                     A          A          *A*

  Rupel                                          A          B                     A          A          *A*

  Zenne                                                    A B                    A                     *A*

  Dijle                                                    A B                    A                     *A*

  Kleine Nete                                              A B                    A                     *A*

  Grote Nete                                               A B                    A                     *A*
  --------------------------------------------------------------------------------------------------------------

  : (#tab:Tabel1) Overzicht van de jaren waarvan vegetatiekaarten beschikbaar zijn. De verschillende deelgebieden zijn gekarteerd volgens de klassieke karteringsmethode (A) of door middel van remote sensing-technieken (B).

Momenteel is de vegetatiekaart van 2025 in opmaak. Deze kaart zal de schorren van de volledige Zeeschelde, Durme en Rupel omvatten, inclusief de getijdenafhankelijke delen van de Ringvaart en Tijarm in het meest stroomopwaartse deel van het estuarium (regio Gent). Bovendien zal deze kaart ook de schorren bevatten langs de Beneden-Nete en langs de getijdenafhankelijke delen van de Grote Nete tot Itegem, van de Kleine Nete tot Grobbendonk, van de Zenne tot Zemst en van de Dijle tot Werchter.

Ook de ontpolderingen gerealiseerd voor augustus 2025 maken deel uit van deze kaart (bijv. Wijmeers, Fasseit, Kruibeekse kreek[^1], Burchtse Weel^1^, Potpolder Lillo, enz.). Naast deze ontpolderingen zijn ook de verschillende functionele gecontroleerd gereduceerd getijdengebieden (GGG's) in deze vegetatiekaart opgenomen (Bergenmeersen, Lippenbroek, Polders van Kruibeke (GGG-Kruibeke, GGG Bazel-Noord), Zennegat, enz.).

Voor deze kartering zijn in augustus 2025 falsecolour infrared-beelden (FCIR) gemaakt van het volledige projectgebied, inclusief de nieuw aangelegde gebieden (GGG's en ontpolderingen). Met behulp van deze beelden zal veldwerk verricht worden om grondwaarheidsgegevens te verzamelen.

Langs de smalle oeverstroken worden biezen-, riet- en pioniersvegetaties integraal gekarteerd. De dataverzameling hiervoor gebeurd vanop een boot. De hogere delen van het schor langs deze oeverstroken zullen steekproefsgewijs worden gekarteerd.

## Referenties

Bertels L., Houthuys R., Deronde B., Knaeps E., Vandevoorde B. & Van den Bergh E. (2008). Automatische kartering voor opvolging areaal slikken en schorren. Rapport VITO 2008/TAP/R/076, 137 p.

Eurosense (2012). Hyperspectraalmetingen en kartering van slikken en schorren van de Zeeschelde afwaarts Wintam in het kader van de geïntegreerde monitoring van het Schelde-estuarium (MONEOS-programma). Eindrapport 01/10/2012. In opdracht van W&Z Afdeling Zeeschelde.

Vandevoorde B. (2011). Systeemmonitoring vegetatiekartering. In Van Ryckegem G., (red.) (2011). MONEOS --Geïntegreerd datarapport Toestand Zeeschelde tot 2009. Datarapportage ten behoeve van de VNSC voor het vastleggen van de uitgangssituatie anno 2009. Rapporten van het Instituut voor Natuur- en Bosonderzoek INBO.R.2011.8. Instituut voor Natuur‐ en Bosonderzoek, Brussel.

[^1]: Dit betreffen aantakkingen omdat deze gebieden via een koker of sluis verbonden zijn met de Zeeschelde wat het getijpatroon en de dynamiek beïnvloeden.

