---
params:
  hoofdstuk: "090_vissen"
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile,
                          encoding=encoding,
                          output_dir = paste0(rmarkdown::yaml_front_matter(inputFile)$params$hoofdstuk, "/output"))})
title: "analyse visdata fuiken"
output: word_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, error=FALSE, warning=FALSE, message=FALSE, cache=FALSE)

```


```{r libraries}

library(tidyverse)
library(lubridate)
library(janitor)
library(readxl)
library(writexl)
# library(yarrr)
library(wesanderson)
library(gridExtra)
library(cowplot)

library(INBOtheme)
library(inbodb)

library(rprojroot) ## workaround pad

conflicted::conflicts_prefer(dplyr::filter)

```


```{r pad}

# inlezen van variabelen
# pad naar data : pad_data
# pad naar tabellen : pad_tabellen
# pad naar figuren : pad_figuren

source(find_root_file("../pad.R", criterion = is_rstudio_project))

pad_data <- maak_pad(params$hoofdstuk, "data")
# pad_figuren <- maak_pad(params$hoofdstuk, "figuren/fuiken")
# pad_tabellen <- maak_pad(params$hoofdstuk, "tabellen/fuiken")

```


```{r EMSE tabellen}

soortenlijst <- 
  read_xlsx(str_c(pad_data, "soorten_Zeeschelde.xlsx"), sheet = "EMSE")

sleutelsoorten_EMSE <-
  read_xlsx(str_c(pad_data, "sleutelsoorten EMSE.xlsx"))

# func_groepen_EMSE <-
#   read_xlsx(str_c(pad_data, "functionele groepen.xlsx")) %>% 
#   mutate(Soort = str_to_lower(Soort))

levels_indeling <-
  c("Mar/Est -- Benth", "Mar/Est -- Omn", "Mar/Est -- Pisc", "Mar/Est -- Plankt",
    "Diadr -- Benth", "Diadr -- Omn", "Diadr -- Pisc", "Diadr -- Plankt",
    "Zoetw -- Benth", "Zoetw -- Omn", "Zoetw -- Pisc", "Zoetw -- Plankt")

locatie_scheldezone_fuiken <- 
  read_xlsx(str_c(pad_data, "metadata VLIZ/fuikvangsten_Zeeschelde_locaties.xlsx")) %>% 
  mutate(locatie = factor(locatie, levels = locatie[order(Y, decreasing = TRUE)])) %>% 
  select(locatie, scheldezone_full = EMSE_niveau3) %>% 
  mutate(scheldezone_full = str_remove(scheldezone_full, " verblijf"),
         scheldezone = 
           case_when(
             scheldezone_full == "saliniteitsgradient" ~ "SG",
             scheldezone_full == "oligohalien" ~ "OH",
             scheldezone_full == "zoet lang" ~ "ZL",
             scheldezone_full == "zoet kort" ~ "ZK"))

levels_locatie_fuiken <- levels(locatie_scheldezone_fuiken$locatie)

locatie_scheldezone_ankerkuil <- 
  read_xlsx(str_c(pad_data, "metadata VLIZ/ankerkuil_Zeeschelde_locaties.xlsx")) %>% 
  mutate(locatie = factor(locatie, levels = locatie[order(Y, decreasing = TRUE)])) %>% 
  select(locatie, scheldezone_full = EMSE_niveau3) %>% 
  mutate(scheldezone_full = str_remove(scheldezone_full, " verblijf"),
         scheldezone = 
           case_when(
             scheldezone_full == "saliniteitsgradient" ~ "SG",
             scheldezone_full == "oligohalien" ~ "OH",
             scheldezone_full == "zoet lang" ~ "ZL",
             scheldezone_full == "zoet kort" ~ "ZK"))

levels_locatie_ankerkuil <- levels(locatie_scheldezone_ankerkuil$locatie)

levels_scheldezone <-
  c("SG", "OH", "ZL", "ZK")

levels_scheldezone_full <-
  c(SG = "saliniteitsgradient", OH = "oligohalien", ZL = "zoet lang", ZK = "zoet kort")


```

##### datasets voor aantal en gewicht:

```{r data fuiken}

(filename <- 
  list.files(path = pad_data,
             pattern = "fuikdata_Zeeschelde_VLIZ") %>% 
  .[str_detect(., "~\\$", negate = TRUE)])

fuiken_aantal <- 
  read_xlsx(str_c(pad_data, filename),
            sheet = "campagnes") %>% 
  select(ID_afvissing, locatie, datum, jaar, seizoen, fuikdagen) %>% 
  left_join(read_xlsx(str_c(pad_data, filename),
                      sheet = "locaties") %>% 
              select(locatie, OMES, EMSE_niveau3)) %>% 
  left_join(read_xlsx(str_c(pad_data, filename),
                      sheet = "aantallen")) %>% 
  select(-ID_afvissing) %>% 
  select(locatie, OMES, EMSE_niveau3, datum, jaar, seizoen, everything())

fuiken_gewicht <- 
  read_xlsx(str_c(pad_data, filename),
            sheet = "campagnes") %>% 
  select(ID_afvissing, locatie, datum, jaar, seizoen, fuikdagen) %>% 
  left_join(read_xlsx(str_c(pad_data, filename),
                      sheet = "locaties") %>% 
              select(locatie, OMES, EMSE_niveau3)) %>% 
  left_join(read_xlsx(str_c(pad_data, filename),
                      sheet = "gewicht")) %>% 
  select(-ID_afvissing) %>% 
  select(locatie, OMES, EMSE_niveau3, datum, jaar, seizoen, everything())


data_fuiken <- 
  fuiken_aantal %>% 
  pivot_longer(cols = -(locatie:fuikdagen),
               names_to = "soort",
               values_to = "aantal") %>%
  left_join(fuiken_gewicht %>% 
              pivot_longer(cols = -(locatie:fuikdagen),
                           names_to = "soort",
                           values_to = "gewicht")) %>% 
  mutate(gewicht = if_else(aantal == 0, 0, gewicht),
         seizoen = factor(seizoen, levels = c("voorjaar", "zomer", "najaar", "winter")),
         locatie = factor(locatie, levels = levels_locatie_fuiken)) %>%
  group_by(soort) %>% 
  mutate(anyN = any(aantal > 0)) %>% 
  ungroup() %>% 
  filter(anyN) %>% 
  select(-anyN) %>% 
  left_join(soortenlijst %>% 
              select(-opmerking))

```


```{r data ankerkuil}

(filename <- 
  list.files(path = pad_data,
             pattern = "ankerkuil_Zeeschelde_VLIZ")) %>% 
  .[str_detect(., "~\\$", negate = TRUE)]

ankerkuil_aantal <- 
  read_xlsx(str_c(pad_data, filename),
            sheet = "campagnes") %>% 
  select(ID_afvissing, locatie, datum, jaar, seizoen, getijde, volume) %>% 
  left_join(read_xlsx(str_c(pad_data, filename),
                      sheet = "locaties") %>% 
              select(locatie, OMES, EMSE_niveau3)) %>% 
  left_join(read_xlsx(str_c(pad_data, filename),
                      sheet = "aantallen")) %>% 
  select(-ID_afvissing) %>% 
  select(locatie, OMES, EMSE_niveau3, datum, jaar, seizoen, everything())

ankerkuil_gewicht <- 
  read_xlsx(str_c(pad_data, filename),
            sheet = "campagnes") %>% 
  select(ID_afvissing, locatie, datum, jaar, seizoen, getijde, volume) %>% 
  left_join(read_xlsx(str_c(pad_data, filename),
                      sheet = "locaties") %>% 
              select(locatie, OMES, EMSE_niveau3)) %>% 
  left_join(read_xlsx(str_c(pad_data, filename),
                      sheet = "gewicht")) %>% 
  select(-ID_afvissing) %>% 
  select(locatie, OMES, EMSE_niveau3, datum, jaar, seizoen, everything())



data_ankerkuil <- 
  ankerkuil_aantal %>% 
  pivot_longer(cols = -(locatie:volume),
               names_to = "soort",
               values_to = "aantal") %>%
  left_join(ankerkuil_gewicht %>% 
              pivot_longer(cols = -(locatie:volume),
                           names_to = "soort",
                           values_to = "gewicht")) %>% 
  mutate(gewicht = if_else(aantal == 0, 0, gewicht),
         seizoen = factor(seizoen, levels = c("voorjaar", "zomer", "najaar", "winter")),
         locatie = factor(locatie, levels = levels_locatie_ankerkuil)) %>%
  group_by(soort) %>% 
  mutate(anyN = any(aantal > 0)) %>% 
  ungroup() %>% 
  filter(anyN) %>% 
  select(-anyN) %>% 
  left_join(soortenlijst %>% 
              select(-opmerking))

```


```{r samenvoegen Zandvliet en Paardenschor}

data_fuiken <-
  data_fuiken %>% 
  mutate(locatie = 
           if_else(locatie == "Zandvliet",
                   "Paardenschor",
                   locatie))

```


```{r optellen eb vloed per locatie & campagne}

(groupvars <- 
  names(data_ankerkuil) %>% 
  setdiff(c("datum", "getijde", "volume", "aantal", "gewicht")))

# setdiff(names(data_ankerkuil), groupvars)

data_ankerkuil <-
  data_ankerkuil %>% 
  select(-datum, -getijde) %>% 
  group_by(across(all_of(groupvars))) %>% 
  summarise(across(everything(), sum)) %>% 
  ungroup()

dupes_na <-
  data_ankerkuil %>% 
  select(locatie:seizoen) %>% 
  distinct() %>% 
  get_dupes(locatie, jaar, seizoen)

```


```{r optellen datums per locatie & campagne}

dupes_voor <-
  data_fuiken %>% 
  select(locatie:seizoen) %>% 
  distinct() %>% 
  get_dupes(locatie, jaar, seizoen)

groupvars <- 
  names(data_fuiken) %>% 
  setdiff(c("datum", "fuikdagen", "aantal", "gewicht"))

data_fuiken <-
  data_fuiken %>% 
  select(-datum) %>% 
  group_by(across(all_of(groupvars))) %>% 
  summarise(across(everything(), sum)) %>% 
  ungroup()

dupes_na <-
  data_fuiken %>% 
  select(locatie:seizoen) %>% 
  distinct() %>% 
  get_dupes(locatie, jaar, seizoen)

```


```{r variabelen & functies}

prop_lim <- 0.1

```


```{r selectie data}

data_fuiken <- 
  data_fuiken %>% 
  filter(!str_detect(soort, "hybride"),
         seizoen != "winter")

data_ankerkuil <- 
  data_ankerkuil %>% 
  filter(seizoen != "winter")

```


```{r enkel-vissen fuiken}

soorten <- 
  data_fuiken %>% 
  distinct(soort) %>% 
  pull(soort)

# soorten_invertebraten <-
#   c("wolhandkrab", "grijze garnalen", "steurgarnalen", "gammarus", "noordzeekrab", "japanse steurgarnaal", "penseelkrab")

soorten_invertebraten <-
  soorten %>% 
  keep(~ str_detect(., "garnaal|garnalen|gammarus|krab|kreeft|inktvis|octopus|zeekat")) 

soorten_vis_fuiken <-
  setdiff(soorten, soorten_invertebraten) %>% 
  {.[order(.)]}

data_fuiken <- 
  data_fuiken %>% 
  filter(soort %in% soorten_vis_fuiken)

# soorten_fuiken_sheet <-
#   soortenlijst %>%
#   filter(!is.na(fuiken)) %>%
#   pull(soort)
# 
# setdiff(soorten_fuiken_sheet, soorten_vis_fuiken)
# setdiff(soorten_vis_fuiken, soorten_fuiken_sheet)

```


```{r enkel-vissen ankerkuil}

soorten <- 
  data_ankerkuil %>% 
  distinct(soort) %>% 
  pull(soort)

# soorten_invertebraten <-
#   c("wolhandkrab", "grijze garnalen", "steurgarnalen", "gammarus", "noordzeekrab", "japanse steurgarnaal", "penseelkrab")

soorten_invertebraten <-
  soorten %>% 
  keep(~ str_detect(., "garnaal|garnalen|gammarus|krab|kreeft|inktvis|octopus|zeekat")) 

soorten_vis_ankerkuil <-
  setdiff(soorten, soorten_invertebraten) %>% 
  {.[order(.)]}

data_ankerkuil <- 
  data_ankerkuil %>% 
  filter(soort %in% soorten_vis_ankerkuil)


# soorten_fuiken_sheet <-
#   soortenlijst %>%
#   filter(!is.na(ankerkuil)) %>%
#   pull(soort)
# 
# setdiff(soorten_fuiken_sheet, soorten_vis)
# setdiff(soorten_vis, soorten_fuiken_sheet)

```


```{r aantal-en-gewicht-per-fuikdag}

data_fuiken <- 
  data_fuiken %>% 
  mutate(aantal_per_fuikdag = aantal/fuikdagen,
         gewicht_per_fuikdag = gewicht/fuikdagen)

```


```{r salgroep en dieet haringachtigen}

soortenlijst %>% 
  filter(soort %in% c("haring", "sprot"))

data_ankerkuil <- 
  data_ankerkuil %>% 
  mutate(salgroep = if_else(soort == "haringachtigen", "mariene migranten", salgroep),
         dieet = if_else(soort == "haringachtigen", "planktivoren", dieet))

```


```{r aantal-en-gewicht-per-kub}

data_ankerkuil <- 
  data_ankerkuil %>% 
  mutate(aantal_per_kub = aantal/volume,
         gewicht_per_kub = gewicht/volume)

```


```{r indeling EMSE rapportage}

indeling_EMSE_full <-
  expand_grid(nesting(salgroep = c("mariene en estuariene soorten", "diadrome soorten", "zoetwatersoorten"),
                      sal_kort = c("Mar/Est", "Diadr", "Zoetw")),
              nesting(dieet = c("benthivoren", "omnivoren", "planktivoren", "piscivoren"),
                      dieet_kort = c("Benth", "Omn", "Plankt", "Pisc"))) %>% 
  mutate(indeling = str_c(sal_kort, dieet_kort, sep = " -- "))

data_fuiken %>% 
  distinct(salgroep)

data_fuiken %>% 
  distinct(dieet)

data_fuiken <- 
  data_fuiken %>% 
  mutate(salgroep_detail = salgroep,
         salgroep = case_when(
           salgroep_detail %in% c("mariene migranten", "mariene dwaalgasten", "estuarien residenten") ~ "mariene en estuariene soorten",
           salgroep_detail %in% c("diadromen") ~ "diadrome soorten",
           salgroep_detail %in% c("zoetwatersoorten") ~ "zoetwatersoorten"
         )) %>% 
  left_join(indeling_EMSE_full) %>% 
  mutate(indeling = factor(indeling, levels = levels_indeling),
         in_indeling = !is.na(indeling)) %>% 
  left_join(sleutelsoorten_EMSE %>% select(-scheldezone) %>% rename(indeling_SL = indeling))

indeling_EMSE_soort <-
  data_fuiken %>% 
  distinct(soort, salgroep, dieet, in_indeling, indeling, indeling_SL)

indeling_EMSE_groep <-
  data_fuiken %>% 
  distinct(salgroep, dieet, indeling)

indeling_EMSE_missing <-
  indeling_EMSE_full %>% 
  select(salgroep, dieet, indeling) %>% 
  anti_join(indeling_EMSE_groep)

# levels(data_fuiken$indeling)
# levels(indeling_EMSE$indeling)

indeling_EMSE_full <-
  expand_grid(nesting(salgroep = c("mariene en estuariene soorten", "diadrome soorten", "zoetwatersoorten"),
                      sal_kort = c("Mar/Est", "Diadr", "Zoetw")),
              nesting(dieet = c("benthivoren", "omnivoren", "planktivoren", "piscivoren"),
                      dieet_kort = c("Benth", "Omn", "Plankt", "Pisc"))) %>% 
  mutate(indeling = str_c(sal_kort, dieet_kort, sep = " -- "))

data_ankerkuil %>% 
  distinct(salgroep)

data_ankerkuil %>% 
  distinct(dieet)

data_ankerkuil <- 
  data_ankerkuil %>% 
  mutate(salgroep_detail = salgroep,
         salgroep = case_when(
           salgroep_detail %in% c("mariene migranten", "mariene dwaalgasten", "estuarien residenten") ~ "mariene en estuariene soorten",
           salgroep_detail %in% c("diadromen") ~ "diadrome soorten",
           salgroep_detail %in% c("zoetwatersoorten") ~ "zoetwatersoorten"
         )) %>% 
  left_join(indeling_EMSE_full) %>% 
  mutate(indeling = factor(indeling, levels = levels_indeling),
         in_indeling = !is.na(indeling)) %>% 
  left_join(sleutelsoorten_EMSE %>% select(-scheldezone) %>% rename(indeling_SL = indeling))

indeling_EMSE_soort <-
  data_ankerkuil %>% 
  distinct(soort, salgroep, dieet, in_indeling, indeling, indeling_SL)

indeling_EMSE_groep <-
  data_ankerkuil %>% 
  distinct(salgroep, dieet, indeling)

indeling_EMSE_missing <-
  indeling_EMSE_full %>% 
  select(salgroep, dieet, indeling) %>% 
  anti_join(indeling_EMSE_groep)

```


```{r soorten kleur}

relatief_aantal_fuiken <- 
  data_fuiken %>% 
  filter(jaar == 2022) %>% 
  group_by(seizoen, locatie) %>%
  mutate(relatief_aantal = aantal/sum(aantal),
         relatief_gewicht = gewicht/sum(gewicht)) %>% 
  ungroup() %>% 
  group_by(soort) %>% 
  mutate(soort2 = ifelse(any(relatief_aantal >= prop_lim | relatief_gewicht >= prop_lim), soort, "rest")) %>% 
  ungroup() %>% 
  group_by(seizoen, locatie, soort2) %>% 
  summarise(aantal = sum(aantal)) %>% 
  ungroup() %>% 
  group_by(seizoen, locatie) %>% 
  mutate(soort2 = soort2,
         aantal = round(aantal/sum(aantal)*100)) %>% 
  ungroup() %>% 
  rename(soort = soort2) %>% 
  mutate(soort = factor(soort, 
                        levels = unique(soort) %>% 
                          sort() %>% 
                          setdiff("rest") %>% 
                          c(., "rest")),
         locatie = factor(locatie, levels = levels_locatie_fuiken))

(soorten_fuiken_1 <-
  relatief_aantal_fuiken %>% 
  distinct(soort) %>% 
  filter(str_detect(soort, "rest", negate = TRUE)) %>% 
  pull())


relatieve_aantallen_EMSE_fuiken <- 
  data_fuiken %>% 
  left_join(locatie_scheldezone_fuiken) %>% 
  filter(in_indeling) %>% 
  filter(aantal > 0) %>% 
  group_by(jaar, scheldezone, soort, salgroep, dieet, indeling) %>%
  summarise(aantal_per_fuikdag = mean(aantal_per_fuikdag),
            gewicht_per_fuikdag = mean(gewicht_per_fuikdag)) %>% 
  ungroup() %>% 
  group_by(jaar, scheldezone, salgroep, dieet, indeling) %>%
  mutate(relatief_aantal = aantal_per_fuikdag/sum(aantal_per_fuikdag),
         relatief_gewicht = gewicht_per_fuikdag/sum(gewicht_per_fuikdag)) %>% 
  mutate(max_aantal = relatief_aantal >= prop_lim,
         max_gewicht = relatief_gewicht >= prop_lim) %>%
  ungroup() %>% 
  group_by(soort) %>% 
  mutate(soort = ifelse(any(max_aantal) | any(max_gewicht), soort, "rest")) %>% 
  ungroup()

(soorten_fuiken_2 <-
  relatieve_aantallen_EMSE_fuiken %>% 
  distinct(soort) %>% 
  filter(str_detect(soort, "rest", negate = TRUE)) %>% 
  pull())


relatief_aantal_ankerkuil <- 
  data_ankerkuil %>% 
  filter(jaar == 2022) %>% 
  group_by(seizoen, locatie) %>%
  mutate(relatief_aantal_laatste_jaar = aantal/sum(aantal),
         relatief_gewicht_laatste_jaar = gewicht/sum(gewicht)) %>% 
  ungroup() %>% 
  group_by(soort) %>% 
  mutate(soort2 = ifelse(any(relatief_aantal_laatste_jaar >= prop_lim | relatief_gewicht_laatste_jaar >= prop_lim), soort, "rest")) %>% 
  ungroup() %>% 
  group_by(seizoen, locatie, soort2) %>% 
  summarise(aantal = sum(aantal)) %>% 
  ungroup() %>% 
  group_by(seizoen, locatie) %>% 
  mutate(soort2 = soort2,
         aantal = round(aantal/sum(aantal)*100)) %>% 
  ungroup() %>% 
  rename(soort = soort2) %>% 
  mutate(soort = factor(soort, 
                        levels = unique(soort) %>% 
                          sort() %>% 
                          setdiff("rest") %>% 
                          c(., "rest")))

(soorten_ankerkuil_1 <-
  relatief_aantal_ankerkuil %>% 
  distinct(soort) %>% 
  filter(str_detect(soort, "haringachtigen|rest", negate = TRUE)) %>% 
  pull())

relatieve_aantallen_EMSE_ankerkuil <- 
  data_ankerkuil %>% 
  left_join(locatie_scheldezone_ankerkuil) %>% 
  filter(in_indeling) %>% 
  filter(aantal > 0) %>% 
  group_by(jaar, scheldezone, soort, salgroep, dieet, indeling) %>%
  summarise(aantal_per_kub = mean(aantal_per_kub),
            gewicht_per_kub = mean(gewicht_per_kub)) %>% 
  ungroup() %>% 
  group_by(jaar, scheldezone, salgroep, dieet, indeling) %>%
  mutate(relatief_aantal = aantal_per_kub/sum(aantal_per_kub),
         relatief_gewicht = gewicht_per_kub/sum(gewicht_per_kub)) %>% 
  mutate(max_aantal = relatief_aantal >= prop_lim,
         max_gewicht = relatief_gewicht >= prop_lim) %>%
  ungroup() %>% 
  group_by(soort) %>% 
  mutate(soort = ifelse(any(max_aantal) | any(max_gewicht), soort, "rest")) %>%
  ungroup()

(soorten_ankerkuil_2 <-
  relatieve_aantallen_EMSE_ankerkuil %>% 
  distinct(soort) %>% 
  filter(str_detect(soort, "haringachtigen|rest", negate = TRUE)) %>% 
  pull())


(soorten_kleur <-
  soorten_fuiken_1 %>% 
  union(soorten_fuiken_2) %>% 
  union(soorten_ankerkuil_1) %>% 
  union(soorten_ankerkuil_2))



relatief_aantal_fuiken <- 
  data_fuiken %>% 
  filter(jaar == 2022) %>% 
  group_by(seizoen, locatie) %>%
  mutate(relatief_aantal = aantal/sum(aantal),
         relatief_gewicht = gewicht/sum(gewicht)) %>% 
  ungroup() %>% 
  group_by(soort) %>% 
  filter(any(relatief_aantal >= prop_lim | relatief_gewicht >= prop_lim)) %>% 
  summarise(aant = max(relatief_aantal),
            gew = max(relatief_gewicht)) %>% 
  ungroup()  %>% 
  group_by(soort) %>% 
  summarise(max_rel = max(aant, gew)) %>% 
  ungroup() %>% 
  arrange(desc(max_rel))

(soorten_fuiken_1 <-
  relatief_aantal_fuiken %>% 
  filter(str_detect(soort, "haringachtigen|rest", negate = TRUE)))


relatieve_aantallen_EMSE_fuiken <- 
  data_fuiken %>% 
  left_join(locatie_scheldezone_fuiken) %>% 
  filter(in_indeling) %>% 
  filter(aantal > 0) %>% 
  group_by(jaar, scheldezone, soort, salgroep, dieet, indeling) %>%
  summarise(aantal_per_fuikdag = mean(aantal_per_fuikdag),
            gewicht_per_fuikdag = mean(gewicht_per_fuikdag)) %>% 
  ungroup() %>% 
  group_by(jaar, scheldezone, salgroep, dieet, indeling) %>%
  mutate(relatief_aantal = aantal_per_fuikdag/sum(aantal_per_fuikdag),
         relatief_gewicht = gewicht_per_fuikdag/sum(gewicht_per_fuikdag)) %>% 
  ungroup() %>% 
  group_by(soort) %>% 
  filter(any(relatief_aantal >= prop_lim | relatief_gewicht >= prop_lim)) %>% 
  summarise(aant = max(relatief_aantal),
            gew = max(relatief_gewicht)) %>% 
  ungroup()  %>% 
  group_by(soort) %>% 
  summarise(max_rel = max(aant, gew)) %>% 
  ungroup() %>% 
  arrange(desc(max_rel))

(soorten_fuiken_2 <-
  relatieve_aantallen_EMSE_fuiken %>% 
  filter(str_detect(soort, "haringachtigen|rest", negate = TRUE)))


relatief_aantal_ankerkuil <- 
  data_ankerkuil %>% 
  filter(jaar == 2022) %>% 
  group_by(seizoen, locatie) %>%
  mutate(relatief_aantal = aantal/sum(aantal),
         relatief_gewicht = gewicht/sum(gewicht)) %>% 
  ungroup() %>% 
  group_by(soort) %>% 
  filter(any(relatief_aantal >= prop_lim | relatief_gewicht >= prop_lim)) %>% 
  summarise(aant = max(relatief_aantal),
            gew = max(relatief_gewicht)) %>% 
  ungroup()  %>% 
  group_by(soort) %>% 
  summarise(max_rel = max(aant, gew)) %>% 
  ungroup() %>% 
  arrange(desc(max_rel))

(soorten_ankerkuil_1 <-
  relatief_aantal_ankerkuil %>% 
  filter(str_detect(soort, "haringachtigen|rest", negate = TRUE)))


relatieve_aantallen_EMSE_ankerkuil <- 
  data_ankerkuil %>% 
  left_join(locatie_scheldezone_ankerkuil) %>% 
  filter(in_indeling) %>% 
  filter(aantal > 0) %>% 
  group_by(jaar, scheldezone, soort, salgroep, dieet, indeling) %>%
  summarise(aantal_per_kub = mean(aantal_per_kub),
            gewicht_per_kub = mean(gewicht_per_kub)) %>% 
  ungroup() %>% 
  group_by(jaar, scheldezone, salgroep, dieet, indeling) %>%
  mutate(relatief_aantal = aantal_per_kub/sum(aantal_per_kub),
         relatief_gewicht = gewicht_per_kub/sum(gewicht_per_kub)) %>% 
  ungroup() %>% 
  group_by(soort) %>% 
  filter(any(relatief_aantal >= prop_lim | relatief_gewicht >= prop_lim)) %>% 
  summarise(aant = max(relatief_aantal),
            gew = max(relatief_gewicht)) %>% 
  ungroup()  %>% 
  group_by(soort) %>% 
  summarise(max_rel = max(aant, gew)) %>% 
  ungroup() %>% 
  arrange(desc(max_rel))

(soorten_ankerkuil_2 <-
  relatieve_aantallen_EMSE_ankerkuil %>% 
  filter(str_detect(soort, "haringachtigen|rest", negate = TRUE)))



(soorten_vis <-
    soorten_vis_fuiken %>% 
    union(soorten_vis_ankerkuil)) 


(soorten_kleur <-
  soorten_fuiken_1 %>% 
  union(soorten_fuiken_2) %>% 
  union(soorten_ankerkuil_1) %>% 
  union(soorten_ankerkuil_2) %>% 
    group_by(soort) %>% 
    summarise(across(everything(), max)) %>% 
    ungroup() %>% 
      arrange(desc(max_rel), soort))


soorten_indeling_kleur <-
  soorten_kleur %>% 
  left_join(soortenlijst %>% 
              filter(soort %in% soorten_kleur$soort) %>% 
              select(soort, salgroep, dieet)) %>% 
  mutate(pos = NA_integer_,
         kleur = NA_character_)

soorten_indeling_n <-
  soorten_indeling_kleur %>% 
  count(salgroep, dieet) %>% 
  arrange(desc(n))

n_kleur <- nrow(soorten_kleur)

save(soorten_indeling_kleur, file = str_c(pad_data, "soorten_kleur.RData"))

```


```{r test kleurcode, eval=FALSE}

relatief_aantal_fuiken <- 
  data_fuiken %>% 
  filter(jaar == 2022) %>% 
  group_by(seizoen, locatie) %>%
  mutate(relatief_aantal = aantal/sum(aantal),
         relatief_gewicht = gewicht/sum(gewicht)) %>% 
  ungroup() %>% 
  group_by(soort) %>% 
  mutate(soort2 = ifelse(any(relatief_aantal >= prop_lim | relatief_gewicht >= prop_lim), soort, "rest")) %>% 
  ungroup() %>% 
  group_by(seizoen, locatie, soort2) %>% 
  summarise(aantal = sum(aantal)) %>% 
  ungroup() %>% 
  group_by(seizoen, locatie) %>% 
  mutate(soort2 = soort2,
         aantal = round(aantal/sum(aantal)*100)) %>% 
  ungroup() %>% 
  rename(soort = soort2) %>% 
  mutate(soort = factor(soort, 
                        levels = unique(soort) %>% 
                          sort() %>% 
                          setdiff("rest") %>% 
                          c(., "rest")),
         locatie = factor(locatie, levels = levels_locatie_fuiken))


# n <- 3
# seq(1,by=n,length.out=n_kleur)%%n_kleur+1
# s <- 3
for(s in 14:25) {

  # set.seed(s)
  # set.seed(45)
  
  # n_rest <- n_kleur
  # n_indeling <- nrow(soorten_indeling_n)
  # serie <- 1:n_rest
  # for (i in 1:n_indeling) {
  #   if (i < n_indeling) { 
  #     # strt <- min(serie)
  #     lng <- soorten_indeling_n[i,]$n
  #     sq <- seq(1, by = n_rest%/%lng, length.out = lng)
  #     sel <- serie[sq]
  #     if (lng > 1)
  #       sel <- sample(sel)
  #     serie <-
  #       setdiff(serie, sel)
  #     n_rest <- length(serie)
  #   } else {
  #     sel <- serie
  #   }
  #   soorten_indeling_kleur[soorten_indeling_kleur$salgroep == soorten_indeling_n[i, ]$salgroep & 
  #                            soorten_indeling_kleur$dieet == soorten_indeling_n[i,]$dieet, "pos"] <- sel
  #   print(sel)
  # }
  
  # s <- 14
  
  
  sq <- seq(1,by=s,length.out=n_kleur)%%(n_kleur+1)
  lm <- 52-((s-1)%%(s))
  sq[sq<=lm] <- sq[sq<=lm] + 1
  # sort(sq)
  
  soorten_indeling_kleur$pos <- sq
  
  
  soorten_indeling_kleur$kleur <- 
    wes_palette("Darjeeling1", 
                type = "continuous", 
                n = n_kleur) %>% 
    unname() %>% 
    .[soorten_indeling_kleur$pos]
  
  
  # my_pal_wes <- 
  #   c(wes_palette("Darjeeling1", 
  #                 type = "continuous", 
  #                 n = length(soorten_kleur)) %>% 
  #       unname() %>%
  #       sample(), 
  #     "azure",
  #     "darkslategrey")
  # names(my_pal_wes) <-
  #   c(soorten_kleur, "haringachtigen", "rest")

  
  my_pal_wes <-
    c(soorten_indeling_kleur$kleur, 
      "azure",
      "darkslategrey")
  names(my_pal_wes) <-
    c(soorten_indeling_kleur$soort, "haringachtigen", "rest")
    
  the_pal <- 
    my_pal_wes[names(my_pal_wes) %in% unique(relatief_aantal_fuiken$soort)]
  
  pl <-
    relatief_aantal_fuiken %>% 
    mutate(aantal = if_else(aantal == 0, NA_real_, aantal)) %>% 
    ggplot(aes(x ="", y = aantal, fill = soort)) +
    geom_col(position = "fill") +
    # geom_text(aes(label = soort),
    #            size = 3) +
    geom_text(aes(label = aantal, size = aantal),
              position = position_fill(vjust = 0.5),
              show.legend = FALSE) +
    coord_polar("y", start=0) +
    facet_grid(locatie ~ seizoen) +
    labs(title = str_c("seed = ", s),
         x = NULL,
         y = NULL) +
    scale_x_discrete(breaks = NULL) +
    scale_y_continuous(breaks = NULL) +
    scale_fill_manual(values = the_pal) +
    theme(
      # legend.position = "bottom",
      legend.title = element_blank())
  print(pl)
  
}


for(s in 76) {

  set.seed(s)
  
  my_pal_wes <- 
    c(wes_palette("Darjeeling1", 
                  type = "continuous", 
                  n = length(soorten_kleur)) %>% 
        unname() %>%
        sample(), 
      "azure",
      "darkslategrey")
  names(my_pal_wes) <-
    c(soorten_kleur, "haringachtigen", "rest")
  
  the_pal <- 
    my_pal_wes[names(my_pal_wes) %in% unique(relatief_aantal_ankerkuil$soort)]
  
  pl <-
    relatief_aantal_ankerkuil %>% 
    mutate(aantal = if_else(aantal == 0, NA_real_, aantal)) %>% 
    ggplot(aes(x ="", y = aantal, fill = soort)) +
    geom_col(position = "fill") +
    # geom_text(aes(label = soort),
    #            size = 3) +
    geom_text(aes(label = aantal, size = aantal),
              position = position_fill(vjust = 0.5),
              show.legend = FALSE) +
    coord_polar("y", start=0) +
    facet_grid(locatie ~ seizoen) +
    labs(title = str_c("seed = ", s),
         x = NULL,
         y = NULL) +
    scale_x_discrete(breaks = NULL) +
    scale_y_continuous(breaks = NULL) +
    scale_fill_manual(values = the_pal) +
    theme(
      # legend.position = "bottom",
      legend.title = element_blank())
  print(pl)
  
}

```

