---
params:
  hoofdstuk: "070_macrozoobenthos"
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile,
                          encoding=encoding,
                          output_dir = {
                            source("../pad.R");
                            maak_pad(rmarkdown::yaml_front_matter(inputFile)$params$hoofdstuk, "output")
                          }
                          )})
title: "Macrozoöbenthos analyse"
output:
  bookdown::word_document2
  ---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, error=FALSE, warning=FALSE, message=FALSE, cache=FALSE)

```


```{r libraries}

library(tidyverse)
library(readxl)
library(writexl)
library(ggpubr)
library(INBOtheme)
library(rprojroot)
library(lubridate)

```


```{r pad}

# inlezen van variabelen
# pad naar data : pad_data
# pad naar tabellen : pad_tabellen
# pad naar figuren : pad_figuren

source("../pad.R")
#source(find_root_file("../pad.R", criterion = is_rstudio_project))

pad_data <- maak_pad(params$hoofdstuk, "data")
pad_figuren <- maak_pad(params$hoofdstuk, "figuren")
pad_tabellen <- maak_pad(params$hoofdstuk, "tabellen")

source("G:/.shortcut-targets-by-id/0B0xcP-eNvJ9dZDBwVVJOVk5Ld2s/PRJ_SCHELDE/VNSC/Rapportage_INBO/2022/Function_CalculateShannonIndex.R")
```


```{r data}

data_macrobenthos <- 
  read_excel(paste0(pad_data, "macrobenthos_data_2008_2020.xlsx")) %>% 
  mutate(tidaal = recode(tidaal, "sub" = "subtidaal", "Intertidaal" = "intertidaal", "inter" = "intertidaal"),
         tidaal = factor(tidaal, 
                         levels = c("subtidaal", "intertidaal"))) %>% 
  dplyr::mutate(niveau3_hybr = recode(waterloop2, "Zeeschelde IV"= "Saliniteitsgradient", "Zeeschelde III"= "Oligohalien", "Zeeschelde II"= "Zoet lang verblijf", "Zeeschelde I"= "Zoet kort verblijf")) %>% 
  dplyr::mutate(fysiotoop = case_when(
    fysiotoop %in% c("diep subtidaal") ~ "diep subtidaal",
    fysiotoop %in% c("matig diep subtidaal") ~ "matig diep subtidaal",
    fysiotoop %in% c("ondiep subtidaal") ~ "ondiep subtidaal",
    fysiotoop %in% c("subtidaal", "nog te bepalen - sub", "nog te bepalen - subtidaal") ~ "subtidaal indet.",
    fysiotoop %in% c("lage slikzone", "laag slik", "laag intertidaal (75-100%)") ~ "laag intertidaal",
    fysiotoop %in% c("middelhoge slikzone", "hoge slikzone", "hoog intertidaal (0-25%)", "middelhoog slik", "middelhoog/hoog slik", "midden intertidaal (25-75%)") ~ "middelhoog/hoog intertidaal",
    fysiotoop %in% c("hard substraat", "hard antropogeen") ~ "hard substraat",
    fysiotoop %in% c("nog te bepalen - inter", "onbepaald", "slik", "slik onbepaald") ~ "intertidaal indet.",
    TRUE ~ fysiotoop)) %>% 
  dplyr::mutate(densiteit = if_else(soort != "geen" & densiteit == 0, 628, densiteit)) ## probleem van soorten waarvoor densiteit = 0, wrsch doordat geen hele ex gevonden zijn of invoerfouten. Dit geeft probleem oa bij Shannon index dus hier waarden invullen met laagste waarde. Om toch onderscheid te maken met die soorten waarvoor wel een 1 genoteerd werd wordt 628 gebruikt (cijfers na de komma niet, wel bij andere cf opp van steekbuis)





vroegste_jaar <-
  data_macrobenthos %>% 
  pull(jaar) %>% 
  min()

laatste_jaar <-
  data_macrobenthos %>% 
  pull(jaar) %>% 
  max()

zeeschelde_order <-
  c("Zeeschelde IV", "Zeeschelde III", "Zeeschelde II", "Zeeschelde I")

zeeschelde_order2022 <- c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf")
zeeschelde_order2022tot <- c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf", "Zeeschelde_totaal")

zijrivieren_order <-
  c("Rupel", "Durme", "Nete", "Dijle", "Zenne")
waterlopen_order <-
  c(zeeschelde_order, zijrivieren_order)

waterlopen_order2022 <-
   c(zeeschelde_order2022, zijrivieren_order)
fysiotoop_order <-
  c("diep subtidaal", "matig diep subtidaal", "ondiep subtidaal", "laag intertidaal", "middelhoog/hoog intertidaal", "hard substraat")

```


```{r totaal-over-soorten}

data_macrobenthos_totaal <-
  data_macrobenthos %>% 
  dplyr::group_by(jaar, waterlichaam, waterloop, niveau3_hybr, systeem, tidaal, fysiotoop, locatie) %>% 
  dplyr::summarise_at(vars(densiteit, biomassa), ~sum(.,na.rm=TRUE)) %>% 
  ungroup()

biom_min <- 
  min(data_macrobenthos_totaal$biomassa[!is.na(data_macrobenthos_totaal$biomassa) & data_macrobenthos_totaal$biomassa > 0])

data_macrobenthos_totaal %>% 
  dplyr::distinct(tidaal, fysiotoop) %>% 
  arrange(tidaal, fysiotoop)

data_macrobenthos_totaal %>% 
  dplyr::filter(jaar == laatste_jaar) %>% 
  dplyr::distinct(tidaal, fysiotoop) %>% 
  dplyr::arrange(tidaal, fysiotoop)

```

```{r 070-tabel-staalnamelocaties}

tabel_staalnamelocaties <-
  data_macrobenthos_totaal %>% 
  dplyr::filter(jaar == laatste_jaar) %>% 
  dplyr::count(waterloop = niveau3_hybr, fysiotoop) %>% 
  pivot_wider(names_from = fysiotoop, 
              values_from = n,
              values_fill = list(n = 0)) %>% 
  dplyr::select(waterloop, `laag intertidaal`, `middelhoog/hoog intertidaal`, `diep subtidaal`, `matig diep subtidaal`, `ondiep subtidaal`, `subtidaal indet.`, `hard substraat`)

aantal_stalen <- tabel_staalnamelocaties %>%
  dplyr::select(-waterloop) %>% 
  dplyr::summarise(aantal = sum(.)) 
n_staal <- aantal_stalen$aantal

write_xlsx(list(staalnamelocaties = tabel_staalnamelocaties),
           path = paste0(pad_tabellen, "070_Macrobenthos_tabellen.xlsx"))

```


```{r per-waterloop-en-tidaal}

data_macrobenthos_tidaal <-
  data_macrobenthos_totaal %>% 
  group_by(jaar, waterlichaam, niveau3_hybr, systeem, tidaal) %>% 
  summarise_at(vars(densiteit, biomassa), 
               list(mean = ~max(0, mean(., na.rm = TRUE)),
                    med = ~max(0, median(., na.rm = TRUE)),
                    lwr1 = ~max(0, quantile(., 0.25, na.rm = TRUE)),
                    upr1 = ~max(0, quantile(., 0.75, na.rm = TRUE)),
                    lwr2 = ~max(0, quantile(., 0.05, na.rm = TRUE)),
                    upr2 = ~max(0, quantile(., 0.95, na.rm = TRUE)))) %>% 
  ungroup()

```


```{r 070-figuur-densiteit-waterlichaam, fig.height=8, fig.width=8}

xlb <- "waterloop"
ylb <- expression(paste("densiteit ", (ind/m^2)))

fnt <- 8

bxp_ZS <- 
  data_macrobenthos_totaal %>% 
  dplyr::filter(niveau3_hybr %in% c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf")) %>%
  dplyr::mutate(jaar = ordered(jaar),
         niveau3_hybr = factor(niveau3_hybr,
                             levels = c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf")),
         densiteit = densiteit + 1) %>% 
  ggplot(aes(niveau3_hybr, densiteit, fill = jaar)) +
  geom_boxplot() +
  ggsci::scale_fill_simpsons() +
  scale_y_log10(breaks = c(0,10,1000,100000)+1, labels = c(0,10,1000,100000)) +
  labs(x = xlb,
       y = ylb) +
  facet_wrap(~tidaal)
# bxp_ZS

bxp_ZR <- data_macrobenthos_totaal %>% 
  filter(niveau3_hybr %in% c("Rupel", "Durme", "Nete", "Dijle", "Zenne")) %>%
  mutate(jaar = ordered(jaar),
         niveau3_hybr = factor(niveau3_hybr,
                             levels = c("Rupel", "Durme", "Nete", "Dijle", "Zenne")),
         densiteit = densiteit + 1) %>% 
  ggplot(aes(niveau3_hybr, densiteit, fill = jaar)) +
  geom_boxplot() +
  ggsci::scale_fill_simpsons() +
  scale_y_log10(breaks = c(0,10,1000,100000)+1, labels = c(0,10,1000,100000)) +
  labs(x = xlb,
       y = ylb) +
  facet_wrap(~tidaal)
# bxp_ZR

ggarrange(bxp_ZS + rremove("xlab") + font("xy.text", size = fnt), 
          bxp_ZR + rremove("xlab") + font("xy.text", size = fnt), 
          nrow = 2,
          common.legend = TRUE)

ggsave(paste0(pad_figuren, "070-figuur-densiteit-waterlichaam.jpg"))

```


```{r 070-figuur-densiteit-Zeeschelde}

xlb <- "waterloop"
ylb <- expression(paste("densiteit ", (g/m^2)))

fnt <- 8

data_macrobenthos_totaal %>% 
  filter(niveau3_hybr %in% c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf", "Durme", "Rupel")) %>%
  mutate(jaar = ordered(jaar),
         niveau3_hybr = factor(niveau3_hybr,
                             levels = c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf", "Durme", "Rupel")),
         densiteit = densiteit + 1) %>% 
  ggplot(aes(niveau3_hybr, densiteit, fill = jaar)) +
  geom_boxplot() +
  ggsci::scale_fill_simpsons() +
  scale_y_log10(breaks = c(0,10,1000,100000)+1, labels = c(0,10,1000,100000)) +
  labs(x = xlb,
       y = ylb) + 
  theme(axis.text.x = element_text(angle = 350))+
  facet_wrap(~tidaal, ncol = 1)

ggsave(paste0(pad_figuren, "070-figuur-densiteit-Zeeschelde.jpg"), height=6, width=8)

```


```{r 070-figuur-densiteit-mediaan-waterlichaam-alternatief}

xlb <- "jaar"
ylb <- expression(paste("densiteit ", (ind/m^2)))

fnt <- 8

bxp_ZS <- 
  data_macrobenthos_tidaal %>% 
  dplyr::filter(niveau3_hybr %in% c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf")) %>%
  dplyr::mutate(niveau3_hybr = factor(niveau3_hybr,
                             levels = c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf")),
         densiteit_med = densiteit_med + 1,
         densiteit_lwr1 = densiteit_lwr1 + 1,
         densiteit_upr1 = densiteit_upr1 + 1,
         densiteit_lwr2 = densiteit_lwr2 + 1,
         densiteit_upr1 = densiteit_upr2 + 1) %>% 
  ggplot(aes(jaar, densiteit_med)) +
  geom_line() +
  geom_ribbon(aes(ymin = densiteit_lwr1, ymax = densiteit_upr1), alpha = 0.2) +
  # geom_ribbon(aes(ymin = densiteit_lwr2, ymax = densiteit_upr2), alpha = 0.2) +
  # scale_x_continuous(breaks = vroegste_jaar:laatste_jaar) +
  scale_x_continuous(breaks = seq(if_else((laatste_jaar-vroegste_jaar)%%2 == 0, vroegste_jaar, vroegste_jaar+1), laatste_jaar, 2)) +
  scale_y_log10(breaks = c(0,10,1000,100000)+1, labels = c(0,10,1000,100000)) +
  labs(x = xlb,
       y = ylb) +
  facet_grid(tidaal~niveau3_hybr) +
  theme(axis.text.x = element_text(angle = 45))
bxp_ZS

# ggsave(paste0(pad_figuren, "070-figuur-densiteit-Zeeschelde-alternatief.jpg"), height=4, width=8)


bxp_ZR <- 
  data_macrobenthos_tidaal %>% 
  filter(niveau3_hybr %in% c("Rupel", "Durme", "Nete", "Dijle", "Zenne")) %>%
  mutate(niveau3_hybr = factor(niveau3_hybr,
                             levels = c("Rupel", "Durme", "Nete", "Dijle", "Zenne")),
         densiteit_med = densiteit_med + 1,
         densiteit_lwr1 = densiteit_lwr1 + 1,
         densiteit_upr1 = densiteit_upr1 + 1,
         densiteit_lwr2 = densiteit_lwr2 + 1,
         densiteit_upr1 = densiteit_upr2 + 1) %>% 
  ggplot(aes(jaar, densiteit_med)) +
  geom_line() +
  geom_ribbon(aes(ymin = densiteit_lwr1, ymax = densiteit_upr1), alpha = 0.2) +
  # geom_ribbon(aes(ymin = densiteit_lwr2, ymax = densiteit_upr2), alpha = 0.2) +
  scale_x_continuous(breaks = seq(if_else((laatste_jaar-vroegste_jaar)%%2 == 0, vroegste_jaar, vroegste_jaar+1), laatste_jaar, 2)) +
  scale_y_log10(breaks = c(0,10,1000,100000)+1, labels = c(0,10,1000,100000)) +
  labs(x = xlb,
       y = ylb) +
  facet_grid(tidaal~niveau3_hybr) +
  theme(axis.text.x = element_text(angle = 45))
bxp_ZR

ggarrange(bxp_ZS + font("xy.text", size = fnt), 
          bxp_ZR + font("xy.text", size = fnt), 
          nrow = 2,
          common.legend = TRUE)

ggsave(paste0(pad_figuren, "070-figuur-densiteit-waterlichaam-mediaan_alternatief.jpg"), height=8, width=8)

```


```{r 070-figuur-densiteit-gemiddelde-waterlichaam-alternatief}

xlb <- "jaar"
ylb <- expression(paste("densiteit ", (ind/m^2)))

fnt <- 8

bxp_ZS <- 
  data_macrobenthos_tidaal %>% 
  filter(niveau3_hybr %in% c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf")) %>%
  mutate(niveau3_hybr = factor(niveau3_hybr,
                             levels = c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf")),
         densiteit_mean = densiteit_mean + 1,
         densiteit_lwr1 = densiteit_lwr1 + 1,
         densiteit_upr1 = densiteit_upr1 + 1,
         densiteit_lwr2 = densiteit_lwr2 + 1,
         densiteit_upr1 = densiteit_upr2 + 1) %>% 
  ggplot(aes(jaar, densiteit_mean)) +
  geom_line() +
  geom_ribbon(aes(ymin = densiteit_lwr1, ymax = densiteit_upr1), alpha = 0.2) +
  # geom_ribbon(aes(ymin = densiteit_lwr2, ymax = densiteit_upr2), alpha = 0.2) +
  # scale_x_continuous(breaks = vroegste_jaar:laatste_jaar) +
  scale_x_continuous(breaks = seq(if_else((laatste_jaar-vroegste_jaar)%%2 == 0, vroegste_jaar, vroegste_jaar+1), laatste_jaar, 2)) +
  scale_y_log10(breaks = c(0,10,1000,100000)+1, labels = c(0,10,1000,100000)) +
  labs(x = xlb,
       y = ylb) +
  facet_grid(tidaal~niveau3_hybr) +
  theme(axis.text.x = element_text(angle = 45))
bxp_ZR
bxp_ZS

# ggsave(paste0(pad_figuren, "070-figuur-densiteit-Zeeschelde-alternatief.jpg"), height=4, width=8)


bxp_ZR <- 
  data_macrobenthos_tidaal %>% 
  filter(niveau3_hybr %in% c("Rupel", "Durme", "Nete", "Dijle", "Zenne")) %>%
  mutate(niveau3_hybr = factor(niveau3_hybr,
                             levels = c("Rupel", "Durme", "Nete", "Dijle", "Zenne")),
         densiteit_mean = densiteit_mean + 1,
         densiteit_lwr1 = densiteit_lwr1 + 1,
         densiteit_upr1 = densiteit_upr1 + 1,
         densiteit_lwr2 = densiteit_lwr2 + 1,
         densiteit_upr1 = densiteit_upr2 + 1) %>% 
  ggplot(aes(jaar, densiteit_mean)) +
  geom_line() +
  geom_ribbon(aes(ymin = densiteit_lwr1, ymax = densiteit_upr1), alpha = 0.2) +
  # geom_ribbon(aes(ymin = densiteit_lwr2, ymax = densiteit_upr2), alpha = 0.2) +
  scale_x_continuous(breaks = seq(if_else((laatste_jaar-vroegste_jaar)%%2 == 0, vroegste_jaar, vroegste_jaar+1), laatste_jaar, 2)) +
  scale_y_log10(breaks = c(0,10,1000,100000)+1, labels = c(0,10,1000,100000)) +
  labs(x = xlb,
       y = ylb) +
  facet_grid(tidaal~niveau3_hybr) +
  theme(axis.text.x = element_text(angle = 45))
bxp_ZR

ggarrange(bxp_ZS + font("xy.text", size = fnt), 
          bxp_ZR + font("xy.text", size = fnt), 
          nrow = 2,
          common.legend = TRUE)

ggsave(paste0(pad_figuren, "070-figuur-densiteitgemiddelde.png"), height=8, width=8)

```


```{r 070-figuur-densiteit-Zeeschelde-alternatief}

xlb <- "jaar"
ylb <- expression(paste("densiteit ", (ind/m^2)))

data_macrobenthos_tidaal %>% 
  filter(niveau3_hybr %in% c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf", "Durme", "Rupel")) %>%
  mutate(niveau3_hybr = factor(niveau3_hybr,
                             levels = c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf", "Durme", "Rupel")),
         densiteit_med = densiteit_med + 1,
         densiteit_lwr1 = densiteit_lwr1 + 1,
         densiteit_upr1 = densiteit_upr1 + 1,
         densiteit_lwr2 = densiteit_lwr2 + 1,
         densiteit_upr1 = densiteit_upr2 + 1) %>% 
  ggplot(aes(jaar, densiteit_med)) +
  geom_line() +
  geom_ribbon(aes(ymin = densiteit_lwr1, ymax = densiteit_upr1), alpha = 0.2) +
  # geom_ribbon(aes(ymin = densiteit_lwr2, ymax = densiteit_upr2), alpha = 0.2) +
  # scale_x_continuous(breaks = vroegste_jaar:laatste_jaar) +
  scale_x_continuous(breaks = seq(if_else((laatste_jaar-vroegste_jaar)%%2 == 0, vroegste_jaar, vroegste_jaar+1), laatste_jaar, 2)) +
  scale_y_log10(breaks = c(0,10,1000,100000)+1, labels = c(0,10,1000,100000)) +
  labs(x = xlb,
       y = ylb) +
  facet_grid(niveau3_hybr~tidaal) +
  theme(axis.text.x = element_text(angle = 45))

ggsave(paste0(pad_figuren, "070-figuur-densiteit-Zeeschelde-alternatief.jpg"), height=8, width=6)


```


```{r 070-figuur-biomassa-waterlichaam, fig.height=8, fig.width=8}

xlb <- "waterloop"
ylb <- expression(paste("biomassa ", (g/m^2)))

fnt <- 8

bxp_ZS <- 
  data_macrobenthos_totaal %>% 
  filter(niveau3_hybr %in% c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf")) %>%
  mutate(jaar = ordered(jaar),
         niveau3_hybr = factor(niveau3_hybr,
                             levels = c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf")),
         biomassa = biomassa + biom_min) %>% 
  ggplot(aes(niveau3_hybr, biomassa, fill = jaar)) +
  geom_boxplot() +
  ggsci::scale_fill_simpsons() +
  scale_y_log10(breaks = c(0,0.1,1,10,100,1000)+biom_min, labels = c(0,0.1,1,10,100,1000)) +
  labs(x = xlb,
       y = ylb) +
  facet_wrap(~tidaal)
# bxp_ZS

bxp_ZR <- data_macrobenthos_totaal %>% 
  filter(niveau3_hybr %in% c("Rupel", "Durme", "Nete", "Dijle", "Zenne")) %>%
  mutate(jaar = ordered(jaar),
         niveau3_hybr = factor(niveau3_hybr,
                             levels = c("Rupel", "Durme", "Nete", "Dijle", "Zenne")),
         biomassa = biomassa + biom_min) %>% 
  ggplot(aes(niveau3_hybr, biomassa, fill = jaar)) +
  geom_boxplot() +
  ggsci::scale_fill_simpsons() +
  scale_y_log10(breaks = c(0,0.1,1,10,100,1000)+biom_min, labels = c(0,0.1,1,10,100,1000)) +
  labs(x = xlb,
       y = ylb) +
  facet_wrap(~tidaal)
# bxp_ZR

ggarrange(bxp_ZS + rremove("xlab") + font("xy.text", size = fnt), 
          bxp_ZR + rremove("xlab") + font("xy.text", size = fnt), 
          nrow = 2,
          common.legend = TRUE)

ggsave(paste0(pad_figuren, "070-figuur-biomassa-waterlichaam.jpg"))

```


```{r 070-figuur-biomassa-Zeeschelde}

xlb <- "waterloop"
ylb <- expression(paste("biomassa ", (g/m^2)))

fnt <- 8

data_macrobenthos_totaal %>% 
  filter(niveau3_hybr %in% c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf", "Durme", "Rupel")) %>%
  mutate(jaar = ordered(jaar),
         niveau3_hybr = factor(niveau3_hybr,
                             levels = c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf", "Durme", "Rupel")),
         biomassa = biomassa + biom_min) %>% 
  ggplot(aes(niveau3_hybr, biomassa, fill = jaar)) +
  geom_boxplot() +
  ggsci::scale_fill_simpsons() +
  scale_y_log10(breaks = c(0,0.1,1,10,100,1000)+biom_min, labels = c(0,0.1,1,10,100,1000)) +
  labs(x = xlb,
       y = ylb) +
  facet_wrap(~tidaal, ncol = 1)

ggsave(paste0(pad_figuren, "070-figuur-biomassa-Zeeschelde.jpg"), height=6, width=8)

```


```{r 070-figuur-biomassa-waterlichaam-alternatief}

xlb <- "jaar"
ylb <- expression(paste("biomassa ", (g/m^2)))

fnt <- 8

bxp_ZS <- 
  data_macrobenthos_tidaal %>% 
  filter(niveau3_hybr %in% c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf")) %>%
  mutate(niveau3_hybr = factor(niveau3_hybr,
                             levels = c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf")),
         biomassa_med = biomassa_med + biom_min,
         biomassa_lwr1 = biomassa_lwr1 + biom_min,
         biomassa_upr1 = biomassa_upr1 + biom_min,
         biomassa_lwr2 = biomassa_lwr2 + biom_min,
         biomassa_upr1 = biomassa_upr2 + biom_min) %>% 
  ggplot(aes(jaar, biomassa_med)) +
  geom_line() +
  geom_ribbon(aes(ymin = biomassa_lwr1, ymax = biomassa_upr1), alpha = 0.2) +
  # geom_ribbon(aes(ymin = biomassa_lwr2, ymax = biomassa_upr2), alpha = 0.2) +
  # scale_x_continuous(breaks = vroegste_jaar:laatste_jaar) +
  scale_x_continuous(breaks = seq(if_else((laatste_jaar-vroegste_jaar)%%2 == 0, vroegste_jaar, vroegste_jaar+1), laatste_jaar, 2)) +
  scale_y_log10(breaks = c(0,0.1,1,10,100,1000)+biom_min, labels = c(0,0.1,1,10,100,1000)) +
  labs(x = xlb,
       y = ylb)+
  facet_grid(tidaal~niveau3_hybr) +
  theme(axis.text.x = element_text(angle = 45))
bxp_ZS

# ggsave(paste0(pad_figuren, "070-figuur-biomassa-Zeeschelde-alternatief.jpg"), height=4, width=8)


bxp_ZR <- 
  data_macrobenthos_tidaal %>% 
  filter(niveau3_hybr %in% c("Rupel", "Durme", "Nete", "Dijle", "Zenne")) %>%
  mutate(niveau3_hybr = factor(niveau3_hybr,
                             levels = c("Rupel", "Durme", "Nete", "Dijle", "Zenne")),
         biomassa_med = biomassa_med + biom_min,
         biomassa_lwr1 = biomassa_lwr1 + biom_min,
         biomassa_upr1 = biomassa_upr1 + biom_min,
         biomassa_lwr2 = biomassa_lwr2 + biom_min,
         biomassa_upr1 = biomassa_upr2 + biom_min) %>% 
  ggplot(aes(jaar, biomassa_med)) +
  geom_line() +
  geom_ribbon(aes(ymin = biomassa_lwr1, ymax = biomassa_upr1), alpha = 0.2) +
  # geom_ribbon(aes(ymin = biomassa_lwr2, ymax = biomassa_upr2), alpha = 0.2) +
  scale_x_continuous(breaks = seq(if_else((laatste_jaar-vroegste_jaar)%%2 == 0, vroegste_jaar, vroegste_jaar+1), laatste_jaar, 2)) +
  scale_y_log10(breaks = c(0,0.1,1,10,100,1000)+biom_min, labels = c(0,0.1,1,10,100,1000)) +
  labs(x = xlb,
       y = ylb) +
  facet_grid(tidaal~niveau3_hybr) +
  theme(axis.text.x = element_text(angle = 45))
bxp_ZR

ggarrange(bxp_ZS + font("xy.text", size = fnt), 
          bxp_ZR + font("xy.text", size = fnt), 
          nrow = 2,
          common.legend = TRUE)

ggsave(paste0(pad_figuren, "070-figuur-biomassa-waterlichaammediaan-alternatief.jpg"), height=8, width=8)

```

```{r 070-figuur-biomassagemiddelde-waterlichaam-alternatief}

xlb <- "jaar"
ylb <- expression(paste("biomassa ", (g/m^2)))

fnt <- 8

bxp_ZS <- 
  data_macrobenthos_tidaal %>% 
  filter(niveau3_hybr %in% c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf")) %>%
  mutate(niveau3_hybr = factor(niveau3_hybr,
                             levels = c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf")),
         biomassa_mean = biomassa_mean + biom_min,
         biomassa_lwr1 = biomassa_lwr1 + biom_min,
         biomassa_upr1 = biomassa_upr1 + biom_min,
         biomassa_lwr2 = biomassa_lwr2 + biom_min,
         biomassa_upr1 = biomassa_upr2 + biom_min) %>% 
  ggplot(aes(jaar, biomassa_mean)) +
  geom_line() +
  geom_ribbon(aes(ymin = biomassa_lwr1, ymax = biomassa_upr1), alpha = 0.2) +
  # geom_ribbon(aes(ymin = biomassa_lwr2, ymax = biomassa_upr2), alpha = 0.2) +
  # scale_x_continuous(breaks = vroegste_jaar:laatste_jaar) +
  scale_x_continuous(breaks = seq(if_else((laatste_jaar-vroegste_jaar)%%2 == 0, vroegste_jaar, vroegste_jaar+1), laatste_jaar, 2)) +
  # scale_y_log10(breaks = c(0,0.1,1,10,100,1000)+biom_min, labels = c(0,0.1,1,10,100,1000)) +
  ylim(0,50)+
  labs(x = xlb,
       y = ylb) +
  facet_grid(tidaal~niveau3_hybr) +
  theme(axis.text.x = element_text(angle = 45))
bxp_ZS

# ggsave(paste0(pad_figuren, "070-figuur-biomassa-Zeeschelde-alternatief.jpg"), height=4, width=8)


bxp_ZR <- 
  data_macrobenthos_tidaal %>% 
  filter(niveau3_hybr %in% c("Rupel", "Durme", "Nete", "Dijle", "Zenne")) %>%
  mutate(niveau3_hybr = factor(niveau3_hybr,
                             levels = c("Rupel", "Durme", "Nete", "Dijle", "Zenne")),
         biomassa_mean = biomassa_mean + biom_min,
         biomassa_lwr1 = biomassa_lwr1 + biom_min,
         biomassa_upr1 = biomassa_upr1 + biom_min,
         biomassa_lwr2 = biomassa_lwr2 + biom_min,
         biomassa_upr1 = biomassa_upr2 + biom_min) %>% 
  ggplot(aes(jaar, biomassa_mean)) +
  geom_line() +
  geom_ribbon(aes(ymin = biomassa_lwr1, ymax = biomassa_upr1), alpha = 0.2) +
  # geom_ribbon(aes(ymin = biomassa_lwr2, ymax = biomassa_upr2), alpha = 0.2) +
  scale_x_continuous(breaks = seq(if_else((laatste_jaar-vroegste_jaar)%%2 == 0, vroegste_jaar, vroegste_jaar+1), laatste_jaar, 2)) +
  # scale_y_log10(breaks = c(0,0.1,1,10,100,1000)+biom_min, labels = c(0,0.1,1,10,100,1000)) +
  ylim(0,50)+
  labs(x = xlb,
       y = ylb) +
  facet_grid(tidaal~niveau3_hybr) +
  theme(axis.text.x = element_text(angle = 45))
bxp_ZR

ggarrange(bxp_ZS + font("xy.text", size = fnt), 
          bxp_ZR + font("xy.text", size = fnt), 
          nrow = 2,
          common.legend = TRUE)

ggsave(paste0(pad_figuren, "070-figuur-biomassagemiddelde-waterlichaam-alternatief.jpg"), height=8, width=8)

```

```{r 070-figuur-biomassa-Zeeschelde-alternatief}

xlb <- "jaar"
ylb <- expression(paste("biomassa ", (g/m^2)))

data_macrobenthos_tidaal %>% 
  filter(niveau3_hybr %in% c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf", "Durme", "Rupel")) %>%
  mutate(niveau3_hybr = factor(niveau3_hybr,
                             levels = c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf", "Durme", "Rupel")),
         biomassa_med = biomassa_med + biom_min,
         biomassa_lwr1 = biomassa_lwr1 + biom_min,
         biomassa_upr1 = biomassa_upr1 + biom_min,
         biomassa_lwr2 = biomassa_lwr2 + biom_min,
         biomassa_upr1 = biomassa_upr2 + biom_min) %>% 
  ggplot(aes(jaar, biomassa_med)) +
  geom_line() +
  geom_ribbon(aes(ymin = biomassa_lwr1, ymax = biomassa_upr1), alpha = 0.2) +
  # geom_ribbon(aes(ymin = biomassa_lwr2, ymax = biomassa_upr2), alpha = 0.2) +
  # scale_x_continuous(breaks = vroegste_jaar:laatste_jaar) +
  scale_x_continuous(breaks = seq(if_else((laatste_jaar-vroegste_jaar)%%2 == 0, vroegste_jaar, vroegste_jaar+1), laatste_jaar, 2)) +
  scale_y_log10(breaks = c(0,0.1,1,10,100,1000)+biom_min, labels = c(0,0.1,1,10,100,1000)) +
  labs(x = xlb,
       y = ylb) +
  facet_grid(niveau3_hybr~tidaal) +
  theme(axis.text.x = element_text(angle = 45))

ggsave(paste0(pad_figuren, "070-figuur-biomassa-Zeeschelde-alternatief.jpg"), height=8, width=6)

```


```{r 070-figuur-aandeel-legel-stalen}

data_macrobenthos_totaal %>% 
  group_by(jaar, waterloop = niveau3_hybr, systeem) %>% 
  summarise(leeg = sum(densiteit == 0 & biomassa == 0, na.rm = TRUE),
            totaal = n(),
            leeg_perc = leeg/totaal*100) %>% 
  ungroup() %>% 
  mutate(waterloop = factor(waterloop, levels = waterlopen_order2022)) %>% 
  ggplot(aes(jaar, leeg_perc, color = waterloop)) +
  geom_line(aes(linetype = systeem), size = 1) +
  geom_point(aes(shape = systeem), size = 3) +
  scale_x_continuous(breaks = seq(if_else((laatste_jaar-vroegste_jaar)%%2 == 0, vroegste_jaar, vroegste_jaar+1), laatste_jaar, 2)) +
  scale_y_continuous(breaks = seq(0,50,10), labels = paste0(seq(0,50,10), "%")) +
  labs(y = "aandeel lege stalen")

ggsave(paste0(pad_figuren, "070-figuur-aandeel-lege-stalen.jpg"), height=5, width=8)

unique(data_macrobenthos_totaal$niveau3_hybr)

```


```{r 070-figuur-soortenrijkdom-Zeeschelde}

data_macrobenthos %>% 
  filter(#waterloop2 == "Zeeschelde I",
         fysiotoop %in% fysiotoop_order,
         fysiotoop != "hard substraat") %>% 
  mutate(is_soort = if_else(soort == "geen", 0, 1)) %>% 
  group_by(jaar, tidaal, locatie, niveau3_hybr) %>% 
  summarise(n = sum(is_soort)) %>% 
  ungroup() %>% 
  mutate(jaar = ordered(jaar), 
         niveau3_hybr = factor(niveau3_hybr, levels = waterlopen_order2022)) %>% 
  ggplot(aes(tidaal, n, fill = jaar)) +
  geom_boxplot() +
  ggsci::scale_fill_simpsons() +
  labs(y = "aantal soorten")+
  labs(x = "")+
  facet_wrap(~niveau3_hybr)

ggsave(paste0(pad_figuren, "070-figuur-soortenrijkdom-Zeeschelde.jpg"), height=5, width=8)
waterlopen_order

data_macrobenthos %>%
  select(!c(locatie, densiteit, biomassa)) %>% 
  filter(fysiotoop %in% fysiotoop_order,
         fysiotoop != "hard substraat") %>% 
  mutate(is_soort = if_else(soort == "geen", 0, 1)) %>%
  distinct() %>% 
  group_by(jaar, tidaal, niveau3_hybr) %>% 
  summarise(n = sum(is_soort)) %>% 
  ungroup() %>% 
  mutate(jaar = ordered(jaar), 
         niveau3_hybr = factor(niveau3_hybr, levels = waterlopen_order2022)) %>% 
  ggplot(aes(x=jaar,y = n, fill = tidaal)) +
  ylab("aantal taxa") +
  geom_line(aes(colour = tidaal, group = tidaal)) +
  theme(axis.text.x = element_text(angle = 90))+
  facet_wrap(~niveau3_hybr)
ggsave(paste0(pad_figuren, "070-figuur-soortenrijkdom-lijn-Zeeschelde.jpg"), height=5, width=8)


```
```{r 070-Shannon}

ZStotshbiom <- data_macrobenthos %>%
  dplyr::mutate(jaar = as.factor(jaar), soort = if_else(Taxa_groep == "Oligochaeta", "Oligochaeta", soort)) %>% ## sommige jaren zijn determinatiejaren voor wormen, dus alle oligo als 1 soort. Oligo weg laten geen goed idee want dan geen soorten meer in bv oligohalien in vele jaen
  dplyr::filter(systeem != "zijrivieren", biomassa > 0, soort != "geen") %>% 
  dplyr::group_by(soort, tidaal, jaar) %>% 
  dplyr::summarize(bm = sum(na.omit(biomassa))) %>%
  dplyr::ungroup() %>% 
  dplyr::group_by(tidaal, jaar) %>% 
  dplyr::summarize(Shannon_biomassa = calc_shannon_index(bm)) %>% 
  dplyr::mutate(waterloop_ZS = "Zeeschelde_totaal")


Sh_b_bas<- data_macrobenthos %>%
  dplyr::rename(waterloop_ZS = niveau3_hybr) %>% 
  dplyr::mutate(jaar = as.factor(jaar), soort = if_else(Taxa_groep == "Oligochaeta", "Oligochaeta", soort)) %>% ## sommige jaren zijn determinatiejaren voor wormen, dus alle oligo als 1 soort. Oligo weg laten geen goed idee want dan geen soorten meer in bv oligohalien in vele jaen
  dplyr::filter(systeem != "zijrivieren", biomassa > 0) %>% 
  dplyr::group_by(soort, waterloop_ZS, tidaal, jaar) %>% 
  dplyr::summarize(bm = sum(na.omit(biomassa)),
            ab = sum(na.omit(densiteit))) %>%
  dplyr::ungroup() %>% 
  dplyr::group_by(waterloop_ZS, tidaal, jaar) %>% 
  dplyr::summarize(Shannon_biomassa = calc_shannon_index(bm)) 

Sh_biom_i <- Sh_b_bas %>%
  rbind(ZStotshbiom) %>%
  dplyr::mutate(waterloop_ZS = factor(waterloop_ZS,
                             levels = zeeschelde_order2022tot)) %>%
  dplyr::filter(tidaal == "intertidaal") %>% 
  ggplot(aes(x=jaar, y=Shannon_biomassa), colour=waterloop_ZS)+
  geom_line(aes(colour=waterloop_ZS, group=waterloop_ZS), size =1.2)

Sh_biom_s <- Sh_b_bas %>%
  rbind(ZStotshbiom) %>%
  dplyr::mutate(waterloop_ZS = factor(waterloop_ZS,
                             levels = zeeschelde_order2022tot)) %>%
  dplyr::filter(tidaal == "subtidaal") %>% 
  ggplot(aes(x=jaar, y=Shannon_biomassa), colour=waterloop_ZS)+
  geom_line(aes(colour=waterloop_ZS, group=waterloop_ZS), size =1.2)

# Shannon aantal
ZStotshaant <- data_macrobenthos %>%
  dplyr::mutate(jaar = as.factor(jaar), soort = if_else(Taxa_groep == "Oligochaeta", "Oligochaeta", soort)) %>% ## sommige jaren zijn determinatiejaren voor wormen, dus alle oligo als 1 soort. Oligo weg laten geen goed idee want dan geen soorten meer in bv oligohalien in vele jaen
  dplyr::filter(systeem != "zijrivieren", soort != "geen") %>% 
  dplyr::group_by(soort, tidaal, jaar) %>% 
  dplyr::summarize(ab = sum(na.omit(densiteit))) %>%
  dplyr::ungroup() %>% 
  dplyr::group_by(tidaal, jaar) %>% 
  dplyr::summarize(Shannon_aantal = calc_shannon_index(ab)) %>% 
  dplyr::mutate(waterloop_ZS = "Zeeschelde_totaal")


Sh_a_bas<- data_macrobenthos %>%
  dplyr::rename(waterloop_ZS = niveau3_hybr) %>% 
  dplyr::mutate(jaar = as.factor(jaar), soort = if_else(Taxa_groep == "Oligochaeta", "Oligochaeta", soort)) %>% ## sommige jaren zijn determinatiejaren voor wormen, dus alle oligo als 1 soort. Oligo weg laten geen goed idee want dan geen soorten meer in bv oligohalien in vele jaen
  dplyr::filter(systeem != "zijrivieren", soort != "geen") %>% 
  dplyr::group_by(soort, waterloop_ZS, tidaal, jaar) %>% 
  dplyr::summarize(bm = sum(na.omit(biomassa)),
            ab = sum(na.omit(densiteit))) %>%
  dplyr::ungroup() %>% 
  dplyr::group_by(waterloop_ZS, tidaal, jaar) %>% 
  dplyr::summarize(Shannon_aantal = calc_shannon_index(ab)) 



Sh_aant_i<- Sh_a_bas %>%
  rbind(ZStotshaant) %>%
  dplyr::mutate(waterloop_ZS = factor(waterloop_ZS,
                             levels = zeeschelde_order2022tot)) %>%
  dplyr::filter(tidaal == "intertidaal") %>% 
  ggplot(aes(x=jaar, y=Shannon_aantal), colour=waterloop_ZS)+
  geom_line(aes(colour=waterloop_ZS, group=waterloop_ZS), size =1.2)

Sh_aant_s<- Sh_a_bas %>%
  rbind(ZStotshaant) %>%
  dplyr::mutate(waterloop_ZS = factor(waterloop_ZS,
                             levels = zeeschelde_order2022tot)) %>%
  dplyr::filter(tidaal == "subtidaal") %>% 
  ggplot(aes(x=jaar, y=Shannon_aantal), colour=waterloop_ZS)+
  geom_line(aes(colour=waterloop_ZS, group=waterloop_ZS), size =1.2)


ggarrange(Sh_aant_i + rremove("xlab")+ font("xy.text", size = fnt), 
          Sh_biom_i + font("xy.text", size = fnt), 
          nrow = 2,
          common.legend = TRUE, legend = "right")+ bgcolor("White")

ggsave(paste0(pad_figuren, "070-figuur-Shannondiv-intert-Zeeschelde.jpg"), height=5, width=8) 

ggarrange(Sh_aant_s + rremove("xlab")+ font("xy.text", size = fnt), 
          Sh_biom_s + font("xy.text", size = fnt), 
          nrow = 2,
          common.legend = TRUE, legend = "right")+ bgcolor("White")

ggsave(paste0(pad_figuren, "070-figuur-Shannondiv-subt-Zeeschelde.jpg"), height=5, width=8)

```


```{r 070-oppervlakte koppelen}
#Volledige jaren: 2001,2010, 2016, 2019, andere jaren niet voor OMES 14-19 dus niet gebruiken

oppsruw <- read_excel(paste0(pad_data, "SpatialEcotopenOPP_ApplEcotoop_INBO_v2019small.xlsx"), sheet = "SpatialEcotopenOPP_ApplEcotoop_") %>% 
  dplyr::filter(waterloop != "SCHRAP", !is.na(tidaal)) %>% 
  # hoog en middelhoog samennemen - tot categorie middelhoog/hoog intertidaal
  # eco/fysiotoopnamen opkuisen om match te kunnen maken tussen
  # oppervlakten en biotagegevens
  dplyr::mutate(ecotoop = recode(ecotoop, "hoog intertidaal"= "middelhoog/hoog intertidaal", "middelhoog intertidaal" = "middelhoog/hoog intertidaal")) %>% 
  rename(fysiotoop = ecotoop, opp1 = SomVanShape_Area)


  # segmenten optellen
  opps <- oppsruw %>% 
    dplyr::group_by(jaar, waterloop, tidaal, fysiotoop) %>% 
    dplyr::summarise(opp =sum(na.omit(opp1)))
    
  opps_intertidaalfys <- opps %>% 
    filter(tidaal == "intertidaal") %>% 
    mutate (kaartjaar = jaar) %>% 
    mutate (fysiotoop = (if_else(waterloop == "Durme" & fysiotoop != "intertidaal indet.", "intertidaal indet.", fysiotoop))) %>% 
    mutate(waterloop = recode(waterloop, "Zeeschelde IV" = "Saliniteitsgradient", "Zeeschelde III" = "Oligohalien", "Zeeschelde II" = "Zoet lang verblijf", "Zeeschelde I" = "Zoet kort verblijf"))

  
  data_macrobenthos_intertidaalfys <-
  data_macrobenthos_totaal %>%
  filter(tidaal == "intertidaal") %>% 
  filter(fysiotoop != "hard substraat") %>% 
  mutate (fysiotoop = (if_else(waterloop == "Durme" & fysiotoop != "intertidaal indet.", "intertidaal indet.", fysiotoop))) %>%  
  group_by(jaar, waterlichaam, niveau3_hybr, systeem, fysiotoop) %>% 
  summarise_at(vars(densiteit, biomassa), 
               list(mean = ~max(0, mean(., na.rm = TRUE)),
                    med = ~max(0, median(., na.rm = TRUE)),
                    lwr1 = ~max(0, quantile(., 0.25, na.rm = TRUE)),
                    upr1 = ~max(0, quantile(., 0.75, na.rm = TRUE)),
                    lwr2 = ~max(0, quantile(., 0.05, na.rm = TRUE)),
                    upr2 = ~max(0, quantile(., 0.95, na.rm = TRUE)))) %>% 
  ungroup() %>% 
  dplyr::mutate (kaartjaar = jaar) %>% #jaar van de beste oppervlaktematch toevoegen - we kiezen de kaartjaren van totale Zeeschelde-ecotopenkaarten
  dplyr::mutate (kaartjaar = if_else(jaar < 2012, 2010,kaartjaar)) %>% 
  dplyr::mutate (kaartjaar = if_else(jaar > 2011 & jaar < 2015, 2013, kaartjaar)) %>% 
  dplyr::mutate (kaartjaar = if_else(jaar > 2014 & jaar < 2018, 2016, kaartjaar)) %>%
  dplyr::mutate (kaartjaar = if_else(jaar > 2017, 2019, kaartjaar)) %>% 
  rename (waterloop = niveau3_hybr) 
  
  data_macrobenthos_OPP <- data_macrobenthos_intertidaalfys %>% 
  left_join(opps_intertidaalfys, by = c("kaartjaar", "fysiotoop","waterloop")) %>%
  mutate(biomassa_fys = (biomassa_mean * opp*10000)/1000000) #ton benthos
    
## samenvatten per waterloop en bereken totaal
  
  data_macrobenthos_OPPWL <- data_macrobenthos_OPP %>%
    rename(jaar = jaar.x) %>%
    dplyr::filter(waterloop %in% c("Saliniteitsgradient", "Zoet kort verblijf", "Zoet lang verblijf", "Oligohalien", "Durme", "Rupel")) %>% 
    dplyr::group_by(waterloop, jaar) %>% 
    dplyr::summarise(biomass_waterloop = sum(na.omit(biomassa_fys)))  
  
  totaal  <-data_macrobenthos_OPPWL %>% 
    dplyr::group_by(jaar) %>% 
    dplyr::filter(waterloop %in% c("Saliniteitsgradient", "Zoet kort verblijf", "Zoet lang verblijf", "Oligohalien")) %>% 
    dplyr::summarise(biomass_waterloop = sum(na.omit(biomass_waterloop))) %>% 
    dplyr::mutate (waterloop = "totaal_Zeeschelde")
  
  data_macrobenthos_OPPWL <- data_macrobenthos_OPPWL %>% 
     bind_rows(totaal) 
  
  data_macrobenthos_OPPWL$waterloop <- factor(data_macrobenthos_OPPWL$waterloop, levels=c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf","Rupel","Durme","totaal_Zeeschelde"))       
  
  data_macrobenthos_OPPWL %>% 
    ggplot(aes(x = as.factor(jaar), y = biomass_waterloop))+
    geom_hline(yintercept = 30, linetype=2, colour = "deeppink3", size = 1.2) +
    geom_hline(yintercept = 14.2, linetype=2, colour = "darkolivegreen4", size = 1.2) +
    geom_hline(yintercept = 8.3, linetype=2, colour = "paleturquoise4", size = 1.2) +
    geom_hline(yintercept = 5, linetype=2, colour = "darkorange2", size = 1.2) +
    geom_hline(yintercept = 2.5, linetype=2, colour = "lightblue2", size = 1.2) +
    geom_line(aes(colour = waterloop, group = waterloop), size = 1.8) +
    labs(x="", y = "systeembiomassa (ton droge stof)")
    
ggsave(paste0(pad_figuren, "070-figuur-intertidalesysteembiomassa.jpg"), height=5, width=8)  
  
## gewogen biomassa per m² per waterloop
  data_macrobenthos_OPP$waterloop <- factor(data_macrobenthos_OPP$waterloop, levels=c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf","Rupel","Durme","totaal_Zeeschelde"))
  data_macrobenthos_OPP %>%
    rename(jaar = jaar.x) %>%
    dplyr::filter(waterloop %in% c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf","Rupel","Durme","totaal_Zeeschelde")) %>% 
    dplyr::group_by(waterloop, jaar) %>% 
    dplyr::summarise(weightedbiomass_waterloop = weighted.mean(biomassa_mean, opp)) %>%
  ggplot(aes(x = as.factor(jaar), y = weightedbiomass_waterloop))+
        geom_line(aes(colour = waterloop, group = waterloop), size = 1.8) +
    labs(x="", y = "gewogen gemiddelde biomassa (g/m²)")
  
  ggsave(paste0(pad_figuren, "070-figuur-gewogengemiddeldebiomassa.jpg"), height=5, width=8)

## Gemiddelde biomassa  
  data_macrobenthos_OPP %>%
    rename(jaar = jaar.x) %>%
    filter(waterloop %in% c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf","Rupel","Durme","totaal_Zeeschelde")) %>% 
    dplyr::group_by(waterloop, jaar) %>% 
    summarise(weightedbiomass_waterloop = mean(biomassa_mean)) %>%
  ggplot(aes(x = as.factor(jaar), y = weightedbiomass_waterloop))+
        geom_line(aes(colour = waterloop, group = waterloop), size = 1.8) +
    labs(x="", y = "gemiddelde biomassa (g/m²)")
  
 sysbiomgew <- data_macrobenthos_OPP %>%
    rename(jaar = jaar.x) %>%
    filter(waterloop %in% c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf", "Zoet kort verblijf","Rupel","Durme","totaal_Zeeschelde")) %>% 
    group_by(waterloop, jaar) %>% 
    summarise(weightedbiomass_waterloop = mean(biomassa_mean))
   
opps %>% 
  dplyr::group_by(waterloop, jaar) %>% 
  dplyr::summarise(oppt = sum(opp)) %>%
  dplyr::filter(waterloop !="Tijarm") %>% 
  ggplot(aes(x=jaar, y=oppt))+
  geom_line(aes(colour=waterloop, group=waterloop), size=1.8)
  
mb.sel.8sp<- data_macrobenthos %>%
  dplyr::filter(waterlichaam == "Zeeschelde IV" & jaar == 2020) %>%
  dplyr::group_by(soort) %>% 
  dplyr::summarise(biom = sum(na.omit(biomassa))) %>% 
  ungroup() %>% 
  distinct() %>% 
  arrange(desc(biom)) %>%
  slice(1:8) %>%
  ungroup() 
selmb <- mb.sel.8sp$soort

data_macrobenthos %>% 
  dplyr::filter(soort %in% selmb) %>% 
  dplyr::filter(jaar %in% c(2016, 2017, 2018, 2019, 2020)) %>% 
  dplyr::filter(waterlichaam == "Zeeschelde IV") %>% 
  dplyr::group_by(soort, jaar) %>% 
  dplyr::summarize(bm = sum(biomassa)) %>% 
  dplyr::ungroup() %>% 
  ggplot(aes(x=jaar, y = bm, colour = soort))+
  geom_line(aes(colour = soort, group = soort), size = 1.8)

```

```{r}
#unused fragments possibly recycling later

 opps <- aggregate(SomVanShape_Area ~ jaar + waterloop + tidaal + fysiotoop + Omessegmen,
                    data = oppsruw, FUN = sum)
  # veinzen dat ook in 2012 en 2014 OMES 14 beschikbaar is
  # door gegevens van 2013 in te vullen
  twaalf <- opps[opps$jaar==2013 & opps$Omessegmen=="14",]
  twaalf$jaar <- 2012
  veertien <- opps[opps$jaar==2013 & opps$Omessegmen=="14",]
  veertien$jaar <- 2014
  opps <- rbind(opps,twaalf,veertien)
  
  
    
  # listopp <- opps_intertidaalfys[c("jaar","waterloop","fysiotoop")]
  # listopp <- unique(listopp)
  # unique(listopp$fysiotoop)
  # unique(data_macrobenthos_intertidaalfys$fysiotoop)
  
  # opps_intertidaal_waterloop <- opps_intertidaalfys %>% 
  #   filter(grepl("Zeeschelde", waterloop)) %>% 
  #   group_by(waterloop, jaar) %>% 
  #   summarise (Totslik = sum(opp)) %>% 
  #   ungroup() 
  #   
  # ggplot(opps_intertidaal_waterloop,aes(x = jaar, y = Totslik, color = waterloop)) + 
  #   geom_point(aes(shape = waterloop))+
  #   geom_line()
  ##oppervlakte data 2015 : er zit een fout in deze vr ZSIV en ZSIII - lijken niet betrouwbaar in deze dataset
```


```{r meta-data}

meta_data <- 
  enframe(c(laatstejaar = laatste_jaar, 
            vroegstejaar = vroegste_jaar,
            aantal_stalen = n_staal),
          name = "naam", value = "waarde")

meta_data %>% 
  write_delim(paste0(pad_data, "meta_data.csv"),
              delim = ";")

```

