
# Macrozoöbenthos 

Fichenummer: S-DS-V-002

__Jeroen Speybroeck__


## Inleiding 

Een beschrijving van de historische benthosgegevens (1999, 2002, 2005) is te vinden in Speybroeck et al. (2014**XXX**). Sinds 2008 wordt jaarlijks op basis van een random stratified design benthos bemonsterd.

De gegevens van 2008 tot en met 2016 worden geleverd in een Excel-bestand (_S_DS_V_002_benthos_data2008-2016_rapportage2018.xlsx_) met volgende werkbladen.

densiteit – densiteit per staalnamelocatie

biomassa – biomassa per staalnamelocatie

locaties – de Lambert-coördinaten van de bemonsterde locaties

Naast de gegevens van 2016, worden ook de gegevens van Dijle, Nete en Zenne van 2015 aangeleverd, die bij de vorige rapportage ontbraken.


## Materiaal en methode

### Strategie

Sinds 2008 wordt een stratified random sampling design toegepast. Als hoogste hiërarchisch niveau binnen de stratificatie worden de 7 waterlichamen genomen, zoals deze voor monitoring en beoordeling in de context van de Kaderrichtlijn Water (KRW) worden onderscheiden (Figuur 1-1**XXX**). In Zeeschelde III wordt de Rupel echter apart beschouwd en ook de Dijle en Zenne worden als aparte eenheden behandeld. Per waterlichaam wordt vervolgens een opdeling gemaakt per fysiotoop (\@ref(tab:tabel-staalnamelocaties)), met de uitzondering dat hoog slik en slik in het supralitoraal (potentiële pionierzone) samen genomen worden. Dit resulteert in een gelijkmatige spreiding van de staalnamelocaties. Jaarlijks worden nieuwe random vastgelegde staalnamelocaties gekozen. 

In principe worden 5 locaties per fysiotoop bemonsterd. Dit aantal wordt aangepast in sommige gevallen in functie van de relatieve en absolute areaalgrootte van de fysiotopen. Voor de Durme en de bovenlopen van Netes en Zenne is geen fysiotopenkaart beschikbaar, waardoor een aantal staalnamepunten gekozen zijn los van een fysiotoop-gebaseerde stratificatie.

De fysiotoop fungeert als kleinste eenheid van informatie. De stalen van verschillende locaties binnen een zelfde fysiotoop worden dan ook als replica’s voor dat fysiotoop beschouwd.
 

```{r tabel-staalnamelocaties}

knitr::kable(caption = "Aantal staalnamelocaties per waterlichaam (sectie) - monitoringscampagne 2016XXX.",
             data.frame(sectie = c("Zeeschelde IV", "Zeeschelde III", "Zeeschelde II", "Zeeschelde I", 
                                  "Rupel", "Durme", "Nete", "Dijle", "Zenne", "all"), 
                        hoog = c(9, 4, 4, 6, 0, 5, 4, 6, 3, 41), 
                        middelhoog = c(9, 4, 4, 6, 4, 4, 5, 6, 3, 45), 
                        laag = c(9, 4, 4, 6, 4, 5, 5, 6, 3, 46), 
                        hard = c(3, 3, 3, 6, 3, 0, 0, 0, 0, 18), 
                        "inter indet." = c(0, 0, 0, 0, 0, 0, 3, 0, 2, 5),  
                        ondiep = c(10, 5, 5, 6, 4, 5, 5, 6, 3, 49), 
                        "matig diep" = c(10, 3, 5, 4, 5, 5, 4, 3, 3, 42),
                        diep = c(10, 3, 5, 4, 5, 0, 0, 0, 0, 27),
                        "sub indet." = c(0, 0, 0, 0, 0, 0, 6, 0, 4, 10),
                        all = c(60, 26, 30, 38, 25, 24, 32, 27, 21, 283)), 
             "latex", booktabs = T) %>%
  kable_styling(latex_options = "striped")

```



In de Zeeschelde en de Rupel werden de anthropogene harde zones (steenbestortingen) afzonderlijk onderscheiden. Ook werden twee delen van waterlichamen opgedeeld omwille van de heterogene aard van hun habitats en fauna. Zeeschelde I werd opgedeeld in het traject Melle-Gentbrugge versus de rest van het KRW-waterlichaam, terwijl de Dijle stroomaf van de Zennemonding (Zennegat) ook afzonderlijk werd onderscheiden van de rest van de Dijle. In de grafieken in de data-exploratie worden deze echter samengevoegd.


### Staalname

We onderscheiden twee soorten benthosstalen.

__basisstaal (BS)__: jaarlijks

-	intertidaal: 1 steekbuisstaal (diameter: 4,5cm) tot op een diepte van 15cm
-	subtidaal: 1 steekbuisstaal uit een Reineck box-corer staal (diameter: 4,5cm) tot op een diepte van 15cm (in het box-corer staal)

__Oligochaetenidentificatiestaal (OID)__: elke drie jaar (2008, 2011, 2014, …) wordt aanvullend een tweede benthosstaal genomen. Dit staal wordt genomen in functie van de identificatie van oligochaeten (OID). 

-	intertidaal: 1 steekbuisstaal (diameter: 4,5cm) tot op een diepte van 15cm
-	subtidaal: 1 steekbuisstaal uit een Reineck box-corer staal (diameter: 4,5cm) tot op een diepte van 15cm (in het box-corer staal)

Beide benthosstalen (BS, OID) worden gefixeerd (formaldehyde 4%). 

Bij elk benthosstaal wordt jaarlijks ook een __sedimentstaal__ genomen en dit tot 10cm diepte met een sedimentcorer (diameter 2 cm zie ook hoofdstuk 6.2**XXX**) in het substraat (intertidaal) of in het box-corer sample (subtidaal). Dit wordt vervolgens ter bewaring ingevroren.


###	Verwerking

Hieronder geven we de chronologie van handelingen bij de verwerking van elk type staal.

__BS__

*	spoelen en zeven over twee zeven met maaswijdtes 1mm en 500µm => twee zeeffracties.
*	uitselecteren van fauna
*	determineren van alle individuen tot op het laagst mogelijke taxonomische niveau + tellen (maar de Oligochaeta worden als 1 taxon gerekend)
*	biomassabepaling = verassing (‘loss on ignition’):
    +	per taxon (= soort of een hoger niet nader te determineren taxonomisch niveau) per stratum (= per taxon samenvoegen van zeeffracties en van locaties binnen één fysiotoop))
    +	__Uitzondering__: waterlichaam Zeeschelde IV : biomassabepaling per zeeffractie om vergelijking toe te laten met stalen uit de Westerschelde (die op 1mm gezeefd worden)
    +	drogen (12h bij 105°C) => drooggewicht (DW)
    +	verassen (2h bij 550°C) => asgewicht (AW)
    +	biomassa: asvrij drooggewicht AFDW = DW - AW
  
__OID__

-	spoelen en zeven over twee zeven met maaswijdtes 1mm en 500µm => 2 zeeffracties
-	uitselecteren van fauna 
-	determineren van 25 individuen Oligochaeta per zeeffractie tot op het laagst mogelijke taxonomische niveau + tellen
-	geen biomassabepaling per soort; totale oligochaetenbiomassa wordt bepaald in BS
! Dit staal dient dus enkel voor het determineren van oligochaeten!

__Sedimentstaal__  - zie hoofdstuk **XXX**

-	granulometrie: korrelgrootteverdeling bepalen aan de hand van laserdiffractie
-	gehalte aan organisch materiaal: zoals biomassabepaling door verassing (zie hoger)

In Hoofdstuk 6**XXX** worden de sedimentgegevens besproken.



