---
params:
  hoofdstuk: "130_sedimentatie_erosie"
knit: (function(inputFile, ...) {
        rmarkdown::render(inputFile,
                          output_dir = paste0(rmarkdown::yaml_front_matter(inputFile)$params$hoofdstuk, "/output"))})
title: "figuren early warning MONEOS raaien"
output: word_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, error=FALSE, warning=FALSE, message=FALSE, cache=FALSE)

```


```{r libraries}

library(tidyverse)
library(readxl)
library(INBOtheme)
library(rprojroot)

# meerdere color of fill schalen in één figuur
library(ggnewscale)

conflicted::conflicts_prefer(dplyr::filter)

```


```{r pad}

# inlezen van variabelen
# pad naar data : pad_data
# pad naar tabellen : pad_tabellen
# pad naar figuren : pad_figuren

source(find_root_file("../pad.R", criterion = is_rstudio_project))

pad_data <- maak_pad(params$hoofdstuk, "data")
pad_figuren <- maak_pad(params$hoofdstuk, "figuren")
pad_tabellen <- maak_pad(params$hoofdstuk, "tabellen")

```


```{r data}

jaar <- 2023
campagne <- "C2022"
campagne_jaren_EW <- 2018:2023
campagnes_EW <- str_c("C", campagne_jaren_EW-1)

year_colors <-
  tibble(Year = campagne_jaren_EW) %>% 
  mutate(Colour = c(rev(terrain.colors(length(campagne_jaren_EW)+1))[c(-1,-2)], 'red'))



data_MONEOS <- 
  read_xlsx(path = str_c(pad_data, "TOPOdata_MONEOSraai_INBO_2023.xlsx"),
            sheet = "TOPOdata_MONEOSRAAIEN_INBO")

raai_campagne <- 
  data_MONEOS %>% 
  distinct(MeetCampagneJaar, Salzone, Omes, DATUM, REEKSCODE, Campagne)

```


```{r selectie vaste MONEOS raaien met metingen in laatste jaar en voldoende jaren voor EW}

data_EW <-
  data_MONEOS %>% 
  mutate(Year = year(DATUM)) %>% 
  group_by(REEKSCODE) %>% 
  mutate(meting = any(MeetCampagneJaar == campagne)) %>% 
  ungroup() %>% 
  filter(Campagne == "MONEOS",
         meting == TRUE,
         MeetCampagneJaar %in% campagnes_EW) %>% 
  select(-meting)

raaicodes <- 
  data_EW %>% 
  distinct(REEKSCODE) %>% 
  pull()

```


```{r ecotoopgrenzen}

tbl_waterstanden <-
  read_xlsx(path = str_c(pad_data, "ecotoopgrenzen.xlsx"))

data_EW <-
  data_EW %>% 
  left_join(tbl_waterstanden)

data_EW <-
  data_EW %>%
  group_by(REEKSCODE, DATUM) %>% 
  mutate(habpres = any(!is.na(Habitat))) %>% 
  ungroup() %>% 
  mutate(ecotoop = 
           case_when(
             habpres ~ Habitat,
             HOOGTE__MT > waterstand_HW85 ~ "schor",
             HOOGTE__MT <= waterstand_HW85 ~ "slik")) %>%
  mutate(ecotoop = 
           case_when(
            HOOGTE__MT < waterstand_LW30 ~ "subtidaal",
            TRUE ~ ecotoop)) %>% 
  select(-habpres)


ecotoopgrenzen <-
  data_EW %>% 
  group_by(REEKSCODE, afstand_grens, Salzone) %>% 
  summarise(bovengrens = unique(afstand_begin),
            bovengrens_meting = min(distance_prof[MeetCampagneJaar == campagne & distance_prof >= (bovengrens + 5)]) - 5,
            bovengrens_schor = min(distance_prof[ecotoop == "schor"], na.rm = TRUE),
            grens_schor = max(distance_prof[ecotoop == "schor" & MeetCampagneJaar == campagne], na.rm = TRUE),
            grens_subtidaal = max(distance_prof[ecotoop == "slik" & MeetCampagneJaar == campagne], na.rm = TRUE)) %>% 
  ungroup() %>% 
  select(REEKSCODE, afstand_grens, Salzone, 
         bovengrens, bovengrens_meting, bovengrens_schor, grens_schor, grens_subtidaal) %>% 
  mutate(across(everything(), ~ifelse(is.infinite(.), NA, .)))
  
```


```{r selectie enkel slik}

buffer_boven <- 0.5
buffer_onder <- 5

data_EW <-
  data_EW %>% 
  left_join(ecotoopgrenzen) %>% 
  filter(distance_prof >= grens_schor - buffer_boven
         # ,
         # distance_prof <= grens_subtidaal + buffer_onder
         )

```


```{r raaien met voldoende meetpunten en jaren}

raaien_sel <-
  data_EW %>% 
  mutate(dist_round = round(distance_prof)) %>% 
  group_by(REEKSCODE, Year) %>% 
  mutate(aantal = length(unique(dist_round)) >= 2) %>% 
  ungroup() %>% 
  filter(aantal == TRUE) %>% 
  distinct(REEKSCODE, Year) %>% 
  group_by(REEKSCODE) %>% 
  filter(n() > 4,
         jaar %in% Year) %>% 
  ungroup()

unique(raaien_sel$REEKSCODE)

# data_EW_sel <-
#   data_EW %>% 
#   filter(REEKSCODE %in% unique(raaien_sel$REEKSCODE))

data_EW_sel <-
  raaien_sel %>% 
  left_join(data_EW)


```


```{r interpolatie}

data_EW_interp_full <-
  data_EW_sel %>% 
  filter(!is.na(afstand_grens)) %>% 
  mutate(distance_prof = round(distance_prof),
         Year = year(DATUM)) %>% 
  group_by(MeetCampagneJaar, Salzone, Omes, Year, REEKSCODE, Campagne, afstand_grens, distance_prof) %>% 
  summarise(HOOGTE__MT = mean(HOOGTE__MT)) %>% 
  ungroup() %>% 
  group_by(MeetCampagneJaar, Salzone, Omes, Year, REEKSCODE, Campagne, afstand_grens) %>% 
  nest() %>% 
  transmute(intrp = map(data, 
                        ~approx(.$distance_prof, 
                                .$HOOGTE__MT, 
                                xout = seq(min(.$distance_prof), max(.$distance_prof), by = 1), 
                                rule = 2))) %>% 
  transmute(distance_prof = map(intrp, ~.$x),
            HOOGTE__MT = map(intrp, ~.$y)) %>% 
  unnest(cols = c(distance_prof, HOOGTE__MT)) %>% 
  ungroup()

data_EW_interp <-
  data_EW_interp_full %>% 
  drop_na(HOOGTE__MT)

```


```{r ecotoopgrenzen binnen slik}

data_EW_interp <-
  data_EW_interp %>% 
  left_join(tbl_waterstanden %>% 
              select(REEKSCODE, waterstand_DD_25, waterstand_DD_35, waterstand_DD_60)) %>% 
  mutate(ecotoop = 
           case_when(
             Salzone == "Mesohalien" & HOOGTE__MT <= waterstand_DD_25 ~ "laag slik",
             Salzone != "Mesohalien" & HOOGTE__MT <= waterstand_DD_35 ~ "laag slik",
             HOOGTE__MT >= waterstand_DD_60 ~ "hoog slik",
             TRUE ~ "middelhoog slik"))

ecotoopgrenzen_slik <-
  data_EW_interp %>% 
  group_by(REEKSCODE, Salzone) %>% 
  summarise(grens_laag_middelhoog = min(distance_prof[ecotoop == "laag slik"]),
            grens_middelhoog_hoog = min(distance_prof[ecotoop == "middelhoog slik"])) %>% 
  ungroup() %>% 
  select(REEKSCODE, Salzone, grens_laag_middelhoog, grens_middelhoog_hoog)

```


```{r functie figuren}

fig_raai <- 
  function(naam, dat_raai) {
    
    cat(str_c("raai: ", naam, "\n"))
    
    dat_raai <-
      dat_raai %>% 
      arrange(Year, distance_prof)
    RKSC <-
      naam
    
    colors <- 
      dat_raai %>% 
      distinct(Year) %>% 
      arrange(Year) %>% 
      left_join(year_colors)
    
    p <- 
      dat_raai %>% 
      mutate(Year = factor(Year)) %>% 
      ggplot(aes(distance_prof, HOOGTE__MT, group = Year, colour = Year)) +  
      geom_vline(data = ecotoopgrenzen_slik %>% filter(REEKSCODE == RKSC),
                 aes(xintercept = grens_laag_middelhoog),
                 linetype = 2, color = "grey50", linewidth = 2) +
      geom_vline(data = ecotoopgrenzen_slik %>% filter(REEKSCODE == RKSC),
                 aes(xintercept = grens_middelhoog_hoog),
                 linetype = 2, color = "grey50", linewidth = 2) +
      geom_line(linewidth = 1) + 
      scale_x_continuous(breaks = pretty(dat_raai$distance_prof, 20)) +
      scale_y_continuous(breaks = pretty(dat_raai$HOOGTE__MT, 5)) +
      scale_colour_manual(values = colors$Colour) +
      labs(title = naam,
           x = "Afstand tot de dijk (m)",
           y = "Hoogte (m T.A.W.)") + 
      theme_bw() + 
      theme(plot.title = element_text(size = 20, hjust = 0.5),
            axis.title = element_text(size = 18),
            axis.text = element_text(size = 15),
            legend.title = element_text(size = 20), 
            legend.text = element_text(size = 14),
            panel.border = element_blank(),
            panel.grid.minor = element_blank(), 
            panel.grid.major = element_line(colour = "grey")) 

    p
  }

```


```{r figuren slikraai}

figuren_EW <-
  data_EW_interp %>% 
  group_by(REEKSCODE) %>% 
  nest() %>% 
  mutate(fig = map2(REEKSCODE, data, ~fig_raai(.x, .y)))

# figuren_EW$fig

walk2(str_c("slik_interp_", figuren_EW$REEKSCODE), figuren_EW$fig, 
      ~ggsave(.y, file=str_c(pad_figuren, "early_warning/slik_interp/", .x, ".png"), 
              width=16, height=8, dpi= 350))

```


```{r selectie raaien}

data_EW_interp <-
  data_EW_interp %>% 
  filter(str_detect(REEKSCODE, "HEU", negate = TRUE))

```


```{r berekenen delta hoogte}

delta_hoogte_full <- NULL
for(r in unique(data_EW_interp$REEKSCODE)) {
  dat_raai <- 
    data_EW_interp %>% 
    filter(REEKSCODE == r)
  if(!is.null(dat_raai)) {
    j <- 
      dat_raai %>% 
      pull(Year) %>% 
      min()
    dat_ref <- 
      dat_raai %>% 
      filter(Year == j) %>% 
      select(REEKSCODE, distance_prof, HOOGTE__MT) %>% 
      rename(!!str_c("hoogte_", j) := HOOGTE__MT)
    if(!is.null(dat_ref)) {
      dat_delta <-
        dat_raai %>% 
        left_join(dat_ref) %>% 
        mutate(Year_ref = j,
               delta_Year = Year - j,
               delta_hoogte = HOOGTE__MT - .data[[str_c("hoogte_", j)]]) %>% 
        select(-!!str_c("hoogte_", j)) %>% 
        drop_na()
      delta_hoogte_full <-
        delta_hoogte_full %>% 
        bind_rows(dat_delta)
    }
  }
}

delta_hoogte_gem <-
  delta_hoogte_full %>% 
  group_by(REEKSCODE, afstand_grens, Salzone, Omes, Campagne, MeetCampagneJaar, ecotoop) %>% 
  filter(Year_ref == min(Year_ref)) %>% 
  ungroup() %>% 
  group_by(REEKSCODE, afstand_grens, Salzone, Omes, Campagne, MeetCampagneJaar, Year, Year_ref, delta_Year, ecotoop) %>% 
  summarise(delta_hoogte = mean(delta_hoogte, na.rm = TRUE)) %>% 
  ungroup()

```


```{r figuren delta hoogte, fig.height=10, fig.width=8}

delta_hoogte_gem %>% 
  ggplot(aes(Year, delta_hoogte, color = ecotoop)) +  
  geom_line(size = 1) + 
  geom_point(size = 2) +
  scale_x_continuous(breaks = 2018:2023) +
  labs(x = "jaar",
       y = "sedimentatie/erosie (meter)") +
  facet_wrap(~REEKSCODE, scales = "free_y") + 
  theme_bw() + 
  theme(plot.title = element_text(size = 20, hjust = 0.5),
        axis.title = element_text(size = 18),
        axis.text = element_text(size = 15),
        legend.title = element_text(size = 20), 
        legend.text = element_text(size = 14),
        # panel.border = element_blank(),
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_line(colour = "grey"),
        strip.text = element_text(size = 16)) 

```


```{r berekenen regressie}

hoogte_evolutie_predict <-
  delta_hoogte_gem %>%
  group_by(REEKSCODE, ecotoop, Year_ref) %>%
  # filter(Campagne != "C2022") %>%
  nest() %>%
  mutate(mod = map(data, ~lm(delta_hoogte ~ 0 + delta_Year, filter(., MeetCampagneJaar != campagne))),
         MeetCampagneJaar = map(data, ~pull(., MeetCampagneJaar)),
         Year = map(data, ~pull(., Year)),
         delta_Year = map(data, ~pull(., delta_Year)),
         delta_hoogte = map(data, ~pull(., delta_hoogte))) %>%
  dplyr::filter(map_lgl(delta_Year, ~length(.) > 0)) %>%
  transmute(slope_hoogte = map(mod, ~coef(.)[1]),
            MeetCampagneJaar = MeetCampagneJaar,
            Year = Year,
            delta_Year = delta_Year,
            delta_hoogte = delta_hoogte,
            preds = map2(mod, delta_Year,
                         ~predict(.x, newdata = tibble(delta_Year = .y), interval = "prediction") %>%
                                    as_tibble())) %>%
  unnest(cols = everything()) %>%
  ungroup()

hoogte_evolutie_predict <-
  hoogte_evolutie_predict %>%
  mutate(flag_hoogte = delta_hoogte < lwr | delta_hoogte > upr,
         Year_shift = 
           case_when(
             ecotoop == "laag slik" ~ Year - 0.2,
             ecotoop == "hoog slik" ~ Year + 0.2,
             TRUE ~ Year))

hoogte_evolutie_slope <-
  hoogte_evolutie_predict %>% 
  filter(MeetCampagneJaar != campagne) %>% 
  group_by(REEKSCODE, ecotoop) %>% 
  mutate(Year_end = max(Year)) %>% 
  ungroup() %>% 
  distinct(REEKSCODE, ecotoop, Year_ref, Year_end, slope_hoogte)


delta_hoogte_predict <-
  delta_hoogte_gem %>%
  left_join(hoogte_evolutie_predict %>%
              distinct(REEKSCODE, ecotoop, Year_ref, slope_hoogte)) %>%
  mutate(delta_hoogte_pred = slope_hoogte*delta_Year)

```


```{r figuren early warning}

dat_delta <-
  delta_hoogte_predict %>%
  group_by(REEKSCODE, ecotoop, Year_ref) %>%
  mutate(any_high = any(MeetCampagneJaar == campagne)) %>%
  filter(any_high) %>%
  select(-any_high) %>%
  ungroup() %>% 
  mutate(ecotoop = factor(ecotoop, levels = c("laag slik", "middelhoog slik", "hoog slik")))

# raaicodes <-
#   dat_delta %>% 
#   distinct(REEKSCODE) %>% 
#   pull()
# 
# r <- raaicodes[1]

dat_delta %>% 
  {ggplot(., aes(Year, delta_hoogte, color = ecotoop)) +
      labs(x = "jaar",
           y = expression(paste(Delta, "hoogte", " (m)"))) +
      geom_point(data = filter(., MeetCampagneJaar != campagne)) +
      geom_segment(data = hoogte_evolutie_slope,
                  aes(x = Year_ref, y = 0, xend = Year_end, yend = -Year_ref*slope_hoogte + Year_end*slope_hoogte, 
                      color = ecotoop),
                  linewidth = 1) +
      geom_hline(aes(yintercept = 0), linetype = 2) +
      # new_scale("color") +
      # geom_point(data = 
      #              hoogte_evolutie_predict %>% 
      #              filter(MeetCampagneJaar == campagne),
      #            aes(color = flag_hoogte, group = ecotoop)) +
      # geom_errorbar(data = 
      #                 hoogte_evolutie_predict %>% 
      #                 filter(MeetCampagneJaar == campagne),
      #               aes(ymin = lwr, ymax = upr, color = flag_hoogte, group = ecotoop),
      #               width = 0.5) +
      # scale_color_manual(name = "flagged", values = c("FALSE" = "chartreuse4", "TRUE" = "firebrick1")) +
      geom_point(data = 
                   hoogte_evolutie_predict %>% 
                   filter(MeetCampagneJaar == campagne),
                 aes(x = Year_shift, color = ecotoop, group = ecotoop, shape = flag_hoogte),
                     stroke = 1,
                     size = 2) +
      geom_errorbar(data = 
                      hoogte_evolutie_predict %>% 
                      filter(MeetCampagneJaar == campagne),
                    aes(x = Year_shift, ymin = lwr, ymax = upr, color = ecotoop, group = ecotoop),
                    linewidth = 1,
                    width = 0.25) +
      scale_shape_manual(name = "flagged", values = c("FALSE" = 1, "TRUE" = 15)) +
      # scale_y_continuous(breaks = pretty(.$delta_hoogte, 10)) +
      scale_x_continuous(breaks = seq(2019,2023, by = 2)) +
      facet_wrap(~REEKSCODE, scales = "free_y") +
      theme_bw() +
      theme(plot.title = element_text(size = 20, hjust = 0.5),
            axis.title = element_text(size = 18),
            axis.text = element_text(size = 15),
            legend.title = element_text(size = 16),
            legend.text = element_text(size = 14),
            panel.grid.minor = element_blank(),
            panel.grid.major.x = element_blank(),
            panel.grid.major.y = element_line(colour = "grey"),
            strip.text = element_text(size = 16))}

ggsave(file=str_c(pad_figuren, "early_warning/early_warning_", campagne, ".png"), 
              width=18, height=10, dpi= 350)
```

