---
params:
  hoofdstuk: "090_vissen"
title: "visdata ankerkuil"
knit: (function(inputFile, ...) {
        rmarkdown::render(inputFile,
                          output_dir = paste0(rmarkdown::yaml_front_matter(inputFile)$params$hoofdstuk, "/output"))})
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, error = FALSE, warning = FALSE, message = FALSE, cache = FALSE)

```


```{r libraries}

library(tidyverse)
library(lubridate)
library(readxl)
library(writexl)

library(inbodb)

library(rprojroot) ## workaround pad

```


```{r pad}

# inlezen van variabelen
# pad naar data : pad_data
# pad naar tabellen : pad_tabellen
# pad naar figuren : pad_figuren

source(find_root_file("../pad.R", criterion = is_rstudio_project))

pad_data <- maak_pad(params$hoofdstuk, "data")
pad_figuren <- maak_pad(params$hoofdstuk, "figuren")
pad_tabellen <- maak_pad(params$hoofdstuk, "tabellen")

```


```{r variabelen}

laatste_jaar <- as.numeric(jaar_moneos) - 1
pad_data_historisch <- str_c(pad_prj_schelde, pad_moneos, as.numeric(jaar_moneos) - 1, "/", params$hoofdstuk, "/data/")

locaties_name <- "ankerkuil_Zeeschelde_locaties"
metadata_name <- "ankerkuil_Zeeschelde_metadata"
filename <- "ankerkuil_Zeeschelde"

locaties <-
  read_xlsx(str_c(pad_data, "metadata VLIZ/", locaties_name, ".xlsx")) %>% 
  mutate(locatiecode = as.character(locatiecode))

```


```{r inlezen historische data}

filename_historisch <- 
  list.files(path = pad_data_historisch,
             pattern = "ankerkuil_Zeeschelde_VLIZ")

campagnes_historisch <- 
  read_xlsx(str_c(pad_data_historisch, filename_historisch),
            sheet = "campagnes")

aantal_historisch <- 
  read_xlsx(str_c(pad_data_historisch, filename_historisch),
            sheet = "aantallen")

gewicht_historisch <- 
  read_xlsx(str_c(pad_data_historisch, filename_historisch),
            sheet = "gewicht")

```


```{r inlezen recent data}

data_recent <- 
    read_xlsx(str_c(pad_data, "ankerkuil_Zeeschelde_ruw_VIS_",
                    laatste_jaar,
                    ".xlsx"),
             sheet = "data")

(old_names <- 
  data_recent %>% 
  distinct(Gebiedcode, Gebiednaam) %>% 
  arrange(Gebiedcode) %>% 
  pull(Gebiednaam))

gebieden <- 
  data_recent %>% 
  distinct(Gebiedcode, Gebiednaam, round(LambertX), round(LambertY)) %>% 
  arrange(Gebiedcode)

locaties <- 
  locaties %>% 
  filter(locatiecode %in% gebieden$Gebiedcode)

locatie_nrs <- locaties$locatiecode
locatie_namen <- locaties$locatie

(gebieden <- 
  gebieden %>% 
  mutate(new_names = locatie_namen[order(locatie_nrs)]))

level_key <- locatie_namen[order(locatie_nrs)]
names(level_key) <- old_names

```


```{r correcties soortnamen}

# rename_vector_historisch <-
#   c("chinese wolhandkrab" = "wolhandkrab")
rename_vector_historisch <-
  c("gewone zwemkrab" = "zwemkrab")

aantal_historisch <-
  aantal_historisch %>%
  rename(!!!rename_vector_historisch)
gewicht_historisch <-
  gewicht_historisch %>%
  rename(!!!rename_vector_historisch)


data_recent <- 
  data_recent %>% 
  mutate(Soort = case_match(Soort, 
                            "blauwband" ~ "blauwbandgrondel",
                            "zandspiering" ~ "kleine zandspiering",
                            "gewone steurgarnaal" ~ "steurgarnalen",
                            "steurgarnaal" ~ "steurgarnalen",
                            "grijze garnaal" ~ "grijze garnalen",
                            .default = Soort))

```


```{r correctie gewicht met verdunningsfactor}

data_recent <-
  data_recent %>% 
  mutate(TAXONGEW = TAXONGEW*METI_DILUTION_FACTOR,
         TAXONTOTGEW = TAXONTOTGEW*METI_DILUTION_FACTOR)
  
```


```{r controle dubbel gewicht in ruwe data}

dubbel_gewicht <-
  data_recent %>% 
  filter(!is.na(TAXONGEW) & !is.na(TAXONTOTGEW))

```


```{r controle uniek aantal of gewicht in ruwe data}

aantal_NA_of_0_ruw <-
  data_recent %>% 
  filter(is.na(TAXONAANTAL) |
           near(TAXONAANTAL, 0)) %>% 
  select("MetingPivotKey", "WaarnemingKey", "MetingID", "WaarnemingID", "GebiedKey", "Gebiedcode", 
         "LambertX", "LambertY", "Gebiednaam", 
         "Begindatum", "Month", "Year", "MethodeKey", "Methodenaam", "Methodegroepcode", 
         "uren", "volume", 
         "TaxonKey", "Soort", 
         "TAXONAANTAL", "TAXONGEW", "TAXONTOTGEW", "TAXONLEN", "METI_DILUTION_FACTOR")

gewicht_NA_of_0_ruw <-
  data_recent %>% 
  filter(if_all(c(TAXONGEW, TAXONTOTGEW), ~is.na(.)) |
           if_all(c(TAXONGEW, TAXONTOTGEW), ~near(., 0))) %>% 
  select("MetingPivotKey", "WaarnemingKey", "MetingID", "WaarnemingID", "GebiedKey", "Gebiedcode", 
         "LambertX", "LambertY", "Gebiednaam", 
         "Begindatum", "Month", "Year", "MethodeKey", "Methodenaam", "Methodegroepcode", 
         "uren", "volume", 
         "TaxonKey", "Soort", 
         "TAXONAANTAL", "TAXONGEW", "TAXONTOTGEW", "TAXONLEN", "METI_DILUTION_FACTOR")

soort_NA <-
  gewicht_NA_of_0_ruw %>% 
  filter(TAXONAANTAL == 1) %>% 
  pull(Soort) %>% 
  unique()

if (length(soort_NA) > 0) {
  data_lengte <-
    data_recent %>% 
    filter(Soort %in% soort_NA,
           !is.na(TAXONLEN)) %>% 
    select(Soort, TAXONAANTAL, TAXONGEW, TAXONLEN)
  
  data_lengte %>% 
    ggplot(aes(TAXONLEN, TAXONGEW)) +
    geom_point() +
    geom_smooth(method = "lm") +
    scale_x_log10() +
    scale_y_log10() +
    facet_wrap(~Soort)
  
  regressie_lengte <-
    data_lengte %>% 
    group_by(Soort) %>% 
    summarise(int = coef(lm(log(TAXONGEW)~log(TAXONLEN)))[1],
              slope = coef(lm(log(TAXONGEW)~log(TAXONLEN)))[2]) %>% 
    ungroup()

  datum_soort <-
  data_recent %>% 
  mutate(gewicht = if_else(is.na(TAXONGEW), 
                                  TAXONTOTGEW, TAXONGEW)) %>% 
  select(Gebiedcode, Gebiednaam, Begindatum, Soort, aantal = TAXONAANTAL, gewicht) %>% 
  filter(str_c(Gebiedcode, Begindatum, Soort) %in% unique(str_c(gewicht_NA_of_0_ruw$Gebiedcode, gewicht_NA_of_0_ruw$Begindatum, gewicht_NA_of_0_ruw$Soort))) %>% 
  drop_na() %>% 
  group_by(Gebiedcode, Gebiednaam, Begindatum, Soort) %>% 
  summarise(across(everything(), sum)) %>% 
  ungroup()


gewicht_NA <-
  gewicht_NA_of_0_ruw %>% 
  select(MetingPivotKey, Gebiedcode, Gebiednaam, Begindatum, Month, Year, Methodenaam, 
         TaxonKey, Soort, TAXONAANTAL, TAXONGEW, TAXONTOTGEW, TAXONLEN) %>% 
  left_join(datum_soort) %>% 
  left_join(regressie_lengte) %>% 
  replace_na(list(aantal = 0, gewicht = 0)) %>% 
  mutate(prop_aantal = TAXONAANTAL/aantal,
         gewicht_imputed = 
           case_when(
             TAXONAANTAL > 1 ~ gewicht*prop_aantal,
             TRUE ~ exp(int + slope*log(TAXONLEN))
           ))

write_xlsx(list(#NA_aantal_of_gewicht = uniek_aantal_of_gewicht,
                # NA_aantal = aantal_NA_of_0_ruw,
                NA_gewicht = gewicht_NA),
           path = str_c(pad_data, "controle/controle_NA_aantal_of_gewicht_ankerkuil.xlsx"))
}

```


```{r toevoegen imputation aan ruwe data}

if (length(soort_NA) > 0) {
  keys <- gewicht_NA$MetingPivotKey
  
  dat_before <-
    data_recent %>% 
    filter(MetingPivotKey %in% keys)
  
  for (k in keys) {
    data_recent$TAXONGEW[data_recent$MetingPivotKey == k] <-
      gewicht_NA$gewicht_imputed[gewicht_NA$MetingPivotKey == k]
  }
  
  dat_after <-
    data_recent %>% 
    filter(MetingPivotKey %in% keys)
}

```


```{r data per datum}

data_per_datum <- 
  data_recent %>% 
  select(locatiecode = Gebiedcode, locatie = Gebiednaam, datum = Begindatum, 
         getijde = Methodenaam, uren, volume, 
         soort = Soort, aantal = TAXONAANTAL, gewicht_ind = TAXONGEW, gewicht_tot = TAXONTOTGEW, 
         temperatuur = ABME_TEMPERATUUR, zuurstof = ABME_ZUURSTOF,	zuurstof_perc = ABME_ZUURSTOFPROCENT,	
         ph = ABME_PH,	turbiditeit = ABME_TURBIDITEIT,	conductiviteit = ABME_CONDUCTIVITEIT) %>% 
  mutate(locatie = recode(locatie, !!!level_key),
         datum = date(datum),
         jaar = year(datum),
         maand = month(datum),
         seizoen = 
           case_when(
           maand %in% 3:5 ~ "voorjaar",
           maand %in% 6:7 ~ "zomer",
           maand %in% 8:10 ~ "najaar",
           maand %in% 12:2 ~ "winter"),
         getijde = str_remove(getijde, "Ankerkuil-"),
         soort = str_to_lower(soort)) %>% 
  group_by(locatiecode, locatie, datum, jaar, maand, seizoen, getijde, uren, volume, soort) %>% 
  summarise(n = n(),
            gewicht = sum(if_else(is.na(gewicht_ind), 
                                  gewicht_tot, gewicht_ind),
                          na.rm = FALSE),
            aantal = sum(aantal, na.rm = FALSE),
            across(c(temperatuur, zuurstof,	zuurstof_perc, ph,	turbiditeit, conductiviteit), 
                   ~mean(., na.rm = TRUE)),
            .groups = "drop")

```


```{r controle NA in aantal of gewicht in geaggregeerde data}

dat_NA <-
  data_per_datum %>% 
  filter(is.na(aantal) | is.na(gewicht))

```


```{r controle ontbrekende campagnes}

campagnes <- 
  data_per_datum %>% 
  select(locatie, jaar, maand, seizoen, getijde) %>% 
  distinct()
camp_tot <-
  campagnes %>% 
  expand(locatie, jaar, seizoen, getijde)
  
campagnes_ontbrekend <-
  camp_tot %>% 
  anti_join(campagnes)

campagnes_NA_or_0 <-
  data_per_datum %>% 
  group_by(locatiecode, locatie, datum, jaar, seizoen, getijde, uren, volume) %>% 
  summarise(n = sum(n), aantal = sum(aantal, na.rm = TRUE), gewicht = sum(gewicht, na.rm = TRUE)) %>% 
  ungroup() %>% 
  arrange(datum, locatie, getijde) %>% 
  filter(if_any(.cols = everything(), .fns = ~is.na(.)) | 
           if_any(.cols = c(uren, volume), ~near(., 0)))

```


```{r controle uniek aantal of gewicht}

uniek_aantal_of_gewicht <-
  data_per_datum %>% 
  select(locatiecode, locatie, datum, jaar, maand, seizoen, getijde, uren, volume, soort, n, aantal, gewicht) %>% 
  arrange(datum, locatie, getijde) %>% 
  filter(if_any(c(aantal, gewicht), ~is.na(.)) |
           (if_any(c(aantal, gewicht), ~near(., 0)) & !if_all(c(aantal, gewicht), ~near(., 0))))


uniek_aantal_of_gewicht_vis <-
  uniek_aantal_of_gewicht %>% 
  filter(!str_detect(str_to_lower(soort), "garnaal|garnalen|gammarus|krab|kreeft|inktvis|octopus|zeekat"))

uniek_aantal_of_gewicht_inv <-
  uniek_aantal_of_gewicht %>% 
  filter(str_detect(str_to_lower(soort), "garnaal|garnalen|gammarus|krab|kreeft|inktvis|octopus|zeekat"))


write_xlsx(list(#NA_aantal_of_gewicht = uniek_aantal_of_gewicht,
                NA_aantal = aantal_NA_of_0_ruw,
                NA_gewicht = gewicht_NA_of_0_ruw),
           path = str_c(pad_data, "controle/controle_NA_aantal_of_gewicht_ankerkuil.xlsx"))


(uniek_aantal_of_gewicht_historisch <-
  symdiff(
    aantal_historisch %>% 
      select(-ID_afvissing) %>% 
      colSums(na.rm = TRUE) %>% 
      .[is.na(.) | . > 0] %>% 
      names(),
    gewicht_historisch %>% 
      select(-ID_afvissing) %>% 
      colSums(na.rm = TRUE) %>% 
      .[is.na(.) | . > 0] %>% 
      names()))

```


```{r vergelijking aanwezige soorten met historisch}

(soorten_historisch_aanwezig <-
  union(
    aantal_historisch %>% 
      select(-ID_afvissing) %>% 
      colSums(na.rm = TRUE) %>% 
      .[. > 0] %>% 
      names(),
    gewicht_historisch %>% 
      select(-ID_afvissing) %>% 
      colSums(na.rm = TRUE) %>% 
      .[. > 0] %>% 
      names()) %>% 
    sort())

(soorten_historisch_afwezig <-
  intersect(
    aantal_historisch %>% 
      select(-ID_afvissing) %>% 
      colSums(na.rm = TRUE) %>% 
      .[. == 0] %>% 
      names(),
    gewicht_historisch %>% 
      select(-ID_afvissing) %>% 
      colSums(na.rm = TRUE) %>% 
      .[. == 0] %>% 
      names()) %>% 
    sort())

intersect(soorten_historisch_aanwezig, soorten_historisch_afwezig)
setdiff(aantal_historisch %>% 
          select(-ID_afvissing) %>%
          names(), 
        union(soorten_historisch_aanwezig, soorten_historisch_afwezig))


(soorten_recent_aanwezig <-
    data_per_datum %>% 
    group_by(soort) %>% 
    summarise(aantal = sum(aantal, na.rm = TRUE)) %>% 
    ungroup() %>% 
    filter(aantal > 0) %>% 
    pull(soort) %>% 
    sort())

(soorten_recent_afwezig <-
    data_per_datum %>% 
    group_by(soort) %>% 
    summarise(aantal = sum(aantal, na.rm = TRUE)) %>% 
    ungroup() %>% 
    filter(aantal == 0) %>% 
    pull(soort) %>% 
    sort())

intersect(soorten_recent_aanwezig, soorten_recent_afwezig)
setdiff(data_per_datum %>% 
          distinct(soort) %>%
          pull(), 
        union(soorten_recent_aanwezig, soorten_recent_afwezig))


(soorten_totaal_afwezig <-
  setdiff(soorten_historisch_afwezig, soorten_recent_aanwezig) %>% 
    sort())

soorten_totaal_aanwezig <-
  union(soorten_historisch_aanwezig, soorten_recent_aanwezig) %>% 
    sort()

(soorten_totaal_aanwezig_invertebraten <-
  soorten_totaal_aanwezig %>% 
  keep(~ str_detect(., "garnaal|garnalen|gammarus|krab|kreeft|inktvis|octopus|zeekat")) %>% 
  sort())

(soorten_totaal_aanwezig_vis <-
    setdiff(soorten_totaal_aanwezig, soorten_totaal_aanwezig_invertebraten) %>% 
    sort())

(soorten_totaal_aanwezig <-
  c(soorten_totaal_aanwezig_vis, soorten_totaal_aanwezig_invertebraten))


(soorten_totaal <-
    union(soorten_totaal_aanwezig, soorten_totaal_afwezig) %>% 
    sort())

(unieke_soorten_historisch_aanwezig <-
    setdiff(soorten_historisch_aanwezig, 
            soorten_recent_aanwezig) %>% 
    sort())

(unieke_soorten_historisch_totaal <-
    setdiff(union(soorten_historisch_aanwezig, soorten_historisch_afwezig), 
            soorten_recent_aanwezig) %>% 
    sort())

(unieke_soorten_recent_aanwezig <-
    setdiff(soorten_recent_aanwezig, 
            soorten_historisch_aanwezig) %>% 
    sort())

# haringachtigen <-
#   data_per_datum %>% 
#   filter(soort %in% c("haring", "sprot", "haringachtigen"))
# 
# grondel_sp <-
#   data_per_datum %>% 
#   filter(soort == "grondel sp")
#   
# zwemkrab <-
#   data_per_datum %>% 
#   filter(str_detect(soort, "zwemkrab"))

```


<!-- ```{r correcties soortnamen recente data, eval=FALSE} -->

<!-- data_per_datum <- -->
<!--   data_per_datum %>%  -->
<!--   mutate(soort =  -->
<!--            case_match(soort, -->
<!--                       "gewone zwemkrab" ~ "zwemkrab", -->
<!--                       .default = soort)) -->

<!-- ``` -->


```{r sheets finale data recent}

campagnes_recent <-
  data_per_datum %>% 
  select(locatie, datum, jaar, seizoen, getijde, uren, volume, 
         temperatuur, zuurstof,	zuurstof_perc, ph,	turbiditeit, conductiviteit) %>% 
  distinct() %>% 
  arrange(datum, locatie) %>% 
  mutate(ID_afvissing = 1:n()) %>% 
  select(ID_afvissing, everything()) %>% 
  arrange(ID_afvissing)

aantallen_recent <-
  data_per_datum %>% 
  select(locatie, datum, getijde, soort, aantal) %>% 
  pivot_wider(names_from = soort,
              values_from = aantal,
              names_sort = TRUE,
              values_fill = 0) %>% 
  arrange(datum, locatie) %>% 
  mutate(ID_afvissing = 1:n()) %>% 
  select(ID_afvissing, everything(), -locatie, -datum, -getijde) %>% 
  arrange(ID_afvissing)

gewicht_recent <-
  data_per_datum %>% 
  select(locatie, datum, getijde, soort, gewicht) %>% 
  pivot_wider(names_from = soort,
              values_from = gewicht,
              names_sort = TRUE,
              values_fill = 0) %>% 
  arrange(datum, locatie) %>% 
  mutate(ID_afvissing = 1:n()) %>% 
  select(ID_afvissing, everything(), -locatie, -datum, -getijde) %>% 
  arrange(ID_afvissing)

```


```{r samenvoegen recent met historisch}

aantal_historisch_finaal <-
  aantal_historisch %>% 
  .[,names(aantal_historisch) %in% c("ID_afvissing", soorten_historisch_aanwezig)] %>% 
  arrange(ID_afvissing) %>% 
  add_column(matrix(data = 0, nrow = nrow(aantal_historisch), ncol = length(unieke_soorten_recent_aanwezig)) %>% 
               as_tibble() %>% 
               rename_at(., vars(names(.)), ~ unieke_soorten_recent_aanwezig))

gewicht_historisch_finaal <-
  gewicht_historisch %>% 
  .[,names(aantal_historisch) %in% c("ID_afvissing", soorten_historisch_aanwezig)] %>% 
  arrange(ID_afvissing) %>% 
  add_column(matrix(data = 0, nrow = nrow(gewicht_historisch), ncol = length(unieke_soorten_recent_aanwezig)) %>% 
               as_tibble() %>% 
               rename_at(., vars(names(.)), ~ unieke_soorten_recent_aanwezig))


start_ID <- max(campagnes_historisch$ID_afvissing)

campagnes_recent_finaal <-
  campagnes_recent %>% 
  mutate(ID_afvissing = ID_afvissing + start_ID)

aantal_recent_finaal <-
  aantallen_recent %>% 
  mutate(ID_afvissing = ID_afvissing + start_ID) %>% 
  add_column(matrix(data = 0, nrow = nrow(aantallen_recent), ncol = length(unieke_soorten_historisch_aanwezig)) %>% 
               as_tibble() %>% 
               rename_at(., vars(names(.)), ~ unieke_soorten_historisch_aanwezig))

gewicht_recent_finaal <-
  gewicht_recent %>% 
  mutate(ID_afvissing = ID_afvissing + start_ID) %>% 
  add_column(matrix(data = 0, nrow = nrow(gewicht_recent), ncol = length(unieke_soorten_historisch_aanwezig)) %>% 
               as_tibble() %>% 
               rename_at(., vars(names(.)), ~ unieke_soorten_historisch_aanwezig))


soorten_order <- 
  soorten_totaal_aanwezig

campagnes <-
  campagnes_historisch %>% 
  bind_rows(campagnes_recent_finaal) %>% 
  mutate(datum = ymd(datum))


aantallen <-
  aantal_historisch_finaal %>% 
  bind_rows(aantal_recent_finaal) %>% 
  relocate(all_of(soorten_order), .after = ID_afvissing)

gewicht <-
  gewicht_historisch_finaal %>% 
  bind_rows(gewicht_recent_finaal) %>% 
  relocate(all_of(soorten_order), .after = ID_afvissing)

# NAs vervangen voor soorten die overal nul zijn, maar niet wanneer aantallen of gewicht wel aanwezig zijn

# afwezige_soorten <-
#   intersect(
#     aantallen %>% 
#       select(-ID_afvissing) %>% 
#       colSums(na.rm = TRUE) %>% 
#       .[. == 0] %>% 
#       names(),
#     gewicht %>% 
#       select(-ID_afvissing) %>% 
#       colSums(na.rm = TRUE) %>% 
#       .[. == 0] %>% 
#       names())
# 
# soorten_replace <-
#   as.list(rep(0, length(afwezige_soorten)))
# names(soorten_replace) <- afwezige_soorten
# 
# aantallen <-
#   aantallen %>% 
#   replace_na(soorten_replace)
# gewicht <-
#   gewicht %>% 
#   replace_na(soorten_replace)

```


```{r wegschrijven-data}

filename <- "ankerkuil_Zeeschelde_VLIZ"

jaar_range <-
  campagnes %>% 
  distinct(jaar) %>% 
  pull(jaar) %>% 
  range()

locaties <-
  read_xlsx(str_c(pad_data, "metadata VLIZ/ankerkuil_Zeeschelde_locaties.xlsx"))
  
metadata <- 
  read_xlsx(str_c(pad_data, "metadata VLIZ/ankerkuil_Zeeschelde_metadata.xlsx"))

write_xlsx(list(locaties = locaties,
                campagnes = campagnes,
                aantallen = aantallen,
                gewicht = gewicht,
                metadata = metadata),
           path = str_c(pad_data, filename, "_", str_c(jaar_range, collapse = "_"), ".xlsx"))

```

