---
params:
  hoofdstuk: "100_watervogels"
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile,
                          encoding=encoding,
                          output_dir = paste0(rmarkdown::yaml_front_matter(inputFile)$params$hoofdstuk, 
                          "/output")
                          )})

title: "Watervogeldata - MONEOS 2026 - Nicolas Vanermen"
output:
  bookdown::word_document2: default
---
  
```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = FALSE, error = FALSE, warning = FALSE, message = FALSE, cache = FALSE)

```

```{r libraries}

library(tidyverse)
library(lubridate)
library(inbodb) 
### Read data from INBO databases (SQL Server) with R - see https://tutorials.inbo.be/tutorials/r_database_access/
library(DBI) 
### A database interface definition for communication between R and relational database management systems. 
library(rprojroot) ## workaround pad
library(openxlsx)
library(waldo)

```

```{r paden}

source(find_root_file("../pad.R", criterion = is_rstudio_project))

pad_data <- maak_pad(params$hoofdstuk, "data")
pad_figuren <- maak_pad(params$hoofdstuk, "figuren")
pad_tabellen <- maak_pad(params$hoofdstuk, "tabellen")

```

### Databank bevragen
```{r inlezen data Watervogeldatabank}

# - indien data download eerder is uitgevoerd en basisfiles dus al weg geschreven werden, kan je de data ook 
#   via de volgende chunk inlezen
# - gebaseerd op script N. Vanermen 'Watervogels_analyse_2025' - zie Amazon PRJ-Watervogels
# - aangepast om Zeeschelde analyseset correct te bevragen en aan te vullen met MIDMA
# - aangepast aan de opmerking van F. Piesschaert: alleen opgesplitste tellingen meenemen via: 
#   inner join DimSample sa on sa.samplekey = ##f.SampleKey where 1=1 and sa.Samplestatus <> 'REJECTED' 
#   (zie mail 5 dec 2025)

########## QUERY TOELICHTING ########## 

# Je ziet deze globale structuur:
#
#   with MIDMA AS ()
#   ,
#   ZSCH AS ()
#   , 
#   BASE AS (
#             SELECT * FROM MIDMA 
#             UNION
#             SELECT * FROM ZSCH
#           )
# 
# In het eerste deel creëer je eigenlijk twee tijdelijke tabellen MIDMA en ZSCH 
# (via een sql-structuur die gekend is als een Common Table Expression ofwel CTE)
# 
# In het tweede deel voeg je die datasets samen met de UNION operator. 
# UNION verwijdert automatisch duplicaten (itt UNION ALL die alle records behoudt)
# 
# Met een UNION haal je er alleen de echte duplicaten uit (dus 1 telling die 
# voor twee analysesets gebruikt wordt). 
#
# Er zijn echter ook gevallen waarbij er twee aparte tellingen zijn voor één 
# gebied en waarbij in de ene analyseset de ene en in de andere analyseset de 
# andere telling gebruikt wordt. In die gevallen krijgt de ZSCH-telling de 
# voorkeur en wordt de MIDMA-telling uit de dataset verwijderd. Dat gebeurt in
# het laatste deel van de query met de LEFT JOIN op de BASE-dataset
#
# Meer detail over het MIDMA-deel:
# - dit zijn de tellingen van de MIDMA-analysesets
# - bemerk dat ik de taxongroupcode ook heb toegevoegd aan de basisdataset
# - de wintertellingen van de Zeeschelde worden ook beschouwd als 
#   midmaandelijkse tellingen en leiden dus tot dubbels als we de data 
#   samenvoegen met de ZSCH-analyseset. Maar met die UNION lossen we dat dus op
# 
# Meer detail over het ZSCH-deel:
# - dit zijn de tellingen van de ZSCH-analyseset
# - bevat dus ook de zomertellingen
#
# Optioneel voor MIDMA-deel:
# - hieronder extra join toegevoegd op een subquery "loc" waarmee de 
#   locaties beperkt worden tot deze die relevant zijn voor Schelde/Sigma;je 
#   kan dat uiteraard ook achteraf in R zelf doen, maar hiermee wordt het aantal
#   records dat binnengehaald wordt met 2/3 verkleind en gaat het ook veel 
#   sneller; als je extra locatiegroepen of -groeptypes wil toevoegen moet je 
#   dat dus hier in de query zelf doen (zie invoeging vanaf line 139)
#     INNER JOIN (SELECT LocationWVKey
# 				FROM [dbo].[FactLocationGroup]
# 				WHERE 1 = 1
# 					AND IsDeleted = 0
# 					AND (LocationGroupCode in ('ZS','ZR','ZSVAL','SEST','WETL','NOH',
#                               'BW','DM','DU','KM','KBR','NG','OV','WZ')
# 					OR LocationGroupTypeCode in ('SCLUS')))loc on loc.LocationWVKey = f.LocationWVKey
#
# - noot 14/08/2026: met deze join worden inderdaad veel minder data binnengehaald, 
#   meer bepaald 350.350 ipv 1.073.228 records
# - deze join werd ingevoegd maar voorlopig 'commented out'

########## EINDE TOELICHTING ##########

### Connectie met WV databank:
con <- inbodb::connect_inbo_dbase("W0004_00_Waterbirds")

### Watervogeldata opvragen:
WV_DB <- dbGetQuery(con, "
WITH MIDMA AS (
  SELECT 
    SU.SurveyCode               AS ProjectCode
    , SU.SurveyNaam             AS Project
    , L.RegioWVCode             AS RegioCode
    , L.RegioWVNaam             AS Regio
    , L.LocationWVCode          AS GebiedsCode
    , L.LocationWVNaam          AS Gebied
    , SS.Seasonname             AS Telseizoen
    , E.EventCode               AS TellingCode
    , E.EventLabel              AS Telling
    , E.SortOrder               AS TellingSortOrder
    , S.sampleDate              AS Teldatum
    , S.CoverageCode            AS Telvolledigheid
    , T.TaxonGroupCode
    , T.TaxonGroupDescription
    , T.Commonname              AS NedNaam
    , T.scientificname          AS WetNaam
    , F.Taxoncount              AS Aantal
  FROM FactAnalyseSetOccurrence F
  
  /** optionele dataselectie vanaf hier...
  INNER JOIN (
    SELECT LocationWVKey
		FROM [dbo].[FactLocationGroup]
		WHERE 1 = 1
		  AND IsDeleted = 0
		  AND (
		    LocationGroupCode IN ('ZS','ZR','ZSVAL','SEST','WETL','NOH','BW','DM','DU','KM','KBR','NG','OV','WZ')
			  OR LocationGroupTypeCode IN ('SCLUS')
			)
	)loc ON loc.LocationWVKey = f.LocationWVKey
	... tot hier **/
  
  INNER JOIN DimSurvey SU       ON SU.surveykey = F.surveykey
  INNER JOIN DimLocationWV L    ON L.locationwvkey = F.locationwvkey
  INNER JOIN DimSeason SS       ON SS.Seasonkey = F.seasonkey
  INNER JOIN DimEvent E         ON E.eventkey = F.eventkey
  INNER JOIN DimSample S        ON F.samplekey = S.samplekey
  INNER JOIN DimTaxonWV T       ON T.taxonwvkey = F.taxonwvkey
  WHERE 1 = 1
    AND S.samplestatus = 'CHECKED'          /**alleen gevalideerde records**/
    AND S.samplestatus <> 'REJECTED'        /**alleen records van opgesplitste tellingen, cfr. Prosperpolder**/
    AND S.coveragecode not in ('-', 'N')    /**niet getelde tellingen zijn irrelevant**/
    AND F.taxoncount > 0
    AND F.Analysesetkey in (2, 3, 4)
),

ZSCH AS (
  SELECT 
    SU.SurveyCode               AS ProjectCode
    , SU.SurveyNaam             AS Project
    , L.RegioWVCode             AS RegioCode
    , L.RegioWVNaam             AS Regio
    , L.LocationWVCode          AS GebiedsCode
    , L.LocationWVNaam          AS Gebied
    , SS.Seasonname             AS Telseizoen
    , E.EventCode               AS TellingCode
    , E.EventLabel              AS Telling
    , E.SortOrder               AS TellingSortOrder
    , S.sampleDate              AS Teldatum
    , S.CoverageCode            AS Telvolledigheid
    , T.TaxonGroupCode
    , T.TaxonGroupDescription
    , T.Commonname              AS NedNaam
    , T.scientificname          AS WetNaam
    , F.Taxoncount              AS Aantal
  FROM FactAnalyseSetOccurrence F
  INNER JOIN DimSurvey SU       ON SU.surveykey = F.surveykey
  INNER JOIN DimLocationWV L    ON L.locationwvkey = F.locationwvkey
  INNER JOIN DimSeason SS       ON SS.Seasonkey = F.seasonkey
  INNER JOIN DimEvent E         ON E.eventkey = F.eventkey
  INNER JOIN DimSample S        ON F.samplekey = S.samplekey
  INNER JOIN DimTaxonWV T       ON T.taxonwvkey = F.taxonwvkey
  WHERE 1 = 1
   AND S.samplestatus = 'CHECKED'         /**alleen gevalideerde records**/
   AND S.samplestatus <> 'REJECTED'       /**alleen records van opgesplitste tellingen, cfr. Prosperpolder**/
   AND S.coveragecode not in ('-', 'N')   /**niet getelde tellingen zijn irrelevant**/
   AND F.taxoncount > 0
   AND F.Analysesetkey in (1)
),

BASE AS (
  SELECT * FROM MIDMA 
  UNION                 /**UNION removes only true duplicates (one sample used in multiple analysis sets)**/
  SELECT * FROM ZSCH
)

/**Subquery checks for locations with two distinct samples in the BASE-data - these are not duplicates in the strict sense, but for analysis only the ZSCH-sample should be used, the MIDMA-sample is dropped**/

SELECT b.*
FROM BASE b
LEFT JOIN (
  SELECT DISTINCT
      m.GebiedsCode
    , m.Gebied
    , m.Teldatum
  FROM MIDMA m
  FULL JOIN ZSCH z 
    ON  m.GebiedsCode = z.GebiedsCode 
    AND m.Telseizoen = z.Telseizoen
    AND m.Telling = z.Telling
  WHERE m.ProjectCode <> z.ProjectCode
)tmp 
  ON  tmp.Gebiedscode = b.GebiedsCode 
  AND tmp.Teldatum = b.Teldatum 
  AND b.ProjectCode = 'MIDMA'
WHERE tmp.Gebied IS NULL
")

### Watervogelgroepen opvragen
WVgroep <- dbGetQuery(con, "
  SELECT 
    TW.commonname               AS NedNaam
    ,TW.TaxonGroupCode          AS Groepscode
    ,TW.TaxonGroupDescription   AS Groep
  FROM DimTaxonWV TW
")

### Gebieden opvragen
Gebieden_ZS <- dbGetQuery(con, "
  SELECT 
    LocationGroupCode
    , LocationGroupNaam
    , LocationGroupTypeCode
    , LocationGroupTypeNaam
    , LocationWVCode
    , LocationWVNaam
    , StartDate
    , EndDate
  FROM [dbo].[FactLocationGroup]
  WHERE 1 = 1
    AND IsDeleted = 0
    AND LocationGroupCode in ('ZS','ZR','ZSVAL','SEST','WETL','NOH')
")

### Sigmaclusters opvragen
Clusters_Sigma <- dbGetQuery(con, "
  SELECT 
    LocationGroupCode
    , LocationGroupNaam
    , LocationGroupTypeCode
    , LocationGroupTypeNaam
    , LocationWVCode
    , LocationWVNaam
    , StartDate
    , EndDate
  FROM [dbo].[FactLocationGroup]
  WHERE 1 = 1
    AND IsDeleted = 0
    AND LocationGroupTypeNaam in ('Sigma-clusters')
")

### ZS-clusters opvragen
Clusters_ZS <- dbGetQuery(con, "
  SELECT 
    LocationGroupCode
    , LocationGroupNaam
    , LocationGroupTypeNaam
    , LocationGroupTypeCode
    , LocationWVCode
    , LocationWVNaam
    , StartDate
    , EndDate
  FROM [dbo].[FactLocationGroup]
  WHERE 1 = 1
    AND IsDeleted = 0
    AND LocationGroupTypeNaam in ('KRW-zones Zeeschelde (analyse)')
")

dbDisconnect(con)

### Basisfiles opslaan
write_delim(WV_DB, file.path(pad_data, "WV_DB_prep.csv"), delim = ";")
write_delim(WVgroep, file.path(pad_data, "WVgroep_prep.csv"), delim = ";")
write_delim(Gebieden_ZS, file.path(pad_data, "Gebieden_ZS_prep.csv"), delim = ";")
write_delim(Clusters_ZS,file.path(pad_data, "Clusters_ZS_MONEOS_prep.csv"), delim = ";")
write_delim(Clusters_Sigma, file.path(pad_data, "Clusters_Sigma_prep.csv"), delim = ";")

```

```{r alternatief voor het bevragen van de Watervogeldatabank: basisfiles inlezen uit pad_data}

# WV_DB <- read_delim(file.path(pad_data, "WV_DB_prep.csv"), delim = ";")
# WVgroep <- read_delim(file.path(pad_data, "WVgroep_prep.csv"), delim = ";")
# Gebieden_ZS <- read_delim(file.path(pad_data, "Gebieden_ZS_prep.csv"), delim = ";")
# Clusters_ZS <- read_delim(file.path(pad_data, "Clusters_ZS_MONEOS_prep.csv"), delim = ";")
# Clusters_Sigma <- read_delim(file.path(pad_data, "Clusters_Sigma_prep.csv"), delim = ";")

```

```{r verkenning}

WV_DB %>% glimpse()
# MONEOS 2026: 1.073.228 records en 17 kolommen
WV_DB %>% group_by(ProjectCode, Project) %>% summarise(N = n()) 

# scheldearm <- dplyr::filter(WV_DB, 
#                             GebiedsCode == '2050810')
# 
# verken1 <- dplyr::filter(WV_DB, 
#                          GebiedsCode == "3156629",
#                          Telseizoen == "2025/26")
# 
# verken2 <- dplyr::filter(WV_DB, 
#                          GebiedsCode == "2091308",
#                          Telseizoen == "2024/25" )

```

### Trofische groep koppelen
```{r data trofische groep koppelen voor MONEOSrapport}

### Join met WVgroep
WV_DB <- WV_DB %>% left_join(WVgroep)

data_trofische_groep <- read_delim(paste0(pad_data, "Voedselgilde_exoten_Moneosrapport.csv"), delim = ";")  

data_trofische_groep <- data_trofische_groep %>% 
              rename_all(tolower) %>% 
              rename(nednaam = species)

### Toevoegen trofisch groep aan dataset
WV_DB <- WV_DB %>% 
  left_join(data_trofische_groep, by = c("NedNaam" = "nednaam"))
# join resulteert in 21 kolommen

### Lijst van soorten niet opgenomen in de trofische analyse van MONEOS 
listspecies <- WV_DB %>%
  dplyr::filter(is.na(trofische_groep)) %>%
  distinct(NedNaam)
# 94 soorten die in lage aantallen voorkomen en niet bepalend zijn voor de trofische trends

```

### Gebiedsinfo toevoegen aan watervogeldata
#### Join  voorbereiden
```{r join voorbereiden van WV_DB met gebiedsindeling T2021}

Gebiedsindeling_T2021 <- 
  read_delim(paste0(pad_data, "Gebiedsindeling_T2021.csv"), 
             delim = ";")  

Gebiedsindeling_ltd <-
  Gebiedsindeling_T2021 %>% 
  mutate(rivier = case_when(
    niveau4 == "Rupel" ~ "Rupel",
    niveau4 == "GetijdeDurme" ~ "Durme",
    niveau4 == "GetijdeDijle" ~ "Dijle",
    niveau4 == "GetijdeZenne" ~ "Zenne",
    niveau4 == "Monding" ~ "Monding",
    niveau2 == "Westerschelde" ~ "Westerschelde",
    .default = "Zeeschelde")) %>% 
  rename(gebiedsgroep = krw) %>% 
  select("niveau1", "niveau2","niveau3", "gebiedsgroep", "rivier") %>% 
  distinct() %>% 
  dplyr::filter(gebiedsgroep != "Getijdenete")

knitr::kable(Gebiedsindeling_ltd)

# er is geen opdeling in de rivieren om niveau 3 of 4 uit databank te halen
# kolom met info op niveau 4 aanmaken om te kunnen koppelen

# gebieden selecteren
Gebieden_ZS_MONEOS <- Gebieden_ZS %>% 
  dplyr::filter(LocationGroupNaam %in% c("Zeeschelde", "Zijrivieren Zeeschelde")) %>% 
  mutate(rivier = case_when(
    LocationWVCode == "3121303" ~ "Rupel",
    LocationWVCode == "4140216" ~ "Rupel",
    LocationWVCode == "4140205" ~ "Rupel",
    LocationWVCode == "4140217" ~ "Rupel",
    LocationWVCode == "4140206" ~ "Rupel",
    LocationWVCode == "2091301" ~ "Durme",
    LocationWVCode == "2091305" ~ "Durme",
    LocationWVCode == "2080605" ~ "Durme",
    LocationWVCode == "3121003" ~ "Dijle",
    LocationWVCode == "3120101" ~ "Zenne",
    LocationWVCode == "3120104" ~ "Zenne",
    LocationWVCode == "3121412" ~ "Zenne",
    LocationWVCode == "3120103" ~ "Zenne",
    .default = "Zeeschelde")) %>% 
  select(LocationWVCode, LocationWVNaam, rivier)

# rivier toevoegen aan Clusters_ZS via join met Gebieden_ZS_MONEOS & niveau 3 definiëren
Clusters_ZS_MONEOS <- Clusters_ZS %>% 
  left_join(Gebieden_ZS_MONEOS) %>% 
  mutate(niveau3 = case_when (
     rivier == "Rupel" ~ "Rupel",
     rivier == "Durme" ~ "Durme",
     rivier == "Zenne"~ "Zoet zijrivier",
     rivier == "Dijle"~ "Zoet zijrivier",
     LocationGroupCode == "ZS4" ~ "Saliniteitsgradient",
     LocationGroupCode == "ZS3" ~ "Oligohalien",
     LocationGroupCode == "ZS2" ~ "Zoet lang verblijf",
     LocationGroupCode == "ZS1" ~ "Zoet kort verblijf",
     .default = "nvt"))

# join van Clusters_ZS_MONEOS met gebiedsindeling (voor niveau 1 & 2!) via rivier & niveau3
Clusters_ZS_MONEOS <- Clusters_ZS_MONEOS %>% 
  left_join(Gebiedsindeling_ltd) %>% 
  select(-gebiedsgroep)


### Gebieden_ZS opkuisen (en nieuwe naam geven zodat chunk onafhankelijk is van basisfiles)
Gebieden_ZS_clean <- Gebieden_ZS %>%
  mutate(Gebiedsklasse = case_when(LocationGroupCode %in% c("SEST", "WETL") ~ "Sigmagebied", 
                                   LocationGroupCode == "ZSVAL" ~ "Valleigebied",
                                   LocationGroupCode %in% c("ZS","ZR") ~ "Estuarium",
                                   LocationGroupCode == "NOH" ~ "Haven", 
                                   .default = NA)) %>% 
  rename_all(tolower) %>% 
  rename(gebiedsklassecode = locationgroupcode,
         zone = locationgroupnaam,
         analyseset = locationgrouptypecode,
         gebiedscode = locationwvcode,
         gebied = locationwvnaam) 

knitr::kable(table(Gebieden_ZS_clean$gebiedsklassecode, Gebieden_ZS_clean$gebiedsklasse))

### Check:
check_gebieden <- Gebieden_ZS_clean %>%
  anti_join(., WV_DB, by = c("gebied" = "Gebied")) %>%
  select(gebied) %>%
  pull()
knitr::kable(check_gebieden)
# 2 mismatches: Ontpoldering Polpolder LILLO & Kruibeekse Kreek estuarien KRUIBEKE

###  Clusters_ZS_MONEOS opkuisen
Clusters_ZS_MONEOS <- Clusters_ZS_MONEOS %>% 
  rename_all(tolower) %>% 
  rename(krwcode = locationgroupcode) %>% 
  rename(krwzone = locationgroupnaam) %>%
  rename(analyseset2 = locationgrouptypecode) %>%
  rename(gebiedscode = locationwvcode) %>%
  rename(gebied = locationwvnaam) %>% 
  select(-locationgrouptypenaam)

### Samenvoegen van Gebieden_ZS met Clusters_ZS_MONEOS voor alle gebiedsinfo
Gebieden_ZS_clean <- Gebieden_ZS_clean %>% 
  left_join(Clusters_ZS_MONEOS) 

```

#### Join van Gebieden_ZS met WV_DB  
``` {r join doorvoeren}

WV_DB <- WV_DB %>% 
  left_join(Gebieden_ZS_clean, by = c("GebiedsCode" = "gebiedscode")) %>% 
  mutate(niveau3 = fct_relevel(niveau3, 
                               c("Saliniteitsgradient", "Oligohalien", "Zoet lang verblijf",
                                 "Zoet kort verblijf", "Rupel", "Durme", "Zoet zijrivier"))) %>% 
  rename (gebiedMONEOS = gebied)
# de join resulteert in 21 + 15 = 36 kolommen

```

### Correcties op dataset
```{r correcties-Waterbirds}

### Checken voor dubbels in de dataset
dubbels <- WV_DB  %>% 
  group_by_at(vars(-Aantal)) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  dplyr::filter(n > 1) %>% 
  arrange(Gebied, Telseizoen, Telling, Teldatum, NedNaam, ProjectCode)

### Corrigeren voor dubbels
WV_DB <- WV_DB  %>% 
  group_by_at(vars(-Aantal)) %>% 
  summarise(Aantal = max(Aantal)) %>% # maximum van de dubbele tellingen
  ungroup()
# het aantal rijen zakt met 37 agv 35 dubbele & 1 driedubbele telling

```

### Controle op volledigheid
```{r controle volledigheid}

aantal_tellingen_gebied <- WV_DB %>%
  rename_all(tolower) %>%
  mutate(maand = month(teldatum)) %>%
  dplyr::filter(!is.na(niveau3),
                maand %in% c(10:12, 1:3),
                telseizoen %in% c("2024/25", "2025/26")) %>%
  distinct(krwzone, gebiedscode, gebied, telseizoen, teldatum) %>% 
  count(krwzone, gebiedscode, gebied, telseizoen) %>% 
  arrange(gebiedscode)

teldatums_25_26 <- WV_DB %>%
  rename_all(tolower) %>%
  filter(teldatum > "2025-10-01",
         !is.na(gebiedsklasse)) %>% 
  distinct(teldatum) 

### Open vraag: hoe weten we wanneer geen data = nultelling of wanneer niet geteld is?

```

### Datasets wegschrijven
```{r volledige dataset wegschrijven}

write_delim(WV_DB, file.path(pad_data, "WV_DB_ready.csv"), delim = ";")
write_delim(Gebieden_ZS_clean, file.path(pad_data, "Gebieden_ZS_ready.csv"), delim = ";")
write_delim(Clusters_ZS_MONEOS, file.path(pad_data, "Clusters_ZS_ready.csv"), delim = ";")
# write_delim(Clusters_Sigma, file.path(pad_data, "Clusters_Sigma_ready.csv"), delim = ";")


### Dataset voor VLIZ
# MONEOS inclusief meeuwen, data per maand

WV_DB %>% 
  rename_all(tolower) %>% 
  mutate(maand = month(teldatum)) %>%
  dplyr::filter(gebiedscode %in% Clusters_ZS_MONEOS$gebiedscode) %>% 
  group_by(krwzone,
           rivier,
           telseizoen,
           maand,
           nednaam,
           wetnaam,
           trofische_groep,
           exoot,
           niveau1,
           niveau2,
           niveau3) %>%
  summarise(aantal = sum(aantal)) %>% 
  ungroup() %>% 
  dplyr::select(-wetnaam)%>% 
  write_delim(paste0(pad_data, "Watervogels_ZeescheldeVLIZcheck.csv"),
              delim = ";")

```

``` {r mogelijke issues}


######## Chunk Databank bevragen

### 1. 
### Lijn 162 & 196
# AND S.samplestatus = 'CHECKED'         
# AND S.samplestatus <> 'REJECTED'    
# (2x)
# Zo is de 2e lijn overbodig! Welke moet ik behouden? Ik denk obv de uitleg van FP de 2e.


######## Chunk Gebiedsinfo toevoegen aan watervogeldata > Join  voorbereiden

### 2.
### Lijn 375
# dplyr::filter(gebiedsgroep != "Getijdenetes")
# Typo?? 
# Gewijzigd naar:
# dplyr::filter(gebiedsgroep != "Getijdenete")
 
### 3.
### Lijn 436
# knitr::kable(table(Gebieden_ZS_clean$gebiedsklassecode, Gebieden_ZS_clean$gebiedsklasse))
# Geen ‘WETL’? Correct?
# 
# 		Estuarium	Haven		Sigmagebied	Valleigebied
# NOH		0		30		0		0
# SEST		0		0		17		0
# ZR		13		0		0		0
# ZS		100		0		0		0
# ZSVAL		0		0		0		121

### 4.
### Lijn 438
# check_gebieden <- Gebieden_ZS_clean %>%
#   anti_join(., WV_DB, by = c("gebied" = "Gebied")) %>%
#   select(gebied) %>%
#   pull()
# knitr::kable(check_gebieden)
# 
# 2 mismatches!
# •	Ontpoldering Potpolder LILLO
# •	Kruibeekse Kreek estuarien KRUIBEKE
 

######## Chunk Datasets wegschrijven

### 5.
### Lijn 531
# Hier werd Clusters_ZS weggeschreven, terwijl ik zou denken dat dat de herwerkte Clusters_ZS_MONEOS moet zijn

```

``` {r "commented oud"}

## Telzones op nederlands grondgebied worden niet meegeteld (strik gesproken geen Zeeschelde). Dit gaat over de teltrajecten (9999999 en 9999998) gelegen op Nederlands grondgebied. Deze teltrajecten zitten niet in de gebiedsgroepen file
##Correctie Groot Schoor Hamme
## boottelling Schelde St. Amands - Oude Briel (LO) bevat infeite de vogels die foerageren in ontpoldering Groot Schoor Hamme
## voor 2022,2023,2024 houden we dezelfde aantallen als 2021 in teltraject
## Sigmagebied wordt niet goed geteld; we rekenen de vogelaantallen voor de ontpoldering als deze geteld op Zeeschelde vermindert met baseline aantallen van 2021 in teltraject
## Deze correctie werd gedaan in rapportage 2024 - men kan zich afvragen of we dat uberhaupt moet beginnen corrigeren - de vogels maken gebruik van beide deelgebieden. Dit zal een overschatting geven van de aantallen maar deze uitwisseling is er overal langs de Zeeschelde. Het blijft wel jammer dat het effect van Sigma niet volledig goed kan gedocumenteerd worden doordat zeker in de eeste jaren werd geteld bij ongunstig getij.

# 
# StAmandstotOudeBriel2020 <-
#   WV_DB %>% 
#   dplyr::filter(GebiedsCode == 4143122) %>% 
#   dplyr::filter(Telseizoen == "2020/21") 
# 
# years <- years(1) 
# StAmandstotOudeBriel2021false <-
#   StAmandstotOudeBriel2020 %>% 
#   mutate(Telseizoen = str_replace_all(Telseizoen, "2020/21", "2021/22")) %>% 
#   mutate(Teldatum = Teldatum +years)
# 
# StAmandstotOudeBriel2022false <-
#   StAmandstotOudeBriel2021false %>% 
#   mutate(Telseizoen = str_replace_all(Telseizoen, "2021/22", "2022/23")) %>% 
#   mutate(Teldatum = Teldatum +years)
# 
# StAmandstotOudeBriel2023false <-
#   StAmandstotOudeBriel2022false %>% 
#   mutate(Telseizoen = str_replace_all(Telseizoen, "2022/23", "2023/24")) %>% 
#   mutate(Teldatum = Teldatum +years)
# 
# #GrootSchorberekend te gebruiken voor Sigma-estuarien ontpoldering Groot Schoor Hamme ipv landtelling
# #bergeenden zijn nu wel onderschatting
# 
# #pas dit ook aan in Sigma dataset!
# 
# GrootSchorberekend2021 <- 
#   WV_DB %>% 
#   dplyr::filter(GebiedsCode == 4143122) %>% 
#   dplyr::filter(Telseizoen == "2021/22") %>% 
#   left_join(StAmandstotOudeBriel2020, by = c("NedNaam","Telling"), suffix = c("_winter2021", "_Baseline2020"),keep = TRUE) %>% 
#   mutate(across(c(Aantal_Baseline2020), ~replace_na(., 0))) %>% 
#   mutate(Aantal_diff = Aantal_winter2021 - Aantal_Baseline2020) %>% 
#   dplyr::filter(Aantal_diff >= 0) %>% 
#   select(ends_with("winter2021"), Aantal_diff) %>% 
#   select(-Aantal_winter2021) %>% 
#   rename_with(~ str_remove(.x, "_winter2021")) %>% 
#   rename(Aantal = Aantal_diff) %>% 
#   mutate(GebiedsCode = if_else(GebiedsCode == "4143122", "2091308", GebiedsCode)) %>% 
#   mutate(Gebied = if_else(Gebied == "Schelde St. Amands - Oude Briel (LO)", "Groot Schoor HAMME", Gebied)) %>% 
#   mutate(Analyseset = if_else(Analyseset == "boottelling", "SIGMA_MIDMA", Analyseset)) 
# 
# GrootSchorberekend2022 <- 
#   WV_DB %>% 
#   dplyr::filter(GebiedsCode == 4143122) %>% 
#   dplyr::filter(Telseizoen == "2022/23") %>% 
#   left_join(StAmandstotOudeBriel2020, by = c("NedNaam","Telling"), suffix = c("_winter2021", "_Baseline2020"),keep = TRUE) %>% 
#   mutate(across(c(Aantal_Baseline2020), ~replace_na(., 0))) %>% 
#   mutate(Aantal_diff = Aantal_winter2021 - Aantal_Baseline2020) %>% 
#   dplyr::filter(Aantal_diff >= 0) %>% 
#   select(ends_with("winter2021"), Aantal_diff) %>% 
#   select(-Aantal_winter2021) %>% 
#   rename_with(~ str_remove(.x, "_winter2021")) %>% 
#   rename(Aantal = Aantal_diff)%>% 
#   mutate(GebiedsCode = if_else(GebiedsCode == "4143122", "2091308", GebiedsCode)) %>% 
#   mutate(Gebied = if_else(Gebied == "Schelde St. Amands - Oude Briel (LO)", "Groot Schoor HAMME", Gebied)) %>% 
#   mutate(Analyseset = if_else(Analyseset == "boottelling", "SIGMA_MIDMA", Analyseset)) 
# 
# GrootSchorberekend2023 <- 
#   WV_DB %>% 
#   dplyr::filter(GebiedsCode == 4143122) %>% 
#   dplyr::filter(Telseizoen == "2023/24") %>% 
#   left_join(StAmandstotOudeBriel2020, by = c("NedNaam","Telling"), suffix = c("_winter2021", "_Baseline2020"),keep = TRUE) %>% 
#   mutate(across(c(Aantal_Baseline2020), ~replace_na(., 0))) %>% 
#   mutate(Aantal_diff = Aantal_winter2021 - Aantal_Baseline2020) %>% 
#   dplyr::filter(Aantal_diff >= 0) %>% 
#   select(ends_with("winter2021"), Aantal_diff) %>% 
#   select(-Aantal_winter2021) %>% 
#   rename_with(~ str_remove(.x, "_winter2021")) %>% 
#   rename(Aantal = Aantal_diff)%>% 
#   mutate(GebiedsCode = if_else(GebiedsCode == "4143122", "2091308", GebiedsCode)) %>% 
#   mutate(Gebied = if_else(Gebied == "Schelde St. Amands - Oude Briel (LO)", "Groot Schoor HAMME", Gebied)) %>% 
#   mutate(Analyseset = if_else(Analyseset == "boottelling", "SIGMA_MIDMA", Analyseset)) 
# 
# 
# datathvGrootschoor %>%
#   dplyr::filter(!(GebiedsCode == 2091308 & (Telseizoen == "2021/22" | Telseizoen == "2022/23" | Telseizoen == "2023/24"))) %>%
#   dplyr::filter(!(GebiedsCode == 4143122 & (Telseizoen == "2021/22" | Telseizoen == "2022/23" | Telseizoen == "2023/24"))) %>% 
#   bind_rows(GrootSchorberekend2021, GrootSchorberekend2022,GrootSchorberekend2023) %>%
#   bind_rows(StAmandstotOudeBriel2021false, StAmandstotOudeBriel2022false,StAmandstotOudeBriel2023false) %>% 
#     write_delim(paste0(pad_data, "datathvGrootSchoorHamme.csv"),
#                 delim = ";")
# 
# GrootSchoorHamme <- bind_rows(GrootSchorberekend2021, GrootSchorberekend2022,GrootSchorberekend2023) 
# 
# WV_DB <-
#   WV_DB %>% 
#   dplyr::filter(!(GebiedsCode == 4143122 & (Telseizoen == "2021/22" | Telseizoen == "2022/23" | Telseizoen == "2023/24"))) %>% 
#   bind_rows(StAmandstotOudeBriel2021false, StAmandstotOudeBriel2022false,StAmandstotOudeBriel2023false) 
#   
# #### ook nog aanpassen in Sigmadataset voor rapportage!
# 
# WV_DB <-
#   WV_DB %>% 
#   dplyr::filter(!(GebiedsCode == 2091308 & (Telseizoen == "2021/22" | Telseizoen == "2022/23" | Telseizoen ==   "2023/24"))) %>% 
# bind_rows(GrootSchoorHamme)

```
